In [69]:
# --  import libraries
import pandas as pd
import numpy as np
import pickle
import re
from itertools import combinations
import warnings
warnings.filterwarnings("ignore")
from datetime import datetime
import matplotlib.pyplot as plt
import seaborn as sns

# In this notebook we will be predicting the IVL using the Models we made

In [70]:
# read in data
matches_reference = pd.read_csv('matches_updated (1).csv'); display(matches_reference); print()
inference_pipeline_db = pd.read_csv('inference_pipeline_db.csv'); display(inference_pipeline_db); print()
teams = pd.read_csv('teams.xls'); display(teams); print()
duals = pd.read_csv('dual_meets.xls'); display(duals); print()
wrestlers = pd.read_csv('wrestlers_updated.csv'); display(wrestlers); print()

,dual_id,weight_class,event_date,home_wrestler_id,home_name,home_rank,away_wrestler_id,away_name,away_rank,home_win,win_type,Result,home_class,home_team_name,away_class,away_team_name
0,280,141,11/1/2025,267.0,Raymond Adams,160.0,825.0,John Hildebrandt,98.0,False,LDEC,LDEC 3 - 2,JR,Duke,JR,Sacred Heart
1,283,197,11/1/2025,878.0,Kael Bennie,46.0,263.0,Angelo Posada,20.0,False,LDEC,LDEC 5 - 4,SO,Utah Valley,FR,Stanford
2,283,285,11/1/2025,879.0,Jack Forbes,62.0,429.0,Jackson Mankowski,182.0,True,WDEC,WDEC 10 - 3,SR,Utah Valley,SO,Stanford
3,284,125,11/1/2025,784.0,Koda Holeman,40.0,530.0,Jacob Macatangay,69.0,True,WMD,WMD 20 - 8,JR,Cal Poly,JR,Purdue
4,284,133,11/1/2025,785.0,Anthony Lucio,245.0,226.0,Blake Boarman,57.0,False,LDEC,LDEC 8 - 2,RSFR,Cal Poly,SR,Purdue
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5835,547,174,2/23/2026,399.0,Joshua Roe,237.0,814.0,Beau Lewis,158.0,False,LDEC,LDEC 5 - 3,SO,Presbyterian,FR,VMI
5836,547,184,2/23/2026,400.0,Reed Douglass,72.0,815.0,Andrew Barford,162.0,True,WTF,WTF5 22 - 5 6:45,JR,Presbyterian,FR,VMI
5837,547,197,2/23/2026,911.0,Toler Hornick,207.0,816.0,Toby Schoffstall,74.0,False,LTF,LTF5 15 - 0 1:05,SO,Presbyterian,JR,VMI
5838,547,149,2/23/2026,398.0,Rey Ortiz,245.0,811.0,Patrick Jordon,77.0,False,LFALL,LFALL 4:22,SO,Presbyterian,JR,VMI
5839,547,285,2/23/2026,1484.0,Ryland Whitworth,157.0,1468.0,Drake Garrison,202.0,True,WTF,WTF5 21 - 5 5:00,FR,Presbyterian,SO,VMI

,wrestler_name,team_name,rank,team_rank,weight_classes,total_matches,total_wins,total_losses,win_rate,bonus_wins,bonus_rate,tf_wins,md_wins,fall_wins,dec_wins,avg_opponent_rank,avg_points_scored,avg_point_diff,std_point_diff
0,William Morrow,Bloomsburg,206,75,[157],22,3,19,13.6,1,4.5,1,0,0,2,113.41,2.68,-2.77,5.20
1,Mason Rebuck,Bloomsburg,53,75,[285],20,15,5,75.0,10,50.0,2,2,6,5,127.85,8.17,3.92,8.62
2,Noah Mulvaney,Bucknell,32,36,[165],20,17,3,85.0,7,35.0,3,3,1,10,93.00,9.22,5.33,6.26
3,Jordan Soriano,Drexel,60,44,[141],20,14,6,70.0,7,35.0,0,2,5,7,112.05,7.31,2.23,6.22
4,Jesse Mendez,Ohio State,1,2,[141],19,19,0,100.0,17,89.5,9,3,5,2,57.37,16.64,12.36,4.25
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1501,Alaa Aly,Edinboro,208,47,[184],1,0,1,0.0,0,0.0,0,0,0,0,40.00,5.00,-15.00,0.00
1502,Cole Tolley,West Virginia,114,17,[197],1,0,1,0.0,0,0.0,0,0,0,0,63.00,6.00,-15.00,0.00
1503,Winston McBride,Wyoming,182,21,[285],1,1,0,100.0,0,0.0,0,0,0,1,240.00,1.00,1.00,0.00
1504,Aiden Robertson,Air Force,222,52,[174],1,0,1,0.0,0,0.0,0,0,0,0,76.00,0.00,-5.00,0.00
1505,Foster Cardinale,Cornell,97,13,[141],1,1,0,100.0,0,0.0,0,0,0,1,151.00,7.00,4.00,0.00

    team_id                name
0         1       Northern Iowa
1         2  South Dakota State
2         3              Drexel
3         4   Northern Illinois
4         5    Central Michigan
..      ...                 ...
73       74             Indiana
74       75     Army West Point
75       76             Wyoming
76       77          Bellarmine
77       78               Brown

[78 rows x 2 columns]

,dual_id,team1_id,team1_rank,team1_score,team2_id,team2_rank,team2_score,event_date
0,1,1,14,20,2,20,14,01/10/26
1,2,1,14,22,3,42,16,01/10/26
2,3,3,42,21,4,45,12,01/10/26
3,4,2,20,28,5,50,10,01/10/26
4,5,5,50,23,6,55,15,01/10/26
...,...,...,...,...,...,...,...,...
579,580,50,26,22,33,35,18,02/19/26
580,581,63,47,28,8,75,10,02/19/26
581,582,44,39,37,34,57,3,02/19/26
582,583,54,42,32,60,65,14,02/19/26
583,584,12,8,45,43,68,3,02/18/26

      wrestler_id             name Class                 Team
0               1     Bowen Downey    SO        Northern Iowa
1               2    Julian Farber    SR        Northern Iowa
2               3        Max Brady    FR        Northern Iowa
3               4     Ethan Basile    SR        Northern Iowa
4               5  Cael Rahnavardi    SR        Northern Iowa
...           ...              ...   ...                  ...
1507           38   Landen Johnson    SO    Northern Illinois
1508          168    Nathan Taylor    SR               Lehigh
1509          897     James Conway    SR             Missouri
1510         2000     James Conway    SR  Franklin & Marshall
1511         2001    Nathan Taylor    JR         Pennsylvania

[1512 rows x 4 columns]

In [71]:
# -- Join class to inference_pipeline_db
inference_pipeline_db = inference_pipeline_db.merge(wrestlers[["name", "Team", "Class"]], left_on=['wrestler_name', 'team_name'], right_on = ['name', 'Team'])
inference_pipeline_db = inference_pipeline_db.drop(columns=['name', 'Team'])
inference_pipeline_db

,wrestler_name,team_name,rank,team_rank,weight_classes,total_matches,total_wins,total_losses,win_rate,bonus_wins,bonus_rate,tf_wins,md_wins,fall_wins,dec_wins,avg_opponent_rank,avg_points_scored,avg_point_diff,std_point_diff,Class
0,William Morrow,Bloomsburg,206,75,[157],22,3,19,13.6,1,4.5,1,0,0,2,113.41,2.68,-2.77,5.20,SR
1,Mason Rebuck,Bloomsburg,53,75,[285],20,15,5,75.0,10,50.0,2,2,6,5,127.85,8.17,3.92,8.62,SO
2,Noah Mulvaney,Bucknell,32,36,[165],20,17,3,85.0,7,35.0,3,3,1,10,93.00,9.22,5.33,6.26,JR
3,Jordan Soriano,Drexel,60,44,[141],20,14,6,70.0,7,35.0,0,2,5,7,112.05,7.31,2.23,6.22,SR
4,Jesse Mendez,Ohio State,1,2,[141],19,19,0,100.0,17,89.5,9,3,5,2,57.37,16.64,12.36,4.25,SR
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1501,Alaa Aly,Edinboro,208,47,[184],1,0,1,0.0,0,0.0,0,0,0,0,40.00,5.00,-15.00,0.00,RSFR
1502,Cole Tolley,West Virginia,114,17,[197],1,0,1,0.0,0,0.0,0,0,0,0,63.00,6.00,-15.00,0.00,SO
1503,Winston McBride,Wyoming,182,21,[285],1,1,0,100.0,0,0.0,0,0,0,1,240.00,1.00,1.00,0.00,SO
1504,Aiden Robertson,Air Force,222,52,[174],1,0,1,0.0,0,0.0,0,0,0,0,76.00,0.00,-5.00,0.00,FR
1505,Foster Cardinale,Cornell,97,13,[141],1,1,0,100.0,0,0.0,0,0,0,1,151.00,7.00,4.00,0.00,JR

In [72]:
def filter_weights(wrestlers: list, match_details=False):
  if match_details:
    print("Matches Detailed")
    display(matches_reference.query('home_name in @wrestlers or away_name in @wrestlers')); print()

  print("Overall Stats")
  display(inference_pipeline_db.query('wrestler_name in @wrestlers')); print()

wrestlers_125 = ["Davis Motyka", "Greg Diakomihalis", "Logan Brzozowski", "Sulayman Bah", "Chase Yasutake", "Marc-Anthony McGowan"]
filter_weights(wrestlers_125)

Overall Stats

,wrestler_name,team_name,rank,team_rank,weight_classes,total_matches,total_wins,total_losses,win_rate,bonus_wins,bonus_rate,tf_wins,md_wins,fall_wins,dec_wins,avg_opponent_rank,avg_points_scored,avg_point_diff,std_point_diff,Class
284,Sulayman Bah,Columbia,23,23,[125],13,9,4,69.2,6,46.2,4,1,1,3,86.69,11.45,6.00,8.66,JR
405,Logan Brzozowski,Harvard,45,51,[125],12,8,4,66.7,4,33.3,2,1,1,4,84.75,8.18,2.82,8.86,SO
480,Chase Yasutake,Brown,230,62,[125],11,1,10,9.1,1,9.1,0,0,1,0,105.91,0.67,-15.00,0.00,FR
563,Marc-Anthony McGowan,Princeton,13,32,[125],10,8,2,80.0,5,50.0,2,3,0,3,59.30,9.40,7.10,6.14,SO
584,Greg Diakomihalis,Cornell,50,13,[125],9,3,6,33.3,2,22.2,1,1,0,1,66.56,5.38,1.00,7.37,SR
901,Davis Motyka,Pennsylvania,37,26,[125],5,4,1,80.0,1,20.0,1,0,0,3,95.60,7.40,4.80,6.72,FR

In [73]:
# -- Create for all weights
wrestlers_133 = ["Evan Mougalian", "Ethan Rivera", "Coleman Nogle", "Evin Gursoy", "Douglas Shipers", "Tyler Ferrera"]
print("133 IVL WRESTLERS")
filter_weights(wrestlers_133); print(); print()

wrestlers_141 = ["Vince Cornella", "Matthew Martino", "Lorenzo Frezza", "Khimari Manns", "Dante Frinzi", "CJ Composto"]
print("141 IVL WRESTLERS")
filter_weights(wrestlers_141); print(); print()

wrestlers_149 = ["Jaxon Joy", "Richard Fedalen", "Jack Crook", "Eligh Rivera", "Austin McBurney", "Cross Wasilewski"]
print("149 IVL WRESTLERS")
filter_weights(wrestlers_149); print(); print()

wrestlers_157 = ["Meyer Shapiro", "Ethan Mojena", "Kai Owen", "Jimmy Harrington", "Rocco Camillaci", "Jude Swisher"]
print("157 IVL WRESTLERS")
filter_weights(wrestlers_157); print(); print()

wrestlers_165 = ["Cesar Alvan", "Joseph Cangro", "Maximus Norman", "Sean Seefeldt", "Benny Rogers", "Ty Whalen"]
print("165 IVL WRESTLERS")
filter_weights(wrestlers_165); print(); print()

wrestlers_174 = ["Simon Ruiz", "Haden Bottiglieri", "Caden Bellis", "Holden Garcia", "Drew Clearie", "Nick Fine"]
print("174 IVL WRESTLERS")
filter_weights(wrestlers_174); print(); print()

wrestlers_184 = ["Joe Curtis", "Xavier Giles", "Matthew Walsh", "Liam Carlin", "Connor O'Donnell", "Louis Cerchio"]
print("184 IVL WRESTLERS")
filter_weights(wrestlers_184); print(); print()

wrestlers_197 = ["Andrew Reall", "Aiden Hanning", "Hudson Skove", "Martin Cosgrove", "Conor McCloskey", "Jack Wehmeyer"]
print("197 IVL WRESTLERS")
filter_weights(wrestlers_197); print(); print()


wrestlers_285 = ["Vincent Mueller", "Sebastian Garibaldi", "Ashton Davis", "John Pardo", "Daniel Bittner", "Alex Semenenko"]
print("285 IVL WRESTLERS")
filter_weights(wrestlers_285); print(); print()

#all_wrestler_list = [wrestlers_125, wrestlers_133, wrestlers_141, wrestlers_149, wrestlers_157, wrestlers_165, wrestlers_174, wrestlers_184, wrestlers_197, wrestlers_285]
#weights = [125, 133, 141, 149, 157, 165, 174, 184, 197, 285]

133 IVL WRESTLERS
Overall Stats

,wrestler_name,team_name,rank,team_rank,weight_classes,total_matches,total_wins,total_losses,win_rate,bonus_wins,bonus_rate,tf_wins,md_wins,fall_wins,dec_wins,avg_opponent_rank,avg_points_scored,avg_point_diff,std_point_diff,Class
209,Douglas Shipers,Brown,254,62,[133],14,0,14,0.0,0,0.0,0,0,0,0,93.43,1.50,-11.00,5.66,FR
249,Evin Gursoy,Columbia,68,23,[133],14,10,4,71.4,5,35.7,1,3,1,5,106.21,5.77,3.54,5.95,FR
335,Coleman Nogle,Harvard,72,51,[133],12,6,6,50.0,3,25.0,0,1,2,3,89.33,4.80,-2.60,7.11,JR
462,Tyler Ferrera,Cornell,18,13,[133],11,8,3,72.7,2,18.2,1,1,0,6,68.18,7.36,2.45,5.96,SO
539,Evan Mougalian,Pennsylvania,16,26,[133],10,8,2,80.0,4,40.0,1,1,2,4,90.40,8.38,4.88,5.54,JR
560,Ethan Rivera,Princeton,45,32,[133],10,5,5,50.0,1,10.0,0,0,1,4,56.00,3.56,-1.56,3.40,SO

141 IVL WRESTLERS
Overall Stats

,wrestler_name,team_name,rank,team_rank,weight_classes,total_matches,total_wins,total_losses,win_rate,bonus_wins,bonus_rate,tf_wins,md_wins,fall_wins,dec_wins,avg_opponent_rank,avg_points_scored,avg_point_diff,std_point_diff,Class
257,Vince Cornella,Cornell,6,13,[141],13,12,1,92.3,5,38.5,1,2,2,7,76.69,7.73,5.27,4.27,RSJR
258,Matthew Martino,Princeton,28,32,"[141, 149]",13,5,8,38.5,2,15.4,0,1,1,3,44.38,6.42,-3.92,7.89,FR
273,Lorenzo Frezza,Columbia,46,23,[141],13,8,5,61.5,5,38.5,3,1,1,3,72.85,10.83,3.17,8.36,JR
495,Khimari Manns,Brown,67,62,[141],11,6,5,54.5,2,18.2,1,1,0,4,71.18,7.80,0.70,9.17,FR
603,Dante Frinzi,Harvard,133,51,[141],9,2,7,22.2,1,11.1,0,0,1,1,77.89,3.83,-5.33,6.53,SR
682,CJ Composto,Pennsylvania,10,26,[141],8,6,2,75.0,3,37.5,1,2,0,3,49.50,10.14,6.14,6.64,SR

149 IVL WRESTLERS
Overall Stats

,wrestler_name,team_name,rank,team_rank,weight_classes,total_matches,total_wins,total_losses,win_rate,bonus_wins,bonus_rate,tf_wins,md_wins,fall_wins,dec_wins,avg_opponent_rank,avg_points_scored,avg_point_diff,std_point_diff,Class
137,Jaxon Joy,Cornell,3,13,[149],15,14,1,93.3,12,80.0,6,5,1,2,72.67,12.57,10.43,5.96,FR
224,Austin McBurney,Brown,81,62,[149],14,8,6,57.1,4,28.6,2,2,0,4,94.50,7.85,2.15,9.38,JR
250,Eligh Rivera,Princeton,22,32,[149],14,8,6,57.1,0,0.0,0,0,0,8,49.57,5.29,-1.00,5.71,JR
341,Richard Fedalen,Columbia,69,23,[149],12,5,7,41.7,1,8.3,1,0,0,4,77.33,5.08,-2.50,8.10,SR
406,Jack Crook,Harvard,60,51,[149],12,8,4,66.7,4,33.3,3,1,0,4,100.08,11.33,3.67,9.39,JR
553,Cross Wasilewski,Pennsylvania,8,26,[149],10,9,1,90.0,7,70.0,2,2,3,2,107.20,10.43,7.43,6.85,SO

157 IVL WRESTLERS
Overall Stats

,wrestler_name,team_name,rank,team_rank,weight_classes,total_matches,total_wins,total_losses,win_rate,bonus_wins,bonus_rate,tf_wins,md_wins,fall_wins,dec_wins,avg_opponent_rank,avg_points_scored,avg_point_diff,std_point_diff,Class
247,Meyer Shapiro,Cornell,1,13,[157],14,14,0,100.0,11,78.6,8,2,1,3,67.50,14.85,11.85,5.03,JR
288,Ethan Mojena,Brown,88,62,[157],13,5,8,38.5,2,15.4,2,0,0,3,75.77,4.85,-2.23,10.05,JR
407,Jimmy Harrington,Harvard,16,51,[157],12,9,3,75.0,4,33.3,1,2,1,5,68.92,6.45,3.00,7.91,SR
580,Kai Owen,Columbia,34,23,[157],9,5,4,55.6,3,33.3,1,2,0,2,72.89,8.67,5.00,9.55,SR
714,Jude Swisher,Pennsylvania,12,26,[157],8,6,2,75.0,5,62.5,2,3,0,1,48.88,10.75,7.38,8.73,JR
780,Rocco Camillaci,Princeton,87,32,[157],7,2,5,28.6,0,0.0,0,0,0,2,58.57,2.43,-4.29,5.12,RSJR

165 IVL WRESTLERS
Overall Stats

,wrestler_name,team_name,rank,team_rank,weight_classes,total_matches,total_wins,total_losses,win_rate,bonus_wins,bonus_rate,tf_wins,md_wins,fall_wins,dec_wins,avg_opponent_rank,avg_points_scored,avg_point_diff,std_point_diff,Class
251,Ty Whalen,Princeton,18,32,[165],14,10,4,71.4,6,42.9,1,4,1,4,55.36,9.83,5.00,7.51,JR
264,Cesar Alvan,Columbia,20,23,[165],13,10,3,76.9,0,0.0,0,0,0,10,64.31,6.00,2.33,2.74,SR
311,Maximus Norman,Brown,48,62,[165],13,6,7,46.2,4,30.8,0,2,2,2,72.00,6.27,-0.27,7.80,FR
418,Joseph Cangro,Harvard,77,51,[165],11,5,6,45.5,4,36.4,0,2,2,1,78.00,5.11,0.11,7.22,JR
537,Sean Seefeldt,Pennsylvania,30,26,[165],10,7,3,70.0,3,30.0,0,3,0,4,70.30,6.00,3.20,5.57,JR
744,Benny Rogers,Cornell,66,13,"[157, 165]",7,3,4,42.9,2,28.6,1,1,0,1,77.00,7.29,-1.14,11.23,JR

174 IVL WRESTLERS
Overall Stats

,wrestler_name,team_name,rank,team_rank,weight_classes,total_matches,total_wins,total_losses,win_rate,bonus_wins,bonus_rate,tf_wins,md_wins,fall_wins,dec_wins,avg_opponent_rank,avg_points_scored,avg_point_diff,std_point_diff,Class
205,Simon Ruiz,Cornell,2,13,[174],14,14,0,100.0,6,42.9,3,2,1,8,55.14,9.85,7.15,5.67,SO
305,Nick Fine,Columbia,22,23,[174],13,10,3,76.9,8,61.5,3,4,1,2,81.92,10.00,6.00,7.54,SR
310,Drew Clearie,Brown,102,62,[174],13,6,7,46.2,3,23.1,0,1,2,3,88.08,6.00,-2.40,7.24,SR
450,Holden Garcia,Princeton,29,32,[174],11,7,4,63.6,5,45.5,1,3,1,2,66.00,7.20,3.10,7.39,RSSO
544,Caden Bellis,Pennsylvania,66,26,[174],10,5,5,50.0,0,0.0,0,0,0,5,69.00,3.11,-2.22,5.24,FR
894,Haden Bottiglieri,Harvard,82,51,[174],5,2,3,40.0,1,20.0,1,0,0,1,90.40,8.25,2.50,10.60,SO

184 IVL WRESTLERS
Overall Stats

,wrestler_name,team_name,rank,team_rank,weight_classes,total_matches,total_wins,total_losses,win_rate,bonus_wins,bonus_rate,tf_wins,md_wins,fall_wins,dec_wins,avg_opponent_rank,avg_points_scored,avg_point_diff,std_point_diff,Class
138,Louis Cerchio,Cornell,50,13,"[165, 184]",15,6,9,40.0,2,13.3,0,2,0,4,50.00,5.57,0.07,7.04,FR
237,Xavier Giles,Princeton,73,32,"[174, 184]",14,5,9,35.7,2,14.3,0,2,0,3,64.86,5.08,-3.77,7.96,SO
411,Matthew Walsh,Harvard,81,51,[184],12,6,6,50.0,2,16.7,0,1,1,4,99.08,4.70,0.30,4.47,JR
582,Connor O'Donnell,Brown,155,62,[184],9,1,8,11.1,0,0.0,0,0,0,1,67.78,3.67,-7.56,6.41,SO
753,Liam Carlin,Pennsylvania,58,26,[184],7,3,4,42.9,0,0.0,0,0,0,3,82.29,3.71,-1.57,6.75,FR
903,Joe Curtis,Columbia,19,23,[184],5,5,0,100.0,5,100.0,0,1,4,0,99.20,16.00,12.00,0.00,JR

197 IVL WRESTLERS
Overall Stats

,wrestler_name,team_name,rank,team_rank,weight_classes,total_matches,total_wins,total_losses,win_rate,bonus_wins,bonus_rate,tf_wins,md_wins,fall_wins,dec_wins,avg_opponent_rank,avg_points_scored,avg_point_diff,std_point_diff,Class
285,Conor McCloskey,Princeton,148,32,"[197, 285]",13,0,13,0.0,0,0.0,0,0,0,0,55.62,2.27,-9.09,5.49,FR
384,Andrew Reall,Brown,18,62,[197],12,11,1,91.7,7,58.3,3,3,1,4,86.33,11.18,7.91,6.02,SO
465,Jack Wehmeyer,Columbia,42,23,[197],11,8,3,72.7,5,45.5,2,1,2,3,107.27,7.78,5.56,6.84,JR
482,Martin Cosgrove,Pennsylvania,80,26,[197],11,4,7,36.4,1,9.1,0,1,0,3,74.73,4.73,-0.73,7.00,JR
559,Hudson Skove,Harvard,117,51,"[197, 285]",10,3,7,30.0,0,0.0,0,0,0,3,62.70,3.44,-6.44,8.57,SO
671,Aiden Hanning,Cornell,87,13,[197],8,1,7,12.5,1,12.5,0,0,1,0,48.25,1.14,-4.00,1.91,JR

285 IVL WRESTLERS
Overall Stats

,wrestler_name,team_name,rank,team_rank,weight_classes,total_matches,total_wins,total_losses,win_rate,bonus_wins,bonus_rate,tf_wins,md_wins,fall_wins,dec_wins,avg_opponent_rank,avg_points_scored,avg_point_diff,std_point_diff,Class
294,Alex Semenenko,Brown,22,62,[285],13,11,2,84.6,6,46.2,2,0,4,5,113.31,7.89,3.22,8.93,SR
374,Vincent Mueller,Columbia,26,23,[285],12,10,2,83.3,7,58.3,1,2,4,3,88.75,7.25,2.75,10.10,JR
531,John Pardo,Pennsylvania,85,26,[285],10,6,4,60.0,3,30.0,2,0,1,3,120.80,7.22,0.22,11.37,SO
668,Sebastian Garibaldi,Princeton,121,32,[285],8,1,7,12.5,1,12.5,0,0,1,0,65.88,2.50,-7.33,6.02,SR
767,Ashton Davis,Cornell,48,13,[285],7,0,7,0.0,0,0.0,0,0,0,0,21.57,2.14,-4.43,3.41,JR
1077,Daniel Bittner,Harvard,174,51,[285],3,1,2,33.3,0,0.0,0,0,0,1,75.67,3.33,-8.00,9.64,SR

# Find Test Cases

In [74]:
matches_reference.query('home_name == "Simon Ruiz" or away_name == "Simon Ruiz"')

,dual_id,weight_class,event_date,home_wrestler_id,home_name,home_rank,away_wrestler_id,away_name,away_rank,home_win,win_type,Result,home_class,home_team_name,away_class,away_team_name
490,222,174,11/15/2025,596.0,Alex Facundo,14.0,175.0,Simon Ruiz,5.0,False,LDEC,LDEC 2 - 0,JR,Oklahoma State,SO,Cornell
494,215,174,11/15/2025,33.0,Jared Simma,20.0,175.0,Simon Ruiz,5.0,False,LMD,LMD 18 - 4,SR,Northern Iowa,SO,Cornell
2726,286,174,1/10/2026,503.0,Myles Takats,17.0,175.0,Simon Ruiz,5.0,False,LDEC,LDEC 5 - 2,JR,Bucknell,SO,Cornell
2844,16,174,1/10/2026,165.0,Richie Grungo,106.0,175.0,Simon Ruiz,5.0,False,LTF,LTF5 15 - 0 7:00,SO,Lehigh,SO,Cornell
3074,325,174,1/16/2026,175.0,Simon Ruiz,4.0,964.0,Cooper Haase,68.0,True,WTF,WTF5 20 - 4 5:25,SO,Cornell,SO,Army West Point
3751,360,174,1/24/2026,175.0,Simon Ruiz,4.0,1060.0,Drew Clearie,109.0,True,WFALL,WFALL 4:16,SO,Cornell,SR,Brown
3796,359,174,1/24/2026,175.0,Simon Ruiz,4.0,74.0,Ben Smith,187.0,True,WTF,WTF5 21 - 3 2:39,SO,Cornell,FR,Harvard
4218,396,174,1/31/2026,175.0,Simon Ruiz,4.0,320.0,Cael Valencia,76.0,True,WDEC,WDEC 7 - 5,SO,Cornell,SR,Arizona State
4227,397,174,1/31/2026,175.0,Simon Ruiz,4.0,519.0,Nick Fine,30.0,True,WDEC,WDEC 8 - 5,SO,Cornell,SR,Columbia
4747,507,174,2/7/2026,458.0,Holden Garcia,35.0,175.0,Simon Ruiz,2.0,False,LDEC,LDEC 5 - 1,RSSO,Princeton,SO,Cornell
4827,494,174,2/8/2026,561.0,Caden Bellis,46.0,175.0,Simon Ruiz,2.0,False,LMD,LMD 9 - 0,FR,Pennsylvania,SO,Cornell
5181,458,174,2/14/2026,175.0,Simon Ruiz,2.0,381.0,Carter Baer,23.0,True,WDEC,WDEC 2 - 0,SO,Cornell,JR,Binghamton
5538,571,174,2/20/2026,241.0,Matthew Singleton,8.0,175.0,Simon Ruiz,2.0,False,LDEC,LDEC 8 - 6,JR,NC State,SO,Cornell
5792,560,174,2/22/2026,270.0,Aiden Wallace,33.0,175.0,Simon Ruiz,2.0,False,LDEC,LDEC 8 - 1,JR,Duke,SO,Cornell

In [75]:
display(inference_pipeline_db.query('wrestler_name == "Simon Ruiz"'))
display(inference_pipeline_db.query('wrestler_name == "Nick Fine"'))

,wrestler_name,team_name,rank,team_rank,weight_classes,total_matches,total_wins,total_losses,win_rate,bonus_wins,bonus_rate,tf_wins,md_wins,fall_wins,dec_wins,avg_opponent_rank,avg_points_scored,avg_point_diff,std_point_diff,Class
205,Simon Ruiz,Cornell,2,13,[174],14,14,0,100.0,6,42.9,3,2,1,8,55.14,9.85,7.15,5.67,SO

,wrestler_name,team_name,rank,team_rank,weight_classes,total_matches,total_wins,total_losses,win_rate,bonus_wins,bonus_rate,tf_wins,md_wins,fall_wins,dec_wins,avg_opponent_rank,avg_points_scored,avg_point_diff,std_point_diff,Class
305,Nick Fine,Columbia,22,23,[174],13,10,3,76.9,8,61.5,3,4,1,2,81.92,10.0,6.0,7.54,SR

In [76]:
matches_reference.query('home_name == "Jaxon Joy" or away_name == "Jaxon Joy"')

,dual_id,weight_class,event_date,home_wrestler_id,home_name,home_rank,away_wrestler_id,away_name,away_rank,home_win,win_type,Result,home_class,home_team_name,away_class,away_team_name
487,222,149,11/15/2025,593.0,Casey Swiderski,21.0,172.0,Jaxon Joy,3.0,False,LDEC,LDEC 4 - 3,RSJR,Oklahoma State,FR,Cornell
565,215,149,11/15/2025,91.0,Caleb Rathjen,44.0,172.0,Jaxon Joy,3.0,False,LMD,LMD 11 - 2,SR,Northern Iowa,FR,Cornell
2022,65,149,12/21/2025,172.0,Jaxon Joy,3.0,609.0,Carter McCallister,138.0,True,WMD,WMD 14 - 5,FR,Cornell,SO,Little Rock
2087,56,149,12/21/2025,172.0,Jaxon Joy,3.0,574.0,William Baysingar,94.0,True,WTF,WTF5 17 - 2 5:37,FR,Cornell,SO,Illinois
2723,286,149,1/10/2026,500.0,Riley Bower,55.0,172.0,Jaxon Joy,3.0,False,LTF,LTF5 17 - 2 7:00,SR,Bucknell,FR,Cornell
2847,16,149,1/10/2026,162.0,Owen Reinsel,48.0,172.0,Jaxon Joy,3.0,False,LMD,LMD 9 - 0,JR,Lehigh,FR,Cornell
3077,325,149,1/16/2026,172.0,Jaxon Joy,3.0,1247.0,Ryan Franco,184.0,True,WTF,WTF5 17 - 1 5:14,FR,Cornell,SR,Army West Point
3748,360,149,1/24/2026,172.0,Jaxon Joy,3.0,1057.0,Austin McBurney,72.0,True,WTF,WTF5 17 - 1 4:37,FR,Cornell,JR,Brown
3793,359,149,1/24/2026,172.0,Jaxon Joy,3.0,71.0,Jack Crook,58.0,True,WMD,WMD 16 - 2,FR,Cornell,JR,Harvard
4211,397,149,1/31/2026,172.0,Jaxon Joy,3.0,516.0,Richard Fedalen,68.0,True,WTF,WTF5 15 - 0 2:29,FR,Cornell,SR,Columbia
4221,396,149,1/31/2026,172.0,Jaxon Joy,3.0,317.0,Daniel Miranda,175.0,True,WTF,WTF5 18 - 1 3:23,FR,Cornell,SO,Arizona State
4744,507,149,2/7/2026,455.0,Eligh Rivera,19.0,172.0,Jaxon Joy,3.0,False,LMD,LMD 13 - 0,JR,Princeton,FR,Cornell
4844,494,149,2/8/2026,558.0,Cross Wasilewski,6.0,172.0,Jaxon Joy,3.0,False,LDEC,LDEC 5 - 1,SO,Pennsylvania,FR,Cornell
5560,571,149,2/20/2026,238.0,Koy Buesgens,5.0,172.0,Jaxon Joy,3.0,True,WDEC,WDEC 6 - 3,SO,NC State,FR,Cornell
5786,560,149,2/22/2026,268.0,Dylan Ross,103.0,172.0,Jaxon Joy,3.0,False,LFALL,LFALL 3:54,RSFR,Duke,FR,Cornell

In [77]:
display(inference_pipeline_db.query('wrestler_name == "Jaxon Joy"'))
display(inference_pipeline_db.query('wrestler_name == "Jack Crook"'))

,wrestler_name,team_name,rank,team_rank,weight_classes,total_matches,total_wins,total_losses,win_rate,bonus_wins,bonus_rate,tf_wins,md_wins,fall_wins,dec_wins,avg_opponent_rank,avg_points_scored,avg_point_diff,std_point_diff,Class
137,Jaxon Joy,Cornell,3,13,[149],15,14,1,93.3,12,80.0,6,5,1,2,72.67,12.57,10.43,5.96,FR

,wrestler_name,team_name,rank,team_rank,weight_classes,total_matches,total_wins,total_losses,win_rate,bonus_wins,bonus_rate,tf_wins,md_wins,fall_wins,dec_wins,avg_opponent_rank,avg_points_scored,avg_point_diff,std_point_diff,Class
406,Jack Crook,Harvard,60,51,[149],12,8,4,66.7,4,33.3,3,1,0,4,100.08,11.33,3.67,9.39,JR

In [78]:
wrestlers

      wrestler_id             name Class                 Team
0               1     Bowen Downey    SO        Northern Iowa
1               2    Julian Farber    SR        Northern Iowa
2               3        Max Brady    FR        Northern Iowa
3               4     Ethan Basile    SR        Northern Iowa
4               5  Cael Rahnavardi    SR        Northern Iowa
...           ...              ...   ...                  ...
1507           38   Landen Johnson    SO    Northern Illinois
1508          168    Nathan Taylor    SR               Lehigh
1509          897     James Conway    SR             Missouri
1510         2000     James Conway    SR  Franklin & Marshall
1511         2001    Nathan Taylor    JR         Pennsylvania

[1512 rows x 4 columns]

In [79]:
# -- 1 -- BASIC LOGREG (win_rate difference)
with open("logreg_model_OFFICIAL.pkl", "rb") as f:
    logreg_model = pickle.load(f)

# -- 2 -- DECISION TREE
with open("dt_model_tuned_OFFICIAL.pkl", "rb") as f:
    dt_model = pickle.load(f)

# -- 3 -- XGBoost w/o ranks
with open("xgboost_model_tuned_noranks_OFFICIAL.pkl", "rb") as f:
    xgb_model1 = pickle.load(f)

# -- 4 -- XGbosst w rank
with open("xgb_with_ranks_tuned_OFFICIAL.pkl", "rb") as f:
    xgb_model2 = pickle.load(f)



# -- Features Dt and XGBoost(1)
with open("features_dt_xgb1.pkl", "rb") as f:
    features_dt_xgb1 = pickle.load(f)


# -- Features XGBoost(2)
with open("xgb_w_ranks_features.pkl", "rb") as f:
    features_xgb2 = pickle.load(f)

In [80]:
# ============================================
# FUNCTION TO GET MATCHUP HISTORY
# ============================================

def get_wrestler_match_history(wrestler1_name, wrestler2_name, matches_df):
    """
    Get complete match history between two wrestlers from matches_reference.
    Returns dictionary of historical features.
    """

    # Find all matches between these two wrestlers
    mask = (
        ((matches_df['home_name'] == wrestler1_name) & (matches_df['away_name'] == wrestler2_name)) |
        ((matches_df['home_name'] == wrestler2_name) & (matches_df['away_name'] == wrestler1_name))
    )

    history = matches_df[mask].copy().sort_values('event_date')

    if len(history) == 0:
        return {
            'wrestled_before': 0,
            'home_point_diff_rematches': 0,
            'home_pinned_away': 0,
            'total_matches': 0,
            'w1_wins': 0,
            'w2_wins': 0,
            'avg_point_diff_w1': 0,
            'last_match_date': None,
            'last_winner': None
        }

    # Calculate head-to-head stats
    w1_name = wrestler1_name
    w2_name = wrestler2_name

    w1_wins = 0
    w2_wins = 0
    total_point_diff_w1 = 0
    point_diff_count = 0
    pins_by_w1 = 0
    pins_by_w2 = 0

    # Store match results
    match_records = []

    for idx, row in history.iterrows():
        # Determine winner
        if row['home_name'] == w1_name:
            winner = w1_name if row['home_win'] else w2_name
        else:
            winner = w2_name if row['home_win'] else w1_name

        # Calculate point differential (from w1's perspective)
        point_diff = 0
        if 'FALL' not in str(row['win_type']):
            try:
                parts = str(row['Result']).split()
                scores = [int(x) for x in parts if x.isdigit()]
                if len(scores) >= 2:
                    score1, score2 = scores[0], scores[1]

                    # Determine scores from w1's perspective
                    if row['home_name'] == w1_name:
                        if row['home_win']:
                            point_diff = score1 - score2
                        else:
                            point_diff = score2 - score1
                    else:
                        if not row['home_win']:
                            point_diff = score1 - score2
                        else:
                            point_diff = score2 - score1

                    total_point_diff_w1 += point_diff
                    point_diff_count += 1
            except:
                point_diff = 0

        # Check for pins
        was_pin = 'FALL' in str(row['win_type'])
        if was_pin:
            if winner == w1_name:
                pins_by_w1 += 1
            else:
                pins_by_w2 += 1

        # Count wins
        if winner == w1_name:
            w1_wins += 1
        else:
            w2_wins += 1

        # Store match record
        match_records.append({
            'date': row['event_date'],
            'home': row['home_name'],
            'away': row['away_name'],
            'winner': winner,
            'point_diff': point_diff,
            'was_pin': was_pin,
            'result': row['Result'],
            'win_type': row['win_type']
        })

    # Calculate averages
    avg_point_diff_w1 = total_point_diff_w1 / point_diff_count if point_diff_count > 0 else 0

    # Add winner column to history
    history['winner'] = [m['winner'] for m in match_records]

    return {
        'wrestled_before': 1 if len(history) > 0 else 0,
        'home_point_diff_rematches': round(avg_point_diff_w1, 3),
        'home_pinned_away': 1 if pins_by_w1 > 0 else 0,
        'total_matches': len(history),
        'w1_wins': w1_wins,
        'w2_wins': w2_wins,
        'avg_point_diff_w1': round(avg_point_diff_w1, 3),
        'pins_by_w1': pins_by_w1,
        'pins_by_w2': pins_by_w2,
        'last_match_date': history.iloc[-1]['event_date'] if len(history) > 0 else None,
        'last_winner': history.iloc[-1]['winner'] if len(history) > 0 else None,
        'match_history': history
    }


# ============================================
# FUNCTION TO PREPARE FEATURES FOR A MATCHUP
# ============================================

def prepare_matchup_features(w1_name, w2_name, historical_features, inference_db, team_name = "Columbia", weight_class=125):
    """
    Prepare all features needed for models given two wrestlers.
    Columbia always home, otherwise lower rank is home.
    """

    # Get wrestler data from inference pipeline
    w1_data = inference_db[inference_db['wrestler_name'] == w1_name].iloc[0]
    w2_data = inference_db[inference_db['wrestler_name'] == w2_name].iloc[0]

    # Determine home/away: Columbia always home, otherwise by rank (lower rank = better)
    if w1_data['team_name'] == team_name:
        home, away = w1_data, w2_data
        home_name, away_name = w1_name, w2_name
        # Historical features are from w1's perspective, and home is w1, so no adjustment
        point_diff_adjustment = 1
    elif w2_data['team_name'] == team_name:
        home, away = w2_data, w1_data
        home_name, away_name = w2_name, w1_name
        # Historical features are from w1's perspective, but home is w2, so need to flip sign
        point_diff_adjustment = -1
    elif w1_data['rank'] < w2_data['rank']:
        home, away = w1_data, w2_data
        home_name, away_name = w1_name, w2_name
        point_diff_adjustment = 1
    else:
        home, away = w2_data, w1_data
        home_name, away_name = w2_name, w1_name
        point_diff_adjustment = -1

    print(f"\n📌 Home wrestler: {home_name} (Rank: {home['rank']}, Team: {home['team_name']})")
    print(f"📌 Away wrestler: {away_name} (Rank: {away['rank']}, Team: {away['team_name']})")

    # Calculate differential features
    features = {}

    # Basic differentials
    features['matches_wrestled_diff'] = home['total_matches'] - away['total_matches']
    features['win_rate_diff'] = round(home['win_rate']/100 - away['win_rate']/100, 4)
    features['bonus_rate_diff'] = round(home['bonus_rate']/100 - away['bonus_rate']/100, 4)
    features['pin_count_diff'] = home['fall_wins'] - away['fall_wins']
    features['avg_point_diff_diff'] = round(home['avg_point_diff'] - away['avg_point_diff'], 4)
    features['avg_points_scored_diff'] = round(home['avg_points_scored'] - away['avg_points_scored'], 4)
    features['std_point_diff_diff'] = round(home['std_point_diff'] - away['std_point_diff'], 4)
    features['team_rank_diff'] = home['team_rank'] - away['team_rank']

    # Historical features - ADJUST SIGN BASED ON WHO IS HOME
    features['wrestled_before'] = historical_features['wrestled_before']
    # Flip the sign if home is not the same as w1 (the perspective used in historical_features)
    features['home_point_diff_rematches'] = round(historical_features['home_point_diff_rematches'] * point_diff_adjustment, 3)
    features['home_pinned_away'] = historical_features['home_pinned_away'] if point_diff_adjustment == 1 else 0

    # Weight class dummies
    weight_classes = [133, 141, 149, 157, 165, 174, 184, 197, 285]
    for wc in weight_classes:
        features[f'weight_class_{wc}'] = 1 if weight_class == wc else 0

    # Class dummies
    all_classes = ['JR', 'RSFR', 'RSJR', 'RSSO', 'RSSR', 'SO', 'SR']

    for cls in all_classes:
        features[f'home_class_{cls}'] = 1 if home['Class'] == cls else 0

    for cls in all_classes:
        features[f'away_class_{cls}'] = 1 if away['Class'] == cls else 0

    return features, home_name, away_name, home, away


# ============================================


# ============================================
# FIXED FUNCTION TO MAKE PREDICTIONS
# ============================================

def predict_matchup(w1_name, w2_name, features, home_name, away_name):
    """
    Make predictions using all 4 models.
    """

    # Create dataframes with correct feature order
    df_dt = pd.DataFrame([{f: features.get(f, 0) for f in features_dt_xgb1}])
    df_xgb2 = pd.DataFrame([{f: features.get(f, 0) for f in features_dt_xgb2}])

    # Make predictions
    results = {
        'home_wrestler': home_name,
        'away_wrestler': away_name
    }

    # LOGREG
    logreg_input = [[features['win_rate_diff']]]
    logreg_proba = logreg_model.predict_proba(logreg_input)[0]
    logreg_pred = logreg_model.predict(logreg_input)[0]

    results['logreg_pred'] = logreg_pred
    results['logreg_winner'] = home_name if logreg_pred == 1 else away_name
    results['logreg_prob'] = round(logreg_proba[1] if logreg_pred == 1 else logreg_proba[0], 4)

    # DT
    dt_input = df_dt[features_dt_xgb1]
    dt_proba = dt_model.predict_proba(dt_input)[0]
    dt_pred = dt_model.predict(dt_input)[0]

    results['dt_pred'] = dt_pred
    results['dt_winner'] = home_name if dt_pred == 1 else away_name
    results['dt_prob'] = round(dt_proba[1] if dt_pred == 1 else dt_proba[0], 4)

    # XGB1 (no ranks)
    xgb1_input = df_dt[features_dt_xgb1]
    xgb1_proba = xgb_model1.predict_proba(xgb1_input)[0]
    xgb1_pred = xgb_model1.predict(xgb1_input)[0]

    results['xgb1_pred'] = xgb1_pred
    results['xgb1_winner'] = home_name if xgb1_pred == 1 else away_name
    results['xgb1_prob'] = round(xgb1_proba[1] if xgb1_pred == 1 else xgb1_proba[0], 4)

    # XGB2 (with ranks)
    xgb2_input = df_xgb2[features_xgb2]
    xgb2_proba = xgb_model2.predict_proba(xgb2_input)[0]
    xgb2_pred = xgb_model2.predict(xgb2_input)[0]

    results['xgb2_pred'] = xgb2_pred
    results['xgb2_winner'] = home_name if xgb2_pred == 1 else away_name
    results['xgb2_prob'] = round(xgb2_proba[1] if xgb2_pred == 1 else xgb2_proba[0], 4)

    return results


# ============================================
# FUNCTION TO PRINT DETAILED FEATURE INFO
# ============================================

# ============================================
# FUNCTION TO PRINT DETAILED FEATURE INFO
# ============================================

def print_matchup_details(w1_name, w2_name, historical_features, features, results, home_name, away_name, home_data, away_data):
    """
    Print detailed information about a matchup including features and predictions.
    """

    print("\n" + "="*80)
    print(f"🔍 MATCHUP DETAILS: {w1_name} vs {w2_name}")
    print("="*80)

    # Historical Summary
    print(f"\n📜 HISTORICAL SUMMARY:")
    if historical_features['wrestled_before']:
        print(f"   Previous matches: {historical_features['total_matches']}")
        print(f"   {w1_name} wins: {historical_features['w1_wins']}")
        print(f"   {w2_name} wins: {historical_features['w2_wins']}")
        print(f"   Avg point diff ({w1_name}'s perspective): {historical_features['avg_point_diff_w1']}")
        print(f"   Last match: {historical_features['last_match_date']} (Winner: {historical_features['last_winner']})")
    else:
        print("   No previous matches")

    # Historical features for models
    print(f"\n🔍 HISTORICAL FEATURES FOR MODELS:")
    print(f"   wrestled_before: {features['wrestled_before']}")
    print(f"   home_point_diff_rematches: {features['home_point_diff_rematches']}")
    print(f"   home_pinned_away: {features['home_pinned_away']}")

    # Key differentials
    print(f"\n📊 KEY DIFFERENTIALS (home - away):")
    print(f"   win_rate_diff: {features['win_rate_diff']:.4f} ({home_name} {home_data['win_rate']}% - {away_name} {away_data['win_rate']}%)")
    print(f"   matches_wrestled_diff: {features['matches_wrestled_diff']}")
    print(f"   bonus_rate_diff: {features['bonus_rate_diff']:.4f}")
    print(f"   avg_point_diff_diff: {features['avg_point_diff_diff']:.4f}")
    print(f"   team_rank_diff: {features['team_rank_diff']}")

    # Create dataframes to show full feature arrays
    print(f"\n📊 FULL FEATURE ARRAYS:")

    # DT/XGB1 features
    print(f"\n📊 DT/XGB1 features ({len(features_dt_xgb1)} total):")
    df_dt = pd.DataFrame([{f: features.get(f, 0) for f in features_dt_xgb1}])
    for i, feat in enumerate(features_dt_xgb1[:10]):  # Show first 10
        print(f"   {i+1:2d}. {feat:35} = {df_dt[feat].iloc[0]:8.4f}")
    print("   ...")

    # XGB2 features
    print(f"\n📊 XGB2 features ({len(features_xgb2)} total):")
    df_xgb2 = pd.DataFrame([{f: features.get(f, 0) for f in features_xgb2}])
    for i, feat in enumerate(features_xgb2[:10]):  # Show first 10
        print(f"   {i+1:2d}. {feat:35} = {df_xgb2[feat].iloc[0]:8.4f}")
    print("   ...")

    # Predictions
    print(f"\n🔮 PREDICTIONS:")
    print(f"   LOGREG: {results['logreg_winner']} wins with {results['logreg_prob']*100:.1f}% confidence")
    print(f"   DT    : {results['dt_winner']} wins with {results['dt_prob']*100:.1f}% confidence")
    print(f"   XGB1  : {results['xgb1_winner']} wins with {results['xgb1_prob']*100:.1f}% confidence")
    print(f"   XGB2  : {results['xgb2_winner']} wins with {results['xgb2_prob']*100:.1f}% confidence")

    # Check agreement
    winners = [results['logreg_winner'], results['dt_winner'], results['xgb1_winner'], results['xgb2_winner']]
    if all(w == winners[0] for w in winners):
        print(f"\n✅ All models agree: {winners[0]} wins!")
    else:
        print(f"\n⚠️ Models disagree on winner")

# ============================================
# TEST CASE 1: SIMON RUIZ vs NICK FINE
# ============================================

print("\n" + "="*100)
print("🔍 IVY LEAGUE TEST CASE 1: SIMON RUIZ vs NICK FINE")
print("="*100)

# Get their match history
hist_features_ruiz = get_wrestler_match_history(
    "Simon Ruiz", "Nick Fine", matches_reference
)

print(f"\n📜 Raw Historical Features (from Simon's perspective):")
print(f"   wrestled_before: {hist_features_ruiz['wrestled_before']}")
print(f"   home_point_diff_rematches: {hist_features_ruiz['home_point_diff_rematches']}")
print(f"   total_matches: {hist_features_ruiz['total_matches']}")
print(f"   Simon Ruiz wins: {hist_features_ruiz['w1_wins']}")
print(f"   Nick Fine wins: {hist_features_ruiz['w2_wins']}")
print(f"   Avg point diff (Simon's perspective): {hist_features_ruiz['avg_point_diff_w1']}")

# Prepare features for prediction
print(f"\n📊 Wrestler Data from Inference Pipeline:")
simon_data = inference_pipeline_db[inference_pipeline_db['wrestler_name'] == 'Simon Ruiz'].iloc[0]
nick_data = inference_pipeline_db[inference_pipeline_db['wrestler_name'] == 'Nick Fine'].iloc[0]

print(f"   Simon Ruiz - Rank: {simon_data['rank']}, Team: {simon_data['team_name']}, Win Rate: {simon_data['win_rate']}%")
print(f"   Nick Fine - Rank: {nick_data['rank']}, Team: {nick_data['team_name']}, Win Rate: {nick_data['win_rate']}%")

# Calculate win_rate_diff for LOGREG
win_rate_diff = simon_data['win_rate']/100 - nick_data['win_rate']/100
print(f"\n📊 LOGREG Input (win_rate_diff): {win_rate_diff:.4f} (Simon {simon_data['win_rate']}% - Nick {nick_data['win_rate']}%)")

# Prepare features for prediction
features_ruiz, home_name_ruiz, away_name_ruiz, home_data_ruiz, away_data_ruiz = prepare_matchup_features(
    "Simon Ruiz", "Nick Fine", hist_features_ruiz, inference_pipeline_db, weight_class=174
)

# Make predictions
results_ruiz = predict_matchup("Simon Ruiz", "Nick Fine", features_ruiz, home_name_ruiz, away_name_ruiz)

# Print detailed information
print_matchup_details(
    "Simon Ruiz", "Nick Fine",
    hist_features_ruiz, features_ruiz, results_ruiz,
    home_name_ruiz, away_name_ruiz, home_data_ruiz, away_data_ruiz
)


# ============================================
# TEST CASE 2: JAXON JOY vs JACK CROOK
# ============================================

print("\n" + "="*100)
print("🔍 IVY LEAGUE TEST CASE 2: JAXON JOY vs JACK CROOK")
print("="*100)

# Get their match history
hist_features_joy = get_wrestler_match_history(
    "Jaxon Joy", "Jack Crook", matches_reference
)

print(f"\n📜 Raw Historical Features (from Jaxon's perspective):")
print(f"   wrestled_before: {hist_features_joy['wrestled_before']}")
print(f"   home_point_diff_rematches: {hist_features_joy['home_point_diff_rematches']}")
print(f"   total_matches: {hist_features_joy['total_matches']}")
print(f"   Jaxon Joy wins: {hist_features_joy['w1_wins']}")
print(f"   Jack Crook wins: {hist_features_joy['w2_wins']}")
print(f"   Avg point diff (Jaxon's perspective): {hist_features_joy['avg_point_diff_w1']}")

# Prepare features for prediction
print(f"\n📊 Wrestler Data from Inference Pipeline:")
jaxon_data = inference_pipeline_db[inference_pipeline_db['wrestler_name'] == 'Jaxon Joy'].iloc[0]
jack_data = inference_pipeline_db[inference_pipeline_db['wrestler_name'] == 'Jack Crook'].iloc[0]

print(f"   Jaxon Joy - Rank: {jaxon_data['rank']}, Team: {jaxon_data['team_name']}, Win Rate: {jaxon_data['win_rate']}%")
print(f"   Jack Crook - Rank: {jack_data['rank']}, Team: {jack_data['team_name']}, Win Rate: {jack_data['win_rate']}%")

# Calculate win_rate_diff for LOGREG
win_rate_diff_joy = jaxon_data['win_rate']/100 - jack_data['win_rate']/100
print(f"\n📊 LOGREG Input (win_rate_diff): {win_rate_diff_joy:.4f} (Jaxon {jaxon_data['win_rate']}% - Jack {jack_data['win_rate']}%)")

# Prepare features for prediction
features_joy, home_name_joy, away_name_joy, home_data_joy, away_data_joy = prepare_matchup_features(
    "Jaxon Joy", "Jack Crook", hist_features_joy, inference_pipeline_db, weight_class=149
)

# Make predictions
results_joy = predict_matchup("Jaxon Joy", "Jack Crook", features_joy, home_name_joy, away_name_joy)

# Print detailed information
print_matchup_details(
    "Jaxon Joy", "Jack Crook",
    hist_features_joy, features_joy, results_joy,
    home_name_joy, away_name_joy, home_data_joy, away_data_joy
)


# ============================================
# VERIFICATION OF HOME/AWAY RULES
# ============================================

print("\n" + "="*100)
print("🔍 VERIFYING HOME/AWAY RULES")
print("="*100)

print("\nRule 1: Columbia always home")
print("   Sulayman Bah (Columbia) vs anyone → Sulayman Bah should be home")

# Test Columbia rule
sulayman_data = inference_pipeline_db[inference_pipeline_db['wrestler_name'] == 'Sulayman Bah'].iloc[0]
print(f"   Sulayman Bah - Team: {sulayman_data['team_name']}")

print("\nRule 2: Otherwise, lower rank is home")
print("   Jaxon Joy (Rank 3) vs Jack Crook (Rank 60) → Jaxon Joy should be home")
print(f"   Jaxon Joy rank: {jaxon_data['rank']}, Jack Crook rank: {jack_data['rank']}")
print(f"   Actual home in test case: {home_name_joy}")

print("\nRule 3: Historical point diff adjusted based on home")
print("   Jaxon Joy vs Jack Crook - Jaxon won by 14")
print(f"   Raw historical (Jaxon's perspective): {hist_features_joy['avg_point_diff_w1']}")
print(f"   Adjusted for home ({home_name_joy}): {features_joy['home_point_diff_rematches']}")

====================================================================================================
🔍 IVY LEAGUE TEST CASE 1: SIMON RUIZ vs NICK FINE
====================================================================================================

📜 Raw Historical Features (from Simon's perspective):
   wrestled_before: 1
   home_point_diff_rematches: 3.0
   total_matches: 1
   Simon Ruiz wins: 1
   Nick Fine wins: 0
   Avg point diff (Simon's perspective): 3.0

📊 Wrestler Data from Inference Pipeline:
   Simon Ruiz - Rank: 2, Team: Cornell, Win Rate: 100.0%
   Nick Fine - Rank: 22, Team: Columbia, Win Rate: 76.9%

📊 LOGREG Input (win_rate_diff): 0.2310 (Simon 100.0% - Nick 76.9%)

📌 Home wrestler: Nick Fine (Rank: 22, Team: Columbia)
📌 Away wrestler: Simon Ruiz (Rank: 2, Team: Cornell)

================================================================================
🔍 MATCHUP DETAILS: Simon Ruiz vs Nick Fine
================================================================================

📜 HISTORICAL SUMMARY:
   Previous matches: 1
   Simon Ruiz wins: 1
   Nick Fine wins: 0
   Avg point diff (Simon Ruiz's perspective): 3.0
   Last match: 1/31/2026 (Winner: Simon Ruiz)

🔍 HISTORICAL FEATURES FOR MODELS:
   wrestled_before: 1
   home_point_diff_rematches: -3.0
   home_pinned_away: 0

📊 KEY DIFFERENTIALS (home - away):
   win_rate_diff: -0.2310 (Nick Fine 76.9% - Simon Ruiz 100.0%)
   matches_wrestled_diff: -1
   bonus_rate_diff: 0.1860
   avg_point_diff_diff: -1.1500
   team_rank_diff: 10

📊 FULL FEATURE ARRAYS:

📊 DT/XGB1 features (33 total):
    1. wrestled_before                     =   1.0000
    2. home_point_diff_rematches           =  -3.0000
    3. home_pinned_away                    =   0.0000
    4. weight_class_133                    =   0.0000
    5. weight_class_141                    =   0.0000
    6. weight_class_149                    =   0.0000
    7. weight_class_157                    =   0.0000
    8. weight_class_165                    =   0.0000
    9. weight_class_174                    =   1.0000
   10. weight_class_184                    =   0.0000
   ...

📊 XGB2 features (34 total):
    1. wrestled_before                     =   1.0000
    2. home_point_diff_rematches           =  -3.0000
    3. home_pinned_away                    =   0.0000
    4. matches_wrestled_diff               =  -1.0000
    5. win_rate_diff                       =  -0.2310
    6. bonus_rate_diff                     =   0.1860
    7. pin_count_diff                      =   0.0000
    8. avg_point_diff_diff                 =  -1.1500
    9. avg_points_scored_diff              =   0.1500
   10. std_point_diff_diff                 =   1.8700
   ...

🔮 PREDICTIONS:
   LOGREG: Simon Ruiz wins with 62.1% confidence
   DT    : Simon Ruiz wins with 53.1% confidence
   XGB1  : Nick Fine wins with 53.9% confidence
   XGB2  : Nick Fine wins with 55.0% confidence

⚠️ Models disagree on winner

====================================================================================================
🔍 IVY LEAGUE TEST CASE 2: JAXON JOY vs JACK CROOK
====================================================================================================

📜 Raw Historical Features (from Jaxon's perspective):
   wrestled_before: 1
   home_point_diff_rematches: 14.0
   total_matches: 1
   Jaxon Joy wins: 1
   Jack Crook wins: 0
   Avg point diff (Jaxon's perspective): 14.0

📊 Wrestler Data from Inference Pipeline:
   Jaxon Joy - Rank: 3, Team: Cornell, Win Rate: 93.3%
   Jack Crook - Rank: 60, Team: Harvard, Win Rate: 66.7%

📊 LOGREG Input (win_rate_diff): 0.2660 (Jaxon 93.3% - Jack 66.7%)

📌 Home wrestler: Jaxon Joy (Rank: 3, Team: Cornell)
📌 Away wrestler: Jack Crook (Rank: 60, Team: Harvard)

================================================================================
🔍 MATCHUP DETAILS: Jaxon Joy vs Jack Crook
================================================================================

📜 HISTORICAL SUMMARY:
   Previous matches: 1
   Jaxon Joy wins: 1
   Jack Crook wins: 0
   Avg point diff (Jaxon Joy's perspective): 14.0
   Last match: 1/24/2026 (Winner: Jaxon Joy)

🔍 HISTORICAL FEATURES FOR MODELS:
   wrestled_before: 1
   home_point_diff_rematches: 14.0
   home_pinned_away: 0

📊 KEY DIFFERENTIALS (home - away):
   win_rate_diff: 0.2660 (Jaxon Joy 93.3% - Jack Crook 66.7%)
   matches_wrestled_diff: 3
   bonus_rate_diff: 0.4670
   avg_point_diff_diff: 6.7600
   team_rank_diff: -38

📊 FULL FEATURE ARRAYS:

📊 DT/XGB1 features (33 total):
    1. wrestled_before                     =   1.0000
    2. home_point_diff_rematches           =  14.0000
    3. home_pinned_away                    =   0.0000
    4. weight_class_133                    =   0.0000
    5. weight_class_141                    =   0.0000
    6. weight_class_149                    =   1.0000
    7. weight_class_157                    =   0.0000
    8. weight_class_165                    =   0.0000
    9. weight_class_174                    =   0.0000
   10. weight_class_184                    =   0.0000
   ...

📊 XGB2 features (34 total):
    1. wrestled_before                     =   1.0000
    2. home_point_diff_rematches           =  14.0000
    3. home_pinned_away                    =   0.0000
    4. matches_wrestled_diff               =   3.0000
    5. win_rate_diff                       =   0.2660
    6. bonus_rate_diff                     =   0.4670
    7. pin_count_diff                      =   1.0000
    8. avg_point_diff_diff                 =   6.7600
    9. avg_points_scored_diff              =   1.2400
   10. std_point_diff_diff                 =  -3.4300
   ...

🔮 PREDICTIONS:
   LOGREG: Jaxon Joy wins with 64.3% confidence
   DT    : Jaxon Joy wins with 74.6% confidence
   XGB1  : Jaxon Joy wins with 77.3% confidence
   XGB2  : Jaxon Joy wins with 90.8% confidence

✅ All models agree: Jaxon Joy wins!

====================================================================================================
🔍 VERIFYING HOME/AWAY RULES
====================================================================================================

Rule 1: Columbia always home
   Sulayman Bah (Columbia) vs anyone → Sulayman Bah should be home
   Sulayman Bah - Team: Columbia

Rule 2: Otherwise, lower rank is home
   Jaxon Joy (Rank 3) vs Jack Crook (Rank 60) → Jaxon Joy should be home
   Jaxon Joy rank: 3, Jack Crook rank: 60
   Actual home in test case: Jaxon Joy

Rule 3: Historical point diff adjusted based on home
   Jaxon Joy vs Jack Crook - Jaxon won by 14
   Raw historical (Jaxon's perspective): 14.0
   Adjusted for home (Jaxon Joy): 14.0

In [81]:

# ============================================
# COMBINE INTO MASTER LIST
# ============================================

all_wrestler_list = [
    wrestlers_125, wrestlers_133, wrestlers_141, wrestlers_149,
    wrestlers_157, wrestlers_165, wrestlers_174, wrestlers_184,
    wrestlers_197, wrestlers_285
]

weights = [125, 133, 141, 149, 157, 165, 174, 184, 197, 285]

# Dictionary to store all results
all_weight_results = {}

# ============================================
# PREDICTION LOOP FOR IVY LEAGUE
# ============================================

# Loop through each weight class
for weight_idx, (weight, wrestler_list) in enumerate(zip(weights, all_wrestler_list)):
    print("\n" + "="*100)
    print(f"🏋️  PROCESSING IVY LEAGUE {weight}lbs WEIGHT CLASS ({weight_idx+1}/10)")
    print("="*100)

    # Display wrestlers in this weight class
    print(f"\n📋 {weight}lbs Wrestlers:")
    wrestlers_df = inference_pipeline_db[inference_pipeline_db['wrestler_name'].isin(wrestler_list)].copy()

    # Check if all wrestlers were found
    found_wrestlers = wrestlers_df['wrestler_name'].tolist()
    missing = [w for w in wrestler_list if w not in found_wrestlers]

    if missing:
        print(f"⚠️ Warning: {len(missing)} wrestlers not found in database:")
        for w in missing:
            print(f"   - {w}")
        # Remove missing wrestlers from the list
        wrestler_list = [w for w in wrestler_list if w in found_wrestlers]

    if len(wrestlers_df) == 0 or len(wrestler_list) < 2:
        print(f"❌ Not enough wrestlers found for {weight}lbs! Skipping...")
        continue

    print(wrestlers_df[['wrestler_name', 'team_name', 'rank', 'win_rate']].to_string(index=False))

    # Generate all matchup predictions for this weight class
    total_matchups = len(list(combinations(wrestler_list, 2)))
    print(f"\n🔄 Generating predictions for {total_matchups} matchups...")

    weight_predictions = []
    matchup_count = 0

    for w1, w2 in combinations(wrestler_list, 2):
        matchup_count += 1
        if matchup_count % 5 == 0 or matchup_count == total_matchups:
            print(f"   Progress: {matchup_count}/{total_matchups} matchups")

        # Get historical data
        hist_features = get_wrestler_match_history(w1, w2, matches_reference)

        # Prepare features - using the Ivy League version with Columbia priority
        features, home_name, away_name, home_data, away_data = prepare_matchup_features(
            w1, w2, hist_features, inference_pipeline_db, weight_class=weight
        )

        # Make predictions
        results = predict_matchup(w1, w2, features, home_name, away_name)

        # Add weight class
        results['weight_class'] = weight
        weight_predictions.append(results)

    # Create dataframe for this weight class
    weight_df = pd.DataFrame(weight_predictions)

    # Add model agreement column
    weight_df['all_agree'] = (
        (weight_df['logreg_winner'] == weight_df['dt_winner']) &
        (weight_df['dt_winner'] == weight_df['xgb1_winner']) &
        (weight_df['xgb1_winner'] == weight_df['xgb2_winner'])
    )

    # Store results
    all_weight_results[weight] = weight_df

    # ============================================
    # DISPLAY ALL MATCHUPS WITH WINNER PROBABILITIES
    # ============================================
    print(f"\n📊 IVY LEAGUE {weight}lbs - ALL MATCHUP PREDICTIONS")
    print("="*100)

    display_cols = [
        'home_wrestler', 'away_wrestler',
        'logreg_winner', 'logreg_prob',
        'dt_winner', 'dt_prob',
        'xgb1_winner', 'xgb1_prob',
        'xgb2_winner', 'xgb2_prob',
        'all_agree'
    ]

    display_df = weight_df[display_cols].copy()
    display_df.columns = [
        'Home', 'Away',
        'LR_Winner', 'LR_Conf',
        'DT_Winner', 'DT_Conf',
        'X1_Winner', 'X1_Conf',
        'X2_Winner', 'X2_Conf',
        'Agree'
    ]

    # Format confidence as percentage
    for col in ['LR_Conf', 'DT_Conf', 'X1_Conf', 'X2_Conf']:
        display_df[col] = (display_df[col] * 100).round(1).astype(str) + '%'

    print(display_df.to_string(index=False))

    # ============================================
    # QUICK SUMMARY STATS
    # ============================================
    print(f"\n📊 IVY LEAGUE {weight}lbs - QUICK SUMMARY")
    print("-" * 60)

    # Agreement stats
    agreement_count = weight_df['all_agree'].sum()
    print(f"Total Matchups: {len(weight_df)}")
    print(f"All models agree: {agreement_count}/{len(weight_df)} ({agreement_count/len(weight_df)*100:.1f}%)")

    # Calculate average confidence
    weight_df['avg_confidence'] = (
        weight_df['logreg_prob'] +
        weight_df['dt_prob'] +
        weight_df['xgb1_prob'] +
        weight_df['xgb2_prob']
    ) / 4

    # Top 3 most confident predictions
    if len(weight_df) >= 3:
        top_confident = weight_df.nlargest(3, 'avg_confidence')[
            ['home_wrestler', 'away_wrestler', 'avg_confidence']
        ]
        print("\n🔝 Top 3 most confident predictions:")
        for _, row in top_confident.iterrows():
            print(f"   {row['home_wrestler']} vs {row['away_wrestler']}: {row['avg_confidence']*100:.1f}%")

    # Predicted champion by each model
    print("\n🏆 Predicted champions:")
    for model in ['logreg', 'dt', 'xgb1', 'xgb2']:
        if len(weight_df) > 0:
            champ_counts = weight_df[f'{model}_winner'].value_counts()
            if len(champ_counts) > 0:
                champ = champ_counts.index[0]
                champ_wins = champ_counts.values[0]
                champ_pct = (champ_wins / (len(wrestler_list) - 1)) * 100 if len(wrestler_list) > 1 else 0
                print(f"   {model.upper():6}: {champ} ({champ_wins}/{len(wrestler_list)-1} wins, {champ_pct:.1f}%)")

    # Check for unanimous champion
    champions = []
    for model in ['logreg', 'dt', 'xgb1', 'xgb2']:
        if len(weight_df) > 0:
            champ_counts = weight_df[f'{model}_winner'].value_counts()
            if len(champ_counts) > 0:
                champions.append(champ_counts.index[0])

    if len(champions) == 4 and all(c == champions[0] for c in champions):
        print(f"\n✅ UNANIMOUS CHAMPION: {champions[0]}")
    elif len(champions) > 0:
        print(f"\n⚠️ No unanimous champion")
        for model, champ in zip(['logreg', 'dt', 'xgb1', 'xgb2'], champions):
            print(f"   {model.upper():6}: {champ}")

    print("\n" + "="*60)

# ============================================
# OVERALL SUMMARY ACROSS ALL WEIGHT CLASSES
# ============================================
print("\n" + "="*100)
print("📊 IVY LEAGUE OVERALL SUMMARY - ALL WEIGHT CLASSES")
print("="*100)

summary_rows = []
for weight in weights:
    if weight in all_weight_results:
        weight_df = all_weight_results[weight]

        # Agreement stats
        agreement_count = weight_df['all_agree'].sum()
        agreement_pct = agreement_count / len(weight_df) * 100 if len(weight_df) > 0 else 0

        # Champions by model
        logreg_champ = weight_df['logreg_winner'].value_counts().index[0] if len(weight_df) > 0 else "N/A"
        dt_champ = weight_df['dt_winner'].value_counts().index[0] if len(weight_df) > 0 else "N/A"
        xgb1_champ = weight_df['xgb1_winner'].value_counts().index[0] if len(weight_df) > 0 else "N/A"
        xgb2_champ = weight_df['xgb2_winner'].value_counts().index[0] if len(weight_df) > 0 else "N/A"

        # Check unanimous
        unanimous = (logreg_champ == dt_champ == xgb1_champ == xgb2_champ) and logreg_champ != "N/A"

        summary_rows.append({
            'Weight': f"{weight}lbs",
            'Matchups': len(weight_df),
            'Agreement': f"{agreement_pct:.1f}%",
            'LogReg Champ': logreg_champ[:15] + "..." if len(str(logreg_champ)) > 15 else str(logreg_champ),
            'DT Champ': dt_champ[:15] + "..." if len(str(dt_champ)) > 15 else str(dt_champ),
            'XGB1 Champ': xgb1_champ[:15] + "..." if len(str(xgb1_champ)) > 15 else str(xgb1_champ),
            'XGB2 Champ': xgb2_champ[:15] + "..." if len(str(xgb2_champ)) > 15 else str(xgb2_champ),
            'Unanimous': '✅' if unanimous else '❌'
        })

summary_df = pd.DataFrame(summary_rows)
print("\n", summary_df.to_string(index=False))

# ============================================
# SAVE MASTER SUMMARY
# ============================================
summary_df.to_csv('ivy_league_all_weight_classes_summary.csv', index=False)
print("\n💾 Saved Ivy League master summary to ivy_league_all_weight_classes_summary.csv")

# Combine all predictions into one master file
if len(all_weight_results) > 0:
    all_predictions_master = pd.concat(all_weight_results.values(), ignore_index=True)
    all_predictions_master.to_csv('ivy_league_all_predictions_master.csv', index=False)
    print("💾 Saved all Ivy League predictions to ivy_league_all_predictions_master.csv")

print("\n" + "="*100)
print("✅ IVY LEAGUE ALL WEIGHT CLASS PREDICTIONS COMPLETE")
print("="*100)
print(f"Total weight classes processed: {len(all_weight_results)}")
print(f"Total matchups processed: {sum(len(df) for df in all_weight_results.values())}")

====================================================================================================
🏋️  PROCESSING IVY LEAGUE 125lbs WEIGHT CLASS (1/10)
====================================================================================================

📋 125lbs Wrestlers:
       wrestler_name    team_name  rank  win_rate
        Sulayman Bah     Columbia    23      69.2
    Logan Brzozowski      Harvard    45      66.7
      Chase Yasutake        Brown   230       9.1
Marc-Anthony McGowan    Princeton    13      80.0
   Greg Diakomihalis      Cornell    50      33.3
        Davis Motyka Pennsylvania    37      80.0

🔄 Generating predictions for 15 matchups...

📌 Home wrestler: Davis Motyka (Rank: 37, Team: Pennsylvania)
📌 Away wrestler: Greg Diakomihalis (Rank: 50, Team: Cornell)

📌 Home wrestler: Davis Motyka (Rank: 37, Team: Pennsylvania)
📌 Away wrestler: Logan Brzozowski (Rank: 45, Team: Harvard)

📌 Home wrestler: Sulayman Bah (Rank: 23, Team: Columbia)
📌 Away wrestler: Davis Motyka (Rank: 37, Team: Pennsylvania)

📌 Home wrestler: Davis Motyka (Rank: 37, Team: Pennsylvania)
📌 Away wrestler: Chase Yasutake (Rank: 230, Team: Brown)
   Progress: 5/15 matchups

📌 Home wrestler: Marc-Anthony McGowan (Rank: 13, Team: Princeton)
📌 Away wrestler: Davis Motyka (Rank: 37, Team: Pennsylvania)

📌 Home wrestler: Logan Brzozowski (Rank: 45, Team: Harvard)
📌 Away wrestler: Greg Diakomihalis (Rank: 50, Team: Cornell)

📌 Home wrestler: Sulayman Bah (Rank: 23, Team: Columbia)
📌 Away wrestler: Greg Diakomihalis (Rank: 50, Team: Cornell)

📌 Home wrestler: Greg Diakomihalis (Rank: 50, Team: Cornell)
📌 Away wrestler: Chase Yasutake (Rank: 230, Team: Brown)

📌 Home wrestler: Marc-Anthony McGowan (Rank: 13, Team: Princeton)
📌 Away wrestler: Greg Diakomihalis (Rank: 50, Team: Cornell)
   Progress: 10/15 matchups

📌 Home wrestler: Sulayman Bah (Rank: 23, Team: Columbia)
📌 Away wrestler: Logan Brzozowski (Rank: 45, Team: Harvard)

📌 Home wrestler: Logan Brzozowski (Rank: 45, Team: Harvard)
📌 Away wrestler: Chase Yasutake (Rank: 230, Team: Brown)

📌 Home wrestler: Marc-Anthony McGowan (Rank: 13, Team: Princeton)
📌 Away wrestler: Logan Brzozowski (Rank: 45, Team: Harvard)

📌 Home wrestler: Sulayman Bah (Rank: 23, Team: Columbia)
📌 Away wrestler: Chase Yasutake (Rank: 230, Team: Brown)

📌 Home wrestler: Sulayman Bah (Rank: 23, Team: Columbia)
📌 Away wrestler: Marc-Anthony McGowan (Rank: 13, Team: Princeton)
   Progress: 15/15 matchups

📌 Home wrestler: Marc-Anthony McGowan (Rank: 13, Team: Princeton)
📌 Away wrestler: Chase Yasutake (Rank: 230, Team: Brown)

📊 IVY LEAGUE 125lbs - ALL MATCHUP PREDICTIONS
====================================================================================================
                Home                 Away            LR_Winner LR_Conf            DT_Winner DT_Conf            X1_Winner X1_Conf            X2_Winner X2_Conf  Agree
        Davis Motyka    Greg Diakomihalis         Davis Motyka   73.6%         Davis Motyka   74.6%         Davis Motyka   61.8%    Greg Diakomihalis   68.5%  False
        Davis Motyka     Logan Brzozowski         Davis Motyka   57.4%         Davis Motyka   61.1%         Davis Motyka   58.4%         Davis Motyka   78.9%   True
        Sulayman Bah         Davis Motyka         Davis Motyka   55.6%         Sulayman Bah   61.1%         Sulayman Bah   74.7%         Sulayman Bah   82.5%  False
        Davis Motyka       Chase Yasutake         Davis Motyka   82.6%         Davis Motyka   89.0%         Davis Motyka   85.8%         Davis Motyka   95.3%   True
Marc-Anthony McGowan         Davis Motyka Marc-Anthony McGowan   50.2% Marc-Anthony McGowan   61.1% Marc-Anthony McGowan   76.5% Marc-Anthony McGowan   64.8%   True
    Logan Brzozowski    Greg Diakomihalis     Logan Brzozowski   67.6%     Logan Brzozowski   74.6%     Logan Brzozowski   68.8%    Greg Diakomihalis   78.3%  False
        Sulayman Bah    Greg Diakomihalis         Sulayman Bah   68.8%         Sulayman Bah   74.6%         Sulayman Bah   79.8%         Sulayman Bah   78.6%   True
   Greg Diakomihalis       Chase Yasutake    Greg Diakomihalis   63.1%    Greg Diakomihalis   89.0%    Greg Diakomihalis   80.0%    Greg Diakomihalis   93.2%   True
Marc-Anthony McGowan    Greg Diakomihalis Marc-Anthony McGowan   73.6% Marc-Anthony McGowan   74.6% Marc-Anthony McGowan   80.2% Marc-Anthony McGowan   64.7%   True
        Sulayman Bah     Logan Brzozowski         Sulayman Bah   51.6%         Sulayman Bah   61.1%         Sulayman Bah   72.4%         Sulayman Bah   89.7%   True
    Logan Brzozowski       Chase Yasutake     Logan Brzozowski   78.0%     Logan Brzozowski   89.0%     Logan Brzozowski   90.3%     Logan Brzozowski   93.8%   True
Marc-Anthony McGowan     Logan Brzozowski Marc-Anthony McGowan   57.4% Marc-Anthony McGowan   61.1% Marc-Anthony McGowan   61.0% Marc-Anthony McGowan   79.4%   True
        Sulayman Bah       Chase Yasutake         Sulayman Bah   78.9%         Sulayman Bah   89.0%         Sulayman Bah   89.0%         Sulayman Bah   95.6%   True
        Sulayman Bah Marc-Anthony McGowan Marc-Anthony McGowan   55.6% Marc-Anthony McGowan   53.1% Marc-Anthony McGowan   55.4% Marc-Anthony McGowan   58.5%   True
Marc-Anthony McGowan       Chase Yasutake Marc-Anthony McGowan   82.6% Marc-Anthony McGowan   89.0% Marc-Anthony McGowan   87.8% Marc-Anthony McGowan   95.9%   True

📊 IVY LEAGUE 125lbs - QUICK SUMMARY
------------------------------------------------------------
Total Matchups: 15
All models agree: 12/15 (80.0%)

🔝 Top 3 most confident predictions:
   Marc-Anthony McGowan vs Chase Yasutake: 88.8%
   Davis Motyka vs Chase Yasutake: 88.2%
   Sulayman Bah vs Chase Yasutake: 88.1%

🏆 Predicted champions:
   LOGREG: Marc-Anthony McGowan (5/5 wins, 100.0%)
   DT    : Marc-Anthony McGowan (5/5 wins, 100.0%)
   XGB1  : Marc-Anthony McGowan (5/5 wins, 100.0%)
   XGB2  : Marc-Anthony McGowan (5/5 wins, 100.0%)

✅ UNANIMOUS CHAMPION: Marc-Anthony McGowan

============================================================

====================================================================================================
🏋️  PROCESSING IVY LEAGUE 133lbs WEIGHT CLASS (2/10)
====================================================================================================

📋 133lbs Wrestlers:
  wrestler_name    team_name  rank  win_rate
Douglas Shipers        Brown   254       0.0
    Evin Gursoy     Columbia    68      71.4
  Coleman Nogle      Harvard    72      50.0
  Tyler Ferrera      Cornell    18      72.7
 Evan Mougalian Pennsylvania    16      80.0
   Ethan Rivera    Princeton    45      50.0

🔄 Generating predictions for 15 matchups...

📌 Home wrestler: Evan Mougalian (Rank: 16, Team: Pennsylvania)
📌 Away wrestler: Ethan Rivera (Rank: 45, Team: Princeton)

📌 Home wrestler: Evan Mougalian (Rank: 16, Team: Pennsylvania)
📌 Away wrestler: Coleman Nogle (Rank: 72, Team: Harvard)

📌 Home wrestler: Evin Gursoy (Rank: 68, Team: Columbia)
📌 Away wrestler: Evan Mougalian (Rank: 16, Team: Pennsylvania)

📌 Home wrestler: Evan Mougalian (Rank: 16, Team: Pennsylvania)
📌 Away wrestler: Douglas Shipers (Rank: 254, Team: Brown)
   Progress: 5/15 matchups

📌 Home wrestler: Evan Mougalian (Rank: 16, Team: Pennsylvania)
📌 Away wrestler: Tyler Ferrera (Rank: 18, Team: Cornell)

📌 Home wrestler: Ethan Rivera (Rank: 45, Team: Princeton)
📌 Away wrestler: Coleman Nogle (Rank: 72, Team: Harvard)

📌 Home wrestler: Evin Gursoy (Rank: 68, Team: Columbia)
📌 Away wrestler: Ethan Rivera (Rank: 45, Team: Princeton)

📌 Home wrestler: Ethan Rivera (Rank: 45, Team: Princeton)
📌 Away wrestler: Douglas Shipers (Rank: 254, Team: Brown)

📌 Home wrestler: Tyler Ferrera (Rank: 18, Team: Cornell)
📌 Away wrestler: Ethan Rivera (Rank: 45, Team: Princeton)
   Progress: 10/15 matchups

📌 Home wrestler: Evin Gursoy (Rank: 68, Team: Columbia)
📌 Away wrestler: Coleman Nogle (Rank: 72, Team: Harvard)

📌 Home wrestler: Coleman Nogle (Rank: 72, Team: Harvard)
📌 Away wrestler: Douglas Shipers (Rank: 254, Team: Brown)

📌 Home wrestler: Tyler Ferrera (Rank: 18, Team: Cornell)
📌 Away wrestler: Coleman Nogle (Rank: 72, Team: Harvard)

📌 Home wrestler: Evin Gursoy (Rank: 68, Team: Columbia)
📌 Away wrestler: Douglas Shipers (Rank: 254, Team: Brown)

📌 Home wrestler: Evin Gursoy (Rank: 68, Team: Columbia)
📌 Away wrestler: Tyler Ferrera (Rank: 18, Team: Cornell)
   Progress: 15/15 matchups

📌 Home wrestler: Tyler Ferrera (Rank: 18, Team: Cornell)
📌 Away wrestler: Douglas Shipers (Rank: 254, Team: Brown)

📊 IVY LEAGUE 133lbs - ALL MATCHUP PREDICTIONS
====================================================================================================
          Home            Away      LR_Winner LR_Conf      DT_Winner DT_Conf      X1_Winner X1_Conf      X2_Winner X2_Conf  Agree
Evan Mougalian    Ethan Rivera Evan Mougalian   66.0% Evan Mougalian   74.6% Evan Mougalian   83.0% Evan Mougalian   79.8%   True
Evan Mougalian   Coleman Nogle Evan Mougalian   66.0% Evan Mougalian   74.6% Evan Mougalian   81.4% Evan Mougalian   89.2%   True
   Evin Gursoy  Evan Mougalian Evan Mougalian   54.4% Evan Mougalian   53.1%    Evin Gursoy   53.5%    Evin Gursoy   56.0%  False
Evan Mougalian Douglas Shipers Evan Mougalian   85.2% Evan Mougalian   89.0% Evan Mougalian   88.6% Evan Mougalian   95.2%   True
Evan Mougalian   Tyler Ferrera Evan Mougalian   54.2% Evan Mougalian   61.1% Evan Mougalian   67.0% Evan Mougalian   60.5%   True
  Ethan Rivera   Coleman Nogle   Ethan Rivera   50.2%   Ethan Rivera   61.1%   Ethan Rivera   52.0%   Ethan Rivera   86.2%   True
   Evin Gursoy    Ethan Rivera    Evin Gursoy   61.7%    Evin Gursoy   74.6%    Evin Gursoy   74.4%    Evin Gursoy   74.1%   True
  Ethan Rivera Douglas Shipers   Ethan Rivera   75.0%   Ethan Rivera   89.0%   Ethan Rivera   85.3%   Ethan Rivera   94.3%   True
 Tyler Ferrera    Ethan Rivera  Tyler Ferrera   62.4%  Tyler Ferrera   74.6%  Tyler Ferrera   70.5%  Tyler Ferrera   77.8%   True
   Evin Gursoy   Coleman Nogle    Evin Gursoy   61.7%    Evin Gursoy   74.6%    Evin Gursoy   76.0%    Evin Gursoy   87.4%   True
 Coleman Nogle Douglas Shipers  Coleman Nogle   75.0%  Coleman Nogle   74.6%  Coleman Nogle   85.6%  Coleman Nogle   92.0%   True
 Tyler Ferrera   Coleman Nogle  Tyler Ferrera   62.4%  Tyler Ferrera   74.6%  Tyler Ferrera   64.2%  Tyler Ferrera   82.8%   True
   Evin Gursoy Douglas Shipers    Evin Gursoy   82.7%    Evin Gursoy   89.0%    Evin Gursoy   91.4%    Evin Gursoy   96.6%   True
   Evin Gursoy   Tyler Ferrera  Tyler Ferrera   50.4%    Evin Gursoy   61.1%    Evin Gursoy   73.3%    Evin Gursoy   59.6%  False
 Tyler Ferrera Douglas Shipers  Tyler Ferrera   83.1%  Tyler Ferrera   89.0%  Tyler Ferrera   87.8%  Tyler Ferrera   95.3%   True

📊 IVY LEAGUE 133lbs - QUICK SUMMARY
------------------------------------------------------------
Total Matchups: 15
All models agree: 13/15 (86.7%)

🔝 Top 3 most confident predictions:
   Evin Gursoy vs Douglas Shipers: 89.9%
   Evan Mougalian vs Douglas Shipers: 89.5%
   Tyler Ferrera vs Douglas Shipers: 88.8%

🏆 Predicted champions:
   LOGREG: Evan Mougalian (5/5 wins, 100.0%)
   DT    : Evan Mougalian (5/5 wins, 100.0%)
   XGB1  : Evin Gursoy (5/5 wins, 100.0%)
   XGB2  : Evin Gursoy (5/5 wins, 100.0%)

⚠️ No unanimous champion
   LOGREG: Evan Mougalian
   DT    : Evan Mougalian
   XGB1  : Evin Gursoy
   XGB2  : Evin Gursoy

============================================================

====================================================================================================
🏋️  PROCESSING IVY LEAGUE 141lbs WEIGHT CLASS (3/10)
====================================================================================================

📋 141lbs Wrestlers:
  wrestler_name    team_name  rank  win_rate
 Vince Cornella      Cornell     6      92.3
Matthew Martino    Princeton    28      38.5
 Lorenzo Frezza     Columbia    46      61.5
  Khimari Manns        Brown    67      54.5
   Dante Frinzi      Harvard   133      22.2
    CJ Composto Pennsylvania    10      75.0

🔄 Generating predictions for 15 matchups...

📌 Home wrestler: Vince Cornella (Rank: 6, Team: Cornell)
📌 Away wrestler: Matthew Martino (Rank: 28, Team: Princeton)

📌 Home wrestler: Lorenzo Frezza (Rank: 46, Team: Columbia)
📌 Away wrestler: Vince Cornella (Rank: 6, Team: Cornell)

📌 Home wrestler: Vince Cornella (Rank: 6, Team: Cornell)
📌 Away wrestler: Khimari Manns (Rank: 67, Team: Brown)

📌 Home wrestler: Vince Cornella (Rank: 6, Team: Cornell)
📌 Away wrestler: Dante Frinzi (Rank: 133, Team: Harvard)
   Progress: 5/15 matchups

📌 Home wrestler: Vince Cornella (Rank: 6, Team: Cornell)
📌 Away wrestler: CJ Composto (Rank: 10, Team: Pennsylvania)

📌 Home wrestler: Lorenzo Frezza (Rank: 46, Team: Columbia)
📌 Away wrestler: Matthew Martino (Rank: 28, Team: Princeton)

📌 Home wrestler: Matthew Martino (Rank: 28, Team: Princeton)
📌 Away wrestler: Khimari Manns (Rank: 67, Team: Brown)

📌 Home wrestler: Matthew Martino (Rank: 28, Team: Princeton)
📌 Away wrestler: Dante Frinzi (Rank: 133, Team: Harvard)

📌 Home wrestler: CJ Composto (Rank: 10, Team: Pennsylvania)
📌 Away wrestler: Matthew Martino (Rank: 28, Team: Princeton)
   Progress: 10/15 matchups

📌 Home wrestler: Lorenzo Frezza (Rank: 46, Team: Columbia)
📌 Away wrestler: Khimari Manns (Rank: 67, Team: Brown)

📌 Home wrestler: Lorenzo Frezza (Rank: 46, Team: Columbia)
📌 Away wrestler: Dante Frinzi (Rank: 133, Team: Harvard)

📌 Home wrestler: Lorenzo Frezza (Rank: 46, Team: Columbia)
📌 Away wrestler: CJ Composto (Rank: 10, Team: Pennsylvania)

📌 Home wrestler: Khimari Manns (Rank: 67, Team: Brown)
📌 Away wrestler: Dante Frinzi (Rank: 133, Team: Harvard)

📌 Home wrestler: CJ Composto (Rank: 10, Team: Pennsylvania)
📌 Away wrestler: Khimari Manns (Rank: 67, Team: Brown)
   Progress: 15/15 matchups

📌 Home wrestler: CJ Composto (Rank: 10, Team: Pennsylvania)
📌 Away wrestler: Dante Frinzi (Rank: 133, Team: Harvard)

📊 IVY LEAGUE 141lbs - ALL MATCHUP PREDICTIONS
====================================================================================================
           Home            Away       LR_Winner LR_Conf       DT_Winner DT_Conf       X1_Winner X1_Conf       X2_Winner X2_Conf  Agree
 Vince Cornella Matthew Martino  Vince Cornella   76.5%  Vince Cornella   89.0%  Vince Cornella   88.0%  Vince Cornella   92.3%   True
 Lorenzo Frezza  Vince Cornella  Vince Cornella   65.9%  Vince Cornella   70.0%  Vince Cornella   57.1%  Vince Cornella   80.1%   True
 Vince Cornella   Khimari Manns  Vince Cornella   69.7%  Vince Cornella   74.6%  Vince Cornella   73.8%  Vince Cornella   91.7%   True
 Vince Cornella    Dante Frinzi  Vince Cornella   82.3%  Vince Cornella   89.0%  Vince Cornella   89.7%  Vince Cornella   94.8%   True
 Vince Cornella     CJ Composto  Vince Cornella   59.6%     CJ Composto   53.1%  Vince Cornella   58.6%  Vince Cornella   53.4%  False
 Lorenzo Frezza Matthew Martino  Lorenzo Frezza   62.5%  Lorenzo Frezza   74.6%  Lorenzo Frezza   77.7%  Lorenzo Frezza   80.6%   True
Matthew Martino   Khimari Manns   Khimari Manns   58.4%   Khimari Manns   53.1%   Khimari Manns   66.1% Matthew Martino   81.5%  False
Matthew Martino    Dante Frinzi Matthew Martino   59.0% Matthew Martino   61.1% Matthew Martino   59.7% Matthew Martino   61.7%   True
    CJ Composto Matthew Martino     CJ Composto   69.1%     CJ Composto   89.0%     CJ Composto   84.2%     CJ Composto   87.3%   True
 Lorenzo Frezza   Khimari Manns  Lorenzo Frezza   54.1%  Lorenzo Frezza   61.1%  Lorenzo Frezza   67.1%  Lorenzo Frezza   89.2%   True
 Lorenzo Frezza    Dante Frinzi  Lorenzo Frezza   70.4%  Lorenzo Frezza   74.6%  Lorenzo Frezza   83.5%  Lorenzo Frezza   91.3%   True
 Lorenzo Frezza     CJ Composto     CJ Composto   57.0%     CJ Composto   53.1%     CJ Composto   53.6%     CJ Composto   68.9%   True
  Khimari Manns    Dante Frinzi   Khimari Manns   67.1%   Khimari Manns   74.6%   Khimari Manns   73.9%   Khimari Manns   50.6%   True
    CJ Composto   Khimari Manns     CJ Composto   61.2%     CJ Composto   74.6%     CJ Composto   75.1%     CJ Composto   92.2%   True
    CJ Composto    Dante Frinzi     CJ Composto   76.1%     CJ Composto   89.0%     CJ Composto   85.9%     CJ Composto   90.6%   True

📊 IVY LEAGUE 141lbs - QUICK SUMMARY
------------------------------------------------------------
Total Matchups: 15
All models agree: 13/15 (86.7%)

🔝 Top 3 most confident predictions:
   Vince Cornella vs Dante Frinzi: 88.9%
   Vince Cornella vs Matthew Martino: 86.5%
   CJ Composto vs Dante Frinzi: 85.4%

🏆 Predicted champions:
   LOGREG: Vince Cornella (5/5 wins, 100.0%)
   DT    : CJ Composto (5/5 wins, 100.0%)
   XGB1  : Vince Cornella (5/5 wins, 100.0%)
   XGB2  : Vince Cornella (5/5 wins, 100.0%)

⚠️ No unanimous champion
   LOGREG: Vince Cornella
   DT    : CJ Composto
   XGB1  : Vince Cornella
   XGB2  : Vince Cornella

============================================================

====================================================================================================
🏋️  PROCESSING IVY LEAGUE 149lbs WEIGHT CLASS (4/10)
====================================================================================================

📋 149lbs Wrestlers:
   wrestler_name    team_name  rank  win_rate
       Jaxon Joy      Cornell     3      93.3
 Austin McBurney        Brown    81      57.1
    Eligh Rivera    Princeton    22      57.1
 Richard Fedalen     Columbia    69      41.7
      Jack Crook      Harvard    60      66.7
Cross Wasilewski Pennsylvania     8      90.0

🔄 Generating predictions for 15 matchups...

📌 Home wrestler: Richard Fedalen (Rank: 69, Team: Columbia)
📌 Away wrestler: Jaxon Joy (Rank: 3, Team: Cornell)

📌 Home wrestler: Jaxon Joy (Rank: 3, Team: Cornell)
📌 Away wrestler: Jack Crook (Rank: 60, Team: Harvard)

📌 Home wrestler: Jaxon Joy (Rank: 3, Team: Cornell)
📌 Away wrestler: Eligh Rivera (Rank: 22, Team: Princeton)

📌 Home wrestler: Jaxon Joy (Rank: 3, Team: Cornell)
📌 Away wrestler: Austin McBurney (Rank: 81, Team: Brown)
   Progress: 5/15 matchups

📌 Home wrestler: Jaxon Joy (Rank: 3, Team: Cornell)
📌 Away wrestler: Cross Wasilewski (Rank: 8, Team: Pennsylvania)

📌 Home wrestler: Richard Fedalen (Rank: 69, Team: Columbia)
📌 Away wrestler: Jack Crook (Rank: 60, Team: Harvard)

📌 Home wrestler: Richard Fedalen (Rank: 69, Team: Columbia)
📌 Away wrestler: Eligh Rivera (Rank: 22, Team: Princeton)

📌 Home wrestler: Richard Fedalen (Rank: 69, Team: Columbia)
📌 Away wrestler: Austin McBurney (Rank: 81, Team: Brown)

📌 Home wrestler: Richard Fedalen (Rank: 69, Team: Columbia)
📌 Away wrestler: Cross Wasilewski (Rank: 8, Team: Pennsylvania)
   Progress: 10/15 matchups

📌 Home wrestler: Eligh Rivera (Rank: 22, Team: Princeton)
📌 Away wrestler: Jack Crook (Rank: 60, Team: Harvard)

📌 Home wrestler: Jack Crook (Rank: 60, Team: Harvard)
📌 Away wrestler: Austin McBurney (Rank: 81, Team: Brown)

📌 Home wrestler: Cross Wasilewski (Rank: 8, Team: Pennsylvania)
📌 Away wrestler: Jack Crook (Rank: 60, Team: Harvard)

📌 Home wrestler: Eligh Rivera (Rank: 22, Team: Princeton)
📌 Away wrestler: Austin McBurney (Rank: 81, Team: Brown)

📌 Home wrestler: Cross Wasilewski (Rank: 8, Team: Pennsylvania)
📌 Away wrestler: Eligh Rivera (Rank: 22, Team: Princeton)
   Progress: 15/15 matchups

📌 Home wrestler: Cross Wasilewski (Rank: 8, Team: Pennsylvania)
📌 Away wrestler: Austin McBurney (Rank: 81, Team: Brown)

📊 IVY LEAGUE 149lbs - ALL MATCHUP PREDICTIONS
====================================================================================================
            Home             Away        LR_Winner LR_Conf        DT_Winner DT_Conf        X1_Winner X1_Conf        X2_Winner X2_Conf  Agree
 Richard Fedalen        Jaxon Joy        Jaxon Joy   75.3%        Jaxon Joy   85.6%        Jaxon Joy   81.2%        Jaxon Joy   88.0%   True
       Jaxon Joy       Jack Crook        Jaxon Joy   64.3%        Jaxon Joy   74.6%        Jaxon Joy   77.3%        Jaxon Joy   90.8%   True

# ----- now we will switch to the big ten

In [82]:
# ============================================
# BIG TEN WRESTLER LISTS
# ============================================

print("\n" + "="*100)
print("🏆 BIG TEN CONFERENCE WRESTLERS BY WEIGHT CLASS")
print("="*100)

# 125 lbs
wrestlers_125 = [
    "Luke Lilledahl", "Spencer Moore", "Nic Bouzakis", "Jacob Moran", "Jore Volk",
    "Ayden Smith", "Nicolar Rivera", "Dean Peterson", "Diego Sotelo", "Dedrick Navarro",
    "Kael Lauridsen", "Nick Corday", "Ashton Jackson", "Abram Cline"
]
print("\n125 BIG TEN WRESTLERS")
filter_weights(wrestlers_125)
print()

# 133 lbs
wrestlers_133 = [
    "Marcus Blaze", "Lucas Byrd", "Ben Davino", "Zan Fugitt", "Drake Ayala",
    "Jacob Van Dee", "Sean Spidle", "Braxton Brown", "Dylan Shawver", "Blake Boarman",
    "Caleb Weiand", "Blaine Frazier", "Gauge Botero", "Jager Eisch"
]
print("133 BIG TEN WRESTLERS")
filter_weights(wrestlers_133)
print()

# 141 lbs
wrestlers_141 = [
    "Jesse Mendez", "Brock Hardy", "Vance Vombaur", "Nasir Bailey", "Dylan Ragusin",
    "Greyson Clark", "Braeden Davis", "Billy Dekraker", "Henry Porter", "Joey Olivieri",
    "Dario Lemus", "Danny Pucino", "Carson Exferd", "Jaden Crumpler"
]
print("141 BIG TEN WRESTLERS")
filter_weights(wrestlers_141)
print()

# 149 lbs
wrestlers_149 = [
    "Shayne Van Ness", "Ethan Stiles", "Joseph Zargo", "Lachlan McNeil", "Carter Young",
    "Chance Lamer", "Andrew Clark", "Ryder Block", "Michael Gioffre", "Drew Roberts",
    "Joey Buttler", "Gavin Brown", "Clayton Jones", "August Hibler"
]
print("149 BIG TEN WRESTLERS")
filter_weights(wrestlers_149)
print()

# 157 lbs
wrestlers_157 = [
    "Antrell Taylor", "PJ Duke", "Kannon Webster", "Anthony White", "Cam Catrabone",
    "Charlie Millard", "Brandon Cannon", "Luke Mechler", "Stoney Buell", "Victor Voinovich",
    "Bryce Lowery", "Darius Marines", "Mekhi Neal", "Ty Wilson"
]
print("157 BIG TEN WRESTLERS")
filter_weights(wrestlers_157)
print()

# 165 lbs
wrestlers_165 = [
    "Mitchell Mesenbrink", "Michael Caliendo", "Joey Blaze", "Andrew Sparks", "LJ Araujo",
    "Braeden Scoles", "Andrew Barbosa", "Paddy Gallagher", "Tyler Lillard", "Cody Goebel",
    "Jacob Bostelman", "Justin Gates", "AJ Rodriguez", "Jack Conley"
]
print("165 BIG TEN WRESTLERS")
filter_weights(wrestlers_165)
print()

# 174 lbs
wrestlers_174 = [
    "Christopher Minto", "Levi Haines", "Patrick Kennedy", "Beau Mantanona", "Carson Kharchla",
    "Derek Gilcher", "Ethan Riddle", "Brody Baumann", "Colin Kelly", "Lenny Pinto",
    "Eddie Enright", "Lucas Condon", "Connor O'Neill", "Seth Digby"
]
print("174 BIG TEN WRESTLERS")
filter_weights(wrestlers_174)
print()

# 184 lbs
wrestlers_184 = [
    "Rocco Welsh", "Max McEnelly", "Silas Allred", "Brock Mantanona", "Chris Moore",
    "Dylan Fishback", "Shane Cartagena-Walsh", "Angelo Ferrari", "Sam Goin", "James Rowley",
    "Jesse Perez", "Sepanta Ahanj-Elias", "Ryan Boucher", "Cale Anderson"
]
print("184 BIG TEN WRESTLERS")
filter_weights(wrestlers_184)
print()

# 197 lbs
wrestlers_197 = [
    "Josh Barr", "Camden McDanel", "Remy Cotton", "Branson John", "Luke Geog",
    "Wyatt Ingham", "Kael Wisler", "Gabe Sollars", "Ben Vanadia", "Hayden Walters",
    "Gavin Nelson", "Dylan Connell", "Gabe Arnold", "Alex Smith"
]
print("197 BIG TEN WRESTLERS")
filter_weights(wrestlers_197)
print()

# 285 lbs
wrestlers_285 = [
    "Taye Ghadiali", "AJ Ferrari", "Nick Feldman", "Cole Mirasola", "Braxton Amos",
    "Luke Luffman", "Koy Hopke", "Hunter Catka", "Josh Terrill", "Ben Kueter",
    "Hayden Filipovich", "Joey Schneck", "Gabe Christenson", "Caleb Marzolino"
]
print("285 BIG TEN WRESTLERS")
filter_weights(wrestlers_285)
print()

# ============================================
# COMBINE INTO MASTER LIST FOR PREDICTIONS
# ============================================

all_wrestler_list = [
    wrestlers_125, wrestlers_133, wrestlers_141, wrestlers_149,
    wrestlers_157, wrestlers_165, wrestlers_174, wrestlers_184,
    wrestlers_197, wrestlers_285
]

weights = [125, 133, 141, 149, 157, 165, 174, 184, 197, 285]

print("\n" + "="*100)
print(f"✅ BIG TEN CONFERENCE LOADED: {sum(len(lst) for lst in all_wrestler_list)} total wrestlers")
print("="*100)

====================================================================================================
🏆 BIG TEN CONFERENCE WRESTLERS BY WEIGHT CLASS
====================================================================================================

125 BIG TEN WRESTLERS
Overall Stats

,wrestler_name,team_name,rank,team_rank,weight_classes,total_matches,total_wins,total_losses,win_rate,bonus_wins,bonus_rate,tf_wins,md_wins,fall_wins,dec_wins,avg_opponent_rank,avg_points_scored,avg_point_diff,std_point_diff,Class
29,Ayden Smith,Rutgers,35,8,[125],18,10,8,55.6,1,5.6,0,0,1,9,50.06,4.29,0.24,3.78,RSFR
38,Nicolar Rivera,Wisconsin,15,22,[125],17,13,4,76.5,5,29.4,2,3,0,8,65.88,10.29,5.29,5.68,JR
107,Jore Volk,Minnesota,18,8,[125],16,12,4,75.0,3,18.8,1,2,0,9,45.31,6.31,3.12,5.33,RSJR
161,Spencer Moore,Illinois,16,12,[125],15,9,6,60.0,3,20.0,0,2,1,6,48.80,5.43,2.21,5.41,SR
216,Jacob Moran,Indiana,12,33,[125],14,11,3,78.6,8,57.1,6,2,0,3,62.36,13.46,7.92,8.07,SR
223,Diego Sotelo,Michigan,39,7,[125],14,7,7,50.0,3,21.4,1,2,0,4,44.00,7.17,1.83,8.28,SR
240,Dean Peterson,Iowa,8,5,[125],14,10,4,71.4,2,14.3,1,1,0,8,36.57,6.62,3.08,5.69,SR
241,Luke Lilledahl,Penn State,1,1,[125],14,14,0,100.0,9,64.3,6,2,1,5,46.21,13.92,9.92,5.69,SO
306,Nick Corday,Michigan State,82,60,[125],13,6,7,46.2,1,7.7,0,1,0,5,62.38,4.25,-1.08,7.33,JR
460,Nic Bouzakis,Ohio State,2,2,[125],11,10,1,90.9,7,63.6,3,2,2,3,37.73,11.89,8.56,6.37,JR
541,Abram Cline,Maryland,125,59,"[125, 133]",10,1,9,10.0,0,0.0,0,0,0,1,44.80,2.70,-8.20,6.88,RSFR
543,Kael Lauridsen,Nebraska,47,6,"[125, 133]",10,3,7,30.0,0,0.0,0,0,0,3,29.20,4.56,-3.67,7.38,RSFR
548,Dedrick Navarro,Northwestern,38,41,[125],10,6,4,60.0,0,0.0,0,0,0,6,64.40,4.70,-2.10,7.49,SO
588,Ashton Jackson,Purdue,96,37,[125],9,2,7,22.2,2,22.2,0,2,0,0,57.11,4.11,-3.11,7.51,SO

133 BIG TEN WRESTLERS
Overall Stats

,wrestler_name,team_name,rank,team_rank,weight_classes,total_matches,total_wins,total_losses,win_rate,bonus_wins,bonus_rate,tf_wins,md_wins,fall_wins,dec_wins,avg_opponent_rank,avg_points_scored,avg_point_diff,std_point_diff,Class
11,Ben Davino,Ohio State,4,2,[133],19,18,1,94.7,12,63.2,9,2,1,6,63.00,13.17,9.89,5.73,RSFR
43,Zan Fugitt,Wisconsin,12,22,[133],17,13,4,76.5,8,47.1,2,4,2,5,65.76,8.60,4.73,7.44,SO
48,Dylan Shawver,Rutgers,35,8,[133],17,11,6,64.7,5,29.4,2,2,1,6,73.53,7.31,3.12,6.78,SR
56,Lucas Byrd,Illinois,1,12,[133],17,17,0,100.0,5,29.4,4,0,1,12,65.41,9.81,7.06,5.03,SR
79,Blake Boarman,Purdue,43,37,[133],16,8,8,50.0,2,12.5,1,0,1,6,71.44,6.71,-0.93,8.29,SR
85,Drake Ayala,Iowa,10,5,[133],16,9,7,56.2,7,43.8,5,1,1,2,29.25,10.40,3.73,9.90,SR
126,Marcus Blaze,Penn State,3,1,[133],15,15,0,100.0,12,80.0,4,5,3,3,46.73,12.42,9.67,5.16,FR
132,Jacob Van Dee,Nebraska,13,6,[133],15,12,3,80.0,5,33.3,2,2,1,7,63.13,7.50,4.43,6.68,JR
146,Gauge Botero,Michigan,98,7,[133],15,2,13,13.3,1,6.7,1,0,0,1,38.73,4.67,-4.93,8.16,FR
386,Braxton Brown,Maryland,23,59,[133],12,8,4,66.7,2,16.7,1,0,1,6,54.50,5.09,0.91,7.31,SR
425,Caleb Weiand,Michigan State,51,60,"[125, 133]",11,4,7,36.4,0,0.0,0,0,0,4,61.09,3.36,-3.64,5.54,SO
776,Sean Spidle,Northwestern,30,41,[133],7,5,2,71.4,1,14.3,0,1,0,4,46.14,4.33,1.17,6.40,SR
980,Jager Eisch,Minnesota,125,8,[149],4,0,4,0.0,0,0.0,0,0,0,0,23.50,4.25,-7.50,3.87,SR
983,Blaine Frazier,Indiana,93,33,[133],4,1,3,25.0,0,0.0,0,0,0,1,35.00,4.50,-5.00,7.16,JR

141 BIG TEN WRESTLERS
Overall Stats

,wrestler_name,team_name,rank,team_rank,weight_classes,total_matches,total_wins,total_losses,win_rate,bonus_wins,bonus_rate,tf_wins,md_wins,fall_wins,dec_wins,avg_opponent_rank,avg_points_scored,avg_point_diff,std_point_diff,Class
4,Jesse Mendez,Ohio State,1,2,[141],19,19,0,100.0,17,89.5,9,3,5,2,57.37,16.64,12.36,4.25,SR
21,Brock Hardy,Nebraska,3,6,[141],18,14,4,77.8,10,55.6,6,0,4,4,35.39,10.54,6.00,9.93,SR
168,Vance Vombaur,Minnesota,9,8,[141],15,11,4,73.3,6,40.0,3,3,0,5,62.47,9.13,4.00,8.72,JR
244,Carson Exferd,Wisconsin,155,22,[141],14,2,12,14.3,0,0.0,0,0,0,2,56.14,3.38,-5.23,5.59,RSFR
308,Henry Porter,Indiana,47,33,[141],13,7,6,53.8,5,38.5,1,4,0,2,69.38,7.92,-0.08,9.94,JR
373,Nasir Bailey,Iowa,13,5,[141],12,7,5,58.3,2,16.7,1,1,0,5,45.25,4.42,-0.08,8.97,JR
387,Dario Lemus,Maryland,55,59,[141],12,6,6,50.0,2,16.7,1,0,1,4,82.75,8.40,-0.70,9.60,SO
502,Greyson Clark,Purdue,41,37,[141],10,9,1,90.0,6,60.0,3,2,1,3,130.50,11.22,9.00,5.66,JR
516,Billy Dekraker,Northwestern,54,41,[141],10,5,5,50.0,1,10.0,0,0,1,4,68.60,4.00,-3.67,6.80,FR
649,Dylan Ragusin,Michigan,33,7,[141],8,6,2,75.0,3,37.5,1,2,0,3,73.12,8.25,3.00,9.07,SR
674,Braeden Davis,Penn State,11,1,[141],8,5,3,62.5,4,50.0,0,4,0,1,33.50,11.57,4.86,10.29,JR
727,Joey Olivieri,Rutgers,7,8,[141],7,7,0,100.0,5,71.4,1,0,4,2,106.14,10.00,6.00,7.81,SR
801,Danny Pucino,Illinois,25,12,[141],6,4,2,66.7,1,16.7,0,0,1,3,42.50,5.20,0.80,5.07,SR
819,Jaden Crumpler,Michigan State,116,60,[141],6,1,5,16.7,0,0.0,0,0,0,1,57.67,4.40,-7.60,6.47,SO

149 BIG TEN WRESTLERS
Overall Stats

,wrestler_name,team_name,rank,team_rank,weight_classes,total_matches,total_wins,total_losses,win_rate,bonus_wins,bonus_rate,tf_wins,md_wins,fall_wins,dec_wins,avg_opponent_rank,avg_points_scored,avg_point_diff,std_point_diff,Class
41,Joseph Zargo,Wisconsin,26,22,[149],17,14,3,82.4,8,47.1,6,1,1,6,91.88,12.12,7.00,7.46,RSSR
80,Gavin Brown,Purdue,58,37,[149],16,9,7,56.2,2,12.5,1,1,0,7,87.31,6.31,1.56,6.14,JR
97,Andrew Clark,Rutgers,28,8,[149],16,11,5,68.8,3,18.8,1,1,1,8,78.94,5.27,1.27,6.84,SR
112,Ryder Block,Iowa,20,5,[149],16,10,6,62.5,6,37.5,3,1,2,4,48.56,7.21,2.79,8.05,SO
184,Shayne Van Ness,Penn State,1,1,[149],15,15,0,100.0,13,86.7,7,4,2,2,53.40,17.46,12.15,3.67,JR
217,Joey Buttler,Indiana,51,33,[149],14,6,8,42.9,2,14.3,0,2,0,4,62.57,5.31,-0.85,7.63,SO
291,Lachlan McNeil,Michigan,17,7,[149],13,10,3,76.9,4,30.8,1,2,1,6,46.38,8.42,3.67,7.36,SR
378,Ethan Stiles,Ohio State,15,2,[149],12,10,2,83.3,3,25.0,0,1,2,7,52.08,6.40,2.70,3.86,SO
432,Drew Roberts,Minnesota,40,8,[149],11,7,4,63.6,2,18.2,1,0,1,5,47.64,5.20,1.10,5.84,SR
515,Chance Lamer,Nebraska,27,6,[149],10,5,5,50.0,3,30.0,2,1,0,2,42.50,8.67,3.00,8.47,SR
626,August Hibler,Northwestern,111,41,[149],9,0,9,0.0,0,0.0,0,0,0,0,44.22,4.12,-6.62,5.50,RSFR
645,Clayton Jones,Michigan State,68,60,[149],8,3,5,37.5,2,25.0,0,0,2,1,70.25,7.00,-6.00,9.54,SO
647,Carter Young,Maryland,13,59,[149],8,7,1,87.5,2,25.0,1,1,0,5,53.00,10.50,4.38,8.80,SR
706,Michael Gioffre,Illinois,38,12,[149],8,4,4,50.0,1,12.5,1,0,0,3,73.25,6.25,1.75,6.43,JR

157 BIG TEN WRESTLERS
Overall Stats

,wrestler_name,team_name,rank,team_rank,weight_classes,total_matches,total_wins,total_losses,win_rate,bonus_wins,bonus_rate,tf_wins,md_wins,fall_wins,dec_wins,avg_opponent_rank,avg_points_scored,avg_point_diff,std_point_diff,Class
46,Antrell Taylor,Nebraska,3,6,[157],17,15,2,88.2,9,52.9,5,2,2,6,31.65,9.87,5.67,8.72,JR
64,Luke Mechler,Wisconsin,36,22,[157],17,12,5,70.6,3,17.6,1,2,0,9,63.12,7.50,3.06,6.24,SR
86,Anthony White,Rutgers,25,8,[157],16,12,4,75.0,4,25.0,1,3,0,8,76.44,6.56,3.00,7.42,SR
148,Cam Catrabone,Michigan,18,7,[157],15,11,4,73.3,8,53.3,2,3,3,3,70.80,9.08,3.33,8.85,RSFR
169,Charlie Millard,Minnesota,15,8,[157],15,9,6,60.0,6,40.0,2,2,2,3,41.13,9.08,3.33,8.32,RSFR
202,Darius Marines,Michigan State,65,60,[157],14,7,7,50.0,2,14.3,0,1,1,5,68.64,5.18,1.09,4.81,RSFR
218,Bryce Lowery,Indiana,38,33,[157],14,6,8,42.9,4,28.6,0,2,2,2,63.79,5.67,-3.92,8.43,SO
230,Kannon Webster,Illinois,8,12,[157],14,12,2,85.7,8,57.1,4,3,1,4,52.00,10.92,7.54,6.17,SO
270,PJ Duke,Penn State,6,1,[157],13,12,1,92.3,9,69.2,3,1,5,3,71.23,12.75,7.75,6.90,FR
348,Brandon Cannon,Ohio State,4,2,[157],12,12,0,100.0,11,91.7,4,5,2,1,56.58,16.70,11.80,3.26,SO
448,Stoney Buell,Purdue,46,37,[157],11,6,5,54.5,1,9.1,1,0,0,5,69.27,5.80,0.90,6.98,SR
555,Mekhi Neal,Maryland,174,59,[157],10,1,9,10.0,0,0.0,0,0,0,1,79.40,2.00,-8.75,6.78,RSFR
704,Victor Voinovich,Iowa,39,5,[157],8,6,2,75.0,1,12.5,0,1,0,5,49.25,7.00,1.25,8.00,SR
1249,Ty Wilson,Northwestern,62,41,[157],2,1,1,50.0,0,0.0,0,0,0,1,40.50,6.00,3.00,0.00,RSFR

165 BIG TEN WRESTLERS
Overall Stats

,wrestler_name,team_name,rank,team_rank,weight_classes,total_matches,total_wins,total_losses,win_rate,bonus_wins,bonus_rate,tf_wins,md_wins,fall_wins,dec_wins,avg_opponent_rank,avg_points_scored,avg_point_diff,std_point_diff,Class
20,Michael Caliendo,Iowa,2,5,[165],18,15,3,83.3,11,61.1,6,3,2,4,41.94,12.88,7.56,7.95,SR
92,Braeden Scoles,Illinois,13,12,[165],16,11,5,68.8,5,31.2,3,2,0,6,41.75,10.06,5.12,7.31,SO
102,Cody Goebel,Wisconsin,54,22,[165],16,8,8,50.0,2,12.5,1,1,0,6,62.50,6.00,-1.94,10.08,JR
110,LJ Araujo,Nebraska,11,6,[165],16,10,6,62.5,2,12.5,0,0,2,8,20.62,4.43,-1.79,6.18,RSFR
199,Andrew Sparks,Minnesota,16,8,[165],14,11,3,78.6,5,35.7,2,2,1,6,48.86,7.69,3.54,8.13,SR
219,Tyler Lillard,Indiana,21,33,[165],14,8,6,57.1,6,42.9,2,2,2,2,56.21,10.00,4.91,7.66,JR
253,Mitchell Mesenbrink,Penn State,1,1,[165],14,14,0,100.0,14,100.0,6,3,5,0,46.14,16.67,13.00,3.04,JR
268,Paddy Gallagher,Ohio State,19,2,[165],13,7,6,53.8,4,30.8,3,1,0,3,43.77,8.15,3.69,7.95,SR
292,Joey Blaze,Purdue,4,37,[165],13,13,0,100.0,8,61.5,6,2,0,5,81.92,13.69,10.08,5.51,JR
394,AJ Rodriguez,Maryland,111,59,[165],12,4,8,33.3,1,8.3,0,1,0,3,60.50,5.17,-5.42,9.97,RSSO
466,Andrew Barbosa,Rutgers,17,8,[165],11,8,3,72.7,4,36.4,2,2,0,4,64.45,8.09,4.82,7.01,RSFR
615,Justin Gates,Michigan,87,7,[165],9,3,6,33.3,1,11.1,0,1,0,2,43.56,4.33,-4.78,9.13,RSFR
725,Jacob Bostelman,Northwestern,103,41,[165],7,2,5,28.6,0,0.0,0,0,0,2,81.29,2.00,-5.00,6.08,SO
792,Jack Conley,Michigan State,141,60,[165],6,1,5,16.7,0,0.0,0,0,0,1,52.67,3.17,-8.50,7.56,SO

174 BIG TEN WRESTLERS
Overall Stats

,wrestler_name,team_name,rank,team_rank,weight_classes,total_matches,total_wins,total_losses,win_rate,bonus_wins,bonus_rate,tf_wins,md_wins,fall_wins,dec_wins,avg_opponent_rank,avg_points_scored,avg_point_diff,std_point_diff,Class
7,Christopher Minto,Nebraska,3,6,[174],19,15,4,78.9,7,36.8,2,5,0,8,37.11,9.11,5.42,5.77,SO
37,Lucas Condon,Wisconsin,57,22,[174],17,7,10,41.2,3,17.6,1,1,1,4,59.94,5.44,-2.12,8.49,SO
73,Carson Kharchla,Ohio State,4,2,[174],17,14,3,82.4,9,52.9,7,2,0,5,51.00,11.76,7.94,6.88,SR
84,Patrick Kennedy,Iowa,5,5,[174],16,14,2,87.5,7,43.8,4,3,0,7,34.94,9.88,6.38,6.30,SR
93,Colin Kelly,Illinois,35,12,[174],16,11,5,68.8,6,37.5,3,2,1,5,83.56,8.73,4.13,7.82,RSFR
147,Beau Mantanona,Michigan,6,7,[174],15,11,4,73.3,8,53.3,2,3,3,3,49.87,9.50,3.83,8.66,SO
175,Ethan Riddle,Minnesota,34,8,[174],15,8,7,53.3,2,13.3,0,2,0,6,46.13,6.40,-2.27,8.83,SO
183,Levi Haines,Penn State,1,1,[174],15,15,0,100.0,13,86.7,6,2,5,2,82.53,15.00,11.50,5.34,SR
266,Connor O'Neill,Michigan State,120,60,[174],13,4,9,30.8,0,0.0,0,0,0,4,74.54,4.08,-6.38,7.43,SR
316,Lenny Pinto,Rutgers,28,8,[174],13,6,7,46.2,6,46.2,3,2,1,0,64.23,9.82,2.18,10.49,SR
363,Seth Digby,Maryland,172,59,"[174, 184]",12,2,10,16.7,0,0.0,0,0,0,2,75.50,4.50,-8.33,6.37,FR
391,Brody Baumann,Purdue,31,37,[174],12,9,3,75.0,5,41.7,3,2,0,4,89.67,11.67,5.25,7.57,JR
472,Derek Gilcher,Indiana,30,33,[174],11,7,4,63.6,3,27.3,3,0,0,4,61.64,9.91,3.91,9.60,SR
557,Eddie Enright,Northwestern,27,41,[174],10,6,4,60.0,3,30.0,1,2,0,3,64.20,9.60,2.90,9.94,RSFR

184 BIG TEN WRESTLERS
Overall Stats

,wrestler_name,team_name,rank,team_rank,weight_classes,total_matches,total_wins,total_losses,win_rate,bonus_wins,bonus_rate,tf_wins,md_wins,fall_wins,dec_wins,avg_opponent_rank,avg_points_scored,avg_point_diff,std_point_diff,Class
50,Shane Cartagena-Walsh,Rutgers,14,8,[184],17,12,5,70.6,10,58.8,4,4,2,2,72.00,11.93,5.07,10.10,SO
60,Silas Allred,Nebraska,7,6,[184],17,11,6,64.7,4,23.5,1,1,2,7,25.88,5.53,1.13,6.17,SR
72,Dylan Fishback,Ohio State,9,2,[184],17,11,6,64.7,7,41.2,3,3,1,4,34.94,8.19,5.19,7.27,JR
78,James Rowley,Purdue,37,37,[184],16,8,8,50.0,4,25.0,1,3,0,4,86.75,6.94,2.06,7.03,JR
91,Chris Moore,Illinois,13,12,[184],16,10,6,62.5,3,18.8,1,2,0,7,36.50,5.81,1.62,6.15,RSSO
108,Max McEnelly,Minnesota,3,8,[184],16,15,1,93.8,10,62.5,8,2,0,5,45.56,13.94,9.44,6.24,SO
130,Rocco Welsh,Penn State,1,1,[184],15,15,0,100.0,8,53.3,4,3,1,7,41.73,11.86,8.07,5.44,RSSO
144,Brock Mantanona,Michigan,8,7,[184],15,11,4,73.3,8,53.3,5,2,1,3,60.07,11.71,5.64,9.80,RSFR
323,Sam Goin,Indiana,18,33,[184],13,8,5,61.5,4,30.8,0,3,1,4,55.92,7.00,1.64,7.39,RSFR
369,Jesse Perez,Northwestern,60,41,[184],12,6,6,50.0,4,33.3,0,4,0,2,81.50,8.64,-2.09,11.85,SR
532,Cale Anderson,Wisconsin,71,22,[184],10,2,8,20.0,1,10.0,0,1,0,1,45.30,5.40,-3.20,6.51,SR
574,Angelo Ferrari,Iowa,4,5,[184],10,9,1,90.0,3,30.0,3,0,0,6,35.00,8.40,5.80,6.49,RSFR
675,Sepanta Ahanj-Elias,Maryland,93,59,[184],8,2,6,25.0,1,12.5,0,1,0,1,38.25,6.50,-5.67,9.79,FR
786,Ryan Boucher,Michigan State,128,60,[184],7,0,7,0.0,0,0.0,0,0,0,0,24.71,3.00,-10.14,5.30,SR

197 BIG TEN WRESTLERS
Overall Stats

,wrestler_name,team_name,rank,team_rank,weight_classes,total_matches,total_wins,total_losses,win_rate,bonus_wins,bonus_rate,tf_wins,md_wins,fall_wins,dec_wins,avg_opponent_rank,avg_points_scored,avg_point_diff,std_point_diff,Class
10,Camden McDanel,Nebraska,13,6,[197],19,15,4,78.9,5,26.3,2,3,0,10,45.79,8.68,4.37,6.25,SO
39,Wyatt Ingham,Wisconsin,24,22,[197],17,12,5,70.6,8,47.1,3,3,2,4,47.41,9.00,4.47,8.68,RSFR
143,Hayden Walters,Michigan,53,7,[197],15,7,8,46.7,3,20.0,0,2,1,4,51.20,4.64,-0.71,6.70,RSFR
193,Gabe Sollars,Indiana,27,33,[197],14,7,7,50.0,4,28.6,1,1,2,3,39.14,5.75,0.08,7.62,SR
196,Gavin Nelson,Minnesota,37,8,[197],14,4,10,28.6,0,0.0,0,0,0,4,23.21,2.62,-1.54,2.93,FR
211,Remy Cotton,Rutgers,22,8,[197],14,11,3,78.6,6,42.9,1,3,2,5,48.21,8.50,2.00,9.18,SO
228,Luke Geog,Ohio State,25,2,[197],14,8,6,57.1,5,35.7,1,4,0,3,43.86,9.15,2.85,8.40,JR
233,Branson John,Maryland,11,59,[197],14,10,4,71.4,7,50.0,4,1,2,3,60.43,10.08,2.92,11.30,SO
265,Kael Wisler,Michigan State,34,60,[197],13,9,4,69.2,3,23.1,2,1,0,6,68.92,8.15,3.54,7.57,RSSO
293,Ben Vanadia,Purdue,40,37,[197],13,9,4,69.2,6,46.2,1,3,2,3,76.38,9.64,3.09,9.46,SR
367,Alex Smith,Northwestern,69,41,[197],12,2,10,16.7,1,8.3,0,1,0,1,58.00,6.14,-3.71,8.08,FR
427,Gabe Arnold,Iowa,14,5,"[174, 184, 197]",11,7,4,63.6,3,27.3,1,2,0,4,30.36,6.55,3.45,6.39,SO
455,Josh Barr,Penn State,1,1,[197],11,11,0,100.0,11,100.0,5,3,3,0,54.45,17.50,13.00,2.98,SO
585,Dylan Connell,Illinois,60,12,[197],9,3,6,33.3,1,11.1,0,1,0,2,38.33,4.00,-2.00,5.57,SR

285 BIG TEN WRESTLERS
Overall Stats

,wrestler_name,team_name,rank,team_rank,weight_classes,total_matches,total_wins,total_losses,win_rate,bonus_wins,bonus_rate,tf_wins,md_wins,fall_wins,dec_wins,avg_opponent_rank,avg_points_scored,avg_point_diff,std_point_diff,Class
40,Braxton Amos,Wisconsin,12,22,[285],17,14,3,82.4,10,58.8,1,4,5,4,63.65,7.50,5.58,6.37,RSJR
44,Nick Feldman,Ohio State,5,2,[285],17,13,4,76.5,7,41.2,5,1,1,6,39.47,8.75,5.31,7.43,JR
89,Hunter Catka,Rutgers,23,8,[285],16,10,6,62.5,7,43.8,5,1,1,3,88.44,10.13,5.20,8.30,SR
120,Hayden Filipovich,Purdue,77,37,[285],16,8,8,50.0,0,0.0,0,0,0,8,74.69,3.50,-2.06,6.27,SR
123,Cole Mirasola,Penn State,8,1,[285],15,11,4,73.3,7,46.7,4,1,2,4,53.87,9.08,4.69,8.06,RSFR
134,AJ Ferrari,Nebraska,3,6,[285],15,13,2,86.7,7,46.7,2,4,1,6,35.67,8.29,5.86,5.93,JR
149,Taye Ghadiali,Michigan,4,7,[285],15,14,1,93.3,9,60.0,6,2,1,5,44.27,12.36,8.21,7.38,RSSR
229,Koy Hopke,Minnesota,15,8,[285],14,8,6,57.1,3,21.4,0,3,0,5,35.29,5.43,1.86,5.50,RSFR
517,Gabe Christenson,Northwestern,109,41,[285],10,2,8,20.0,2,20.0,0,2,0,0,51.00,4.78,-5.11,10.09,SR
556,Luke Luffman,Illinois,17,12,[285],10,8,2,80.0,3,30.0,0,3,0,5,60.60,8.10,4.50,6.77,SR
558,Caleb Marzolino,Indiana,171,33,[285],10,0,10,0.0,0,0.0,0,0,0,0,40.00,3.83,-12.33,4.27,RSFR
570,Ben Kueter,Iowa,13,5,[285],10,5,5,50.0,0,0.0,0,0,0,5,18.60,3.60,-0.20,5.31,SO
711,Josh Terrill,Michigan State,54,60,[285],8,5,3,62.5,2,25.0,0,0,2,3,66.25,2.00,-3.17,6.49,JR
763,Joey Schneck,Maryland,161,59,[285],7,2,5,28.6,1,14.3,0,1,0,1,87.00,4.83,-3.00,8.25,SO

====================================================================================================
✅ BIG TEN CONFERENCE LOADED: 140 total wrestlers
====================================================================================================

## Explore test cases

In [83]:
matches_reference.query('home_name == "Brock Hardy" or away_name == "Brock Hardy"')

,dual_id,weight_class,event_date,home_wrestler_id,home_name,home_rank,away_wrestler_id,away_name,away_rank,home_win,win_type,Result,home_class,home_team_name,away_class,away_team_name
103,272,141,11/7/2025,217.0,Brock Hardy,3.0,960.0,Braden Basile,32.0,True,WTF,WTF5 18 - 2 6:16,SR,Nebraska,JR,Army West Point
418,220,141,11/15/2025,217.0,Brock Hardy,3.0,639.0,Carter Bailey,44.0,True,WFALL,WFALL 6:11,SR,Nebraska,SR,Lehigh
533,207,141,11/15/2025,217.0,Brock Hardy,3.0,1091.0,Eren Sement,40.0,True,WTF,WTF5 20 - 5 7:00,SR,Nebraska,FR,Michigan
861,189,141,11/16/2025,444.0,Jesse Mendez,2.0,217.0,Brock Hardy,3.0,True,WDEC,WDEC 4 - 1,SR,Ohio State,SR,Nebraska
873,190,141,11/16/2025,592.0,Sergio Vega,1.0,217.0,Brock Hardy,3.0,True,WMD,WMD 13 - 2,FR,Oklahoma State,SR,Nebraska
1289,148,141,12/5/2025,217.0,Brock Hardy,3.0,1056.0,Khimari Manns,90.0,True,WFALL,WFALL 2:32,SR,Nebraska,FR,Brown
1300,149,141,12/5/2025,929.0,Zeke Seltzer,62.0,217.0,Brock Hardy,3.0,False,LTF,LTF5 19 - 4 5:40,JR,Missouri,SR,Nebraska
1822,99,141,12/19/2025,217.0,Brock Hardy,3.0,645.0,Luke Simcox,26.0,True,WDEC,WDEC 5 - 0,SR,Nebraska,RSFR,North Carolina
2126,60,141,12/21/2025,217.0,Brock Hardy,3.0,592.0,Sergio Vega,1.0,False,LFALL,LFALL 1:47,SR,Nebraska,FR,Oklahoma State
2351,48,141,1/3/2026,217.0,Brock Hardy,3.0,32.0,Cory Land,16.0,True,WDEC,WDEC 5 - 1,SR,Nebraska,JR,Northern Iowa
2673,30,141,1/9/2026,217.0,Brock Hardy,3.0,227.0,Vinny Paino,58.0,True,WFALL,WFALL 3:57,SR,Nebraska,FR,Purdue
3584,373,141,1/23/2026,217.0,Brock Hardy,3.0,990.0,Nasir Bailey,11.0,True,WDEC,WDEC 1 - 0,SR,Nebraska,JR,Iowa
3910,352,141,1/25/2026,217.0,Brock Hardy,3.0,444.0,Jesse Mendez,1.0,False,LMD,LMD 14 - 3,SR,Nebraska,SR,Ohio State
3982,411,141,1/30/2026,121.0,Braeden Davis,7.0,217.0,Brock Hardy,3.0,False,LFALL,LFALL 5:55,JR,Penn State,SR,Nebraska
4801,490,141,2/8/2026,217.0,Brock Hardy,3.0,336.0,Billy Dekraker,55.0,True,WTF,WTF5 18 - 2 4:25,SR,Nebraska,FR,Northwestern
5048,469,141,2/13/2026,217.0,Brock Hardy,3.0,574.0,William Baysingar,124.0,True,WTF,WTF5 20 - 4 6:31,SR,Nebraska,SO,Illinois
5226,441,141,2/15/2026,950.0,Henry Porter,36.0,217.0,Brock Hardy,3.0,False,LTF,LTF5 20 - 4 6:38,JR,Indiana,SR,Nebraska
5686,564,141,2/21/2026,872.0,Haiden Drury,31.0,217.0,Brock Hardy,3.0,False,LDEC,LDEC 5 - 2,SR,Utah Valley,SR,Nebraska

In [84]:
display(inference_pipeline_db.query('wrestler_name == "Brock Hardy"'))
display(inference_pipeline_db.query('wrestler_name == "Braeden Davis"'))
#

,wrestler_name,team_name,rank,team_rank,weight_classes,total_matches,total_wins,total_losses,win_rate,bonus_wins,bonus_rate,tf_wins,md_wins,fall_wins,dec_wins,avg_opponent_rank,avg_points_scored,avg_point_diff,std_point_diff,Class
21,Brock Hardy,Nebraska,3,6,[141],18,14,4,77.8,10,55.6,6,0,4,4,35.39,10.54,6.0,9.93,SR

,wrestler_name,team_name,rank,team_rank,weight_classes,total_matches,total_wins,total_losses,win_rate,bonus_wins,bonus_rate,tf_wins,md_wins,fall_wins,dec_wins,avg_opponent_rank,avg_points_scored,avg_point_diff,std_point_diff,Class
674,Braeden Davis,Penn State,11,1,[141],8,5,3,62.5,4,50.0,0,4,0,1,33.5,11.57,4.86,10.29,JR

In [85]:
# ============================================
# BIG TEN TEST CASES
# ============================================

print("\n" + "="*100)
print("🏆 BIG TEN CONFERENCE TEST CASES")
print("="*100)

# ============================================
# CASE 1: BEN DAVINO vs DRAKE AYALA
# ============================================

print("\n" + "="*80)
print("🔍 TEST CASE 1: BEN DAVINO vs DRAKE AYALA")
print("="*80)

# Get their match history
hist_features_ben_drake = get_wrestler_match_history(
    "Ben Davino", "Drake Ayala", matches_reference
)

print(f"\n📜 Raw Historical Features (from Ben Davino's perspective):")
print(f"   wrestled_before: {hist_features_ben_drake['wrestled_before']}")
print(f"   total_matches: {hist_features_ben_drake['total_matches']}")
print(f"   Ben Davino wins: {hist_features_ben_drake['w1_wins']}")
print(f"   Drake Ayala wins: {hist_features_ben_drake['w2_wins']}")
print(f"   Avg point diff (Ben's perspective): {hist_features_ben_drake['avg_point_diff_w1']}")
print(f"   Last match: {hist_features_ben_drake['last_match_date']} (Winner: {hist_features_ben_drake['last_winner']})")

# Prepare features for prediction
print(f"\n📊 Wrestler Data from Inference Pipeline:")
ben_data = inference_pipeline_db[inference_pipeline_db['wrestler_name'] == 'Ben Davino'].iloc[0]
drake_data = inference_pipeline_db[inference_pipeline_db['wrestler_name'] == 'Drake Ayala'].iloc[0]

print(f"   Ben Davino - Rank: {ben_data['rank']}, Team: {ben_data['team_name']}, Win Rate: {ben_data['win_rate']}%")
print(f"   Drake Ayala - Rank: {drake_data['rank']}, Team: {drake_data['team_name']}, Win Rate: {drake_data['win_rate']}%")

# Calculate win_rate_diff for LOGREG
win_rate_diff = ben_data['win_rate']/100 - drake_data['win_rate']/100
print(f"\n📊 LOGREG Input (win_rate_diff): {win_rate_diff:.4f} (Ben {ben_data['win_rate']}% - Drake {drake_data['win_rate']}%)")

# Prepare features for prediction - Penn State forced home (but neither is Penn State, so rank decides)
features_ben_drake, home_name_ben_drake, away_name_ben_drake, home_data_ben_drake, away_data_ben_drake = prepare_matchup_features(
    "Ben Davino", "Drake Ayala", hist_features_ben_drake, inference_pipeline_db, team_name="Penn State", weight_class=133
)

# Make predictions
results_ben_drake = predict_matchup("Ben Davino", "Drake Ayala", features_ben_drake, home_name_ben_drake, away_name_ben_drake)

# Print detailed information
print_matchup_details(
    "Ben Davino", "Drake Ayala",
    hist_features_ben_drake, features_ben_drake, results_ben_drake,
    home_name_ben_drake, away_name_ben_drake, home_data_ben_drake, away_data_ben_drake
)

# Verification of expected values
print("\n" + "="*60)
print("✅ EXPECTED VALUES VERIFICATION")
print("="*60)
print(f"Expected wrestled_before: 1 → Actual: {features_ben_drake['wrestled_before']}")
print(f"Expected home_point_diff_rematches (Ben's avg): {(6+2)/2} → Actual: {features_ben_drake['home_point_diff_rematches']}")
print(f"Expected home_pinned_away: 0 → Actual: {features_ben_drake['home_pinned_away']}")


# ============================================
# CASE 2: BEN DAVINO vs MARCUS BLAZE
# ============================================

print("\n" + "="*80)
print("🔍 TEST CASE 2: BEN DAVINO vs MARCUS BLAZE")
print("="*80)

# Get their match history
hist_features_ben_marcus = get_wrestler_match_history(
    "Ben Davino", "Marcus Blaze", matches_reference
)

print(f"\n📜 Raw Historical Features (from Ben Davino's perspective):")
print(f"   wrestled_before: {hist_features_ben_marcus['wrestled_before']}")
print(f"   total_matches: {hist_features_ben_marcus['total_matches']}")
print(f"   Ben Davino wins: {hist_features_ben_marcus['w1_wins']}")
print(f"   Marcus Blaze wins: {hist_features_ben_marcus['w2_wins']}")
print(f"   Avg point diff (Ben's perspective): {hist_features_ben_marcus['avg_point_diff_w1']}")
print(f"   Last match: {hist_features_ben_marcus['last_match_date']} (Winner: {hist_features_ben_marcus['last_winner']})")

# Prepare features for prediction
print(f"\n📊 Wrestler Data from Inference Pipeline:")
ben_data = inference_pipeline_db[inference_pipeline_db['wrestler_name'] == 'Ben Davino'].iloc[0]
marcus_data = inference_pipeline_db[inference_pipeline_db['wrestler_name'] == 'Marcus Blaze'].iloc[0]

print(f"   Ben Davino - Rank: {ben_data['rank']}, Team: {ben_data['team_name']}, Win Rate: {ben_data['win_rate']}%")
print(f"   Marcus Blaze - Rank: {marcus_data['rank']}, Team: {marcus_data['team_name']}, Win Rate: {marcus_data['win_rate']}%")

# Calculate win_rate_diff for LOGREG
win_rate_diff = ben_data['win_rate']/100 - marcus_data['win_rate']/100
print(f"\n📊 LOGREG Input (win_rate_diff): {win_rate_diff:.4f} (Ben {ben_data['win_rate']}% - Marcus {marcus_data['win_rate']}%)")

# Prepare features for prediction - Penn State forced home (Marcus is Penn State)
features_ben_marcus, home_name_ben_marcus, away_name_ben_marcus, home_data_ben_marcus, away_data_ben_marcus = prepare_matchup_features(
    "Ben Davino", "Marcus Blaze", hist_features_ben_marcus, inference_pipeline_db, team_name="Penn State", weight_class=133
)

# Make predictions
results_ben_marcus = predict_matchup("Ben Davino", "Marcus Blaze", features_ben_marcus, home_name_ben_marcus, away_name_ben_marcus)

# Print detailed information
print_matchup_details(
    "Ben Davino", "Marcus Blaze",
    hist_features_ben_marcus, features_ben_marcus, results_ben_marcus,
    home_name_ben_marcus, away_name_ben_marcus, home_data_ben_marcus, away_data_ben_marcus
)

# Verification of expected values
print("\n" + "="*60)
print("✅ EXPECTED VALUES VERIFICATION")
print("="*60)
print(f"Expected wrestled_before: 1 → Actual: {features_ben_marcus['wrestled_before']}")
print(f"Expected home_point_diff_rematches (Marcus's avg from his perspective): 1 → Actual: {features_ben_marcus['home_point_diff_rematches']}")
print(f"Expected home_pinned_away: 0 → Actual: {features_ben_marcus['home_pinned_away']}")
print(f"Expected home wrestler (Marcus - Penn State): Marcus Blaze → Actual: {home_name_ben_marcus}")


# ============================================
# CASE 3: AJ FERRARI vs NICK FELDMAN
# ============================================

print("\n" + "="*80)
print("🔍 TEST CASE 3: AJ FERRARI vs NICK FELDMAN")
print("="*80)

# Get their match history
hist_features_aj_nick = get_wrestler_match_history(
    "AJ Ferrari", "Nick Feldman", matches_reference
)

print(f"\n📜 Raw Historical Features (from AJ Ferrari's perspective):")
print(f"   wrestled_before: {hist_features_aj_nick['wrestled_before']}")
print(f"   total_matches: {hist_features_aj_nick['total_matches']}")
print(f"   AJ Ferrari wins: {hist_features_aj_nick['w1_wins']}")
print(f"   Nick Feldman wins: {hist_features_aj_nick['w2_wins']}")
print(f"   Avg point diff (AJ's perspective): {hist_features_aj_nick['avg_point_diff_w1']}")
print(f"   Last match: {hist_features_aj_nick['last_match_date']} (Winner: {hist_features_aj_nick['last_winner']})")

# Prepare features for prediction
print(f"\n📊 Wrestler Data from Inference Pipeline:")
aj_data = inference_pipeline_db[inference_pipeline_db['wrestler_name'] == 'AJ Ferrari'].iloc[0]
nick_data = inference_pipeline_db[inference_pipeline_db['wrestler_name'] == 'Nick Feldman'].iloc[0]

print(f"   AJ Ferrari - Rank: {aj_data['rank']}, Team: {aj_data['team_name']}, Win Rate: {aj_data['win_rate']}%")
print(f"   Nick Feldman - Rank: {nick_data['rank']}, Team: {nick_data['team_name']}, Win Rate: {nick_data['win_rate']}%")

# Calculate win_rate_diff for LOGREG
win_rate_diff = aj_data['win_rate']/100 - nick_data['win_rate']/100
print(f"\n📊 LOGREG Input (win_rate_diff): {win_rate_diff:.4f} (AJ {aj_data['win_rate']}% - Nick {nick_data['win_rate']}%)")

# Prepare features for prediction - Penn State forced home (neither is Penn State, so rank decides)
features_aj_nick, home_name_aj_nick, away_name_aj_nick, home_data_aj_nick, away_data_aj_nick = prepare_matchup_features(
    "AJ Ferrari", "Nick Feldman", hist_features_aj_nick, inference_pipeline_db, team_name="Penn State", weight_class=285
)

# Make predictions
results_aj_nick = predict_matchup("AJ Ferrari", "Nick Feldman", features_aj_nick, home_name_aj_nick, away_name_aj_nick)

# Print detailed information
print_matchup_details(
    "AJ Ferrari", "Nick Feldman",
    hist_features_aj_nick, features_aj_nick, results_aj_nick,
    home_name_aj_nick, away_name_aj_nick, home_data_aj_nick, away_data_aj_nick
)

# Verification of expected values
print("\n" + "="*60)
print("✅ EXPECTED VALUES VERIFICATION")
print("="*60)
print(f"Expected wrestled_before: 2 → Actual: {features_aj_nick['wrestled_before']}")
print(f"Expected avg point diff from home's perspective: {(1+3)/2 if home_name_aj_nick == 'Nick Feldman' else -((1+3)/2)} → Actual: {features_aj_nick['home_point_diff_rematches']}")
print(f"Expected home_pinned_away: 0 → Actual: {features_aj_nick['home_pinned_away']}")


# ============================================
# CASE 4: BROCK HARDY vs BRAEDEN DAVIS
# ============================================

print("\n" + "="*80)
print("🔍 TEST CASE 4: BROCK HARDY vs BRAEDEN DAVIS")
print("="*80)

# Get their match history
hist_features_brock_braeden = get_wrestler_match_history(
    "Brock Hardy", "Braeden Davis", matches_reference
)

print(f"\n📜 Raw Historical Features (from Brock Hardy's perspective):")
print(f"   wrestled_before: {hist_features_brock_braeden['wrestled_before']}")
print(f"   total_matches: {hist_features_brock_braeden['total_matches']}")
print(f"   Brock Hardy wins: {hist_features_brock_braeden['w1_wins']}")
print(f"   Braeden Davis wins: {hist_features_brock_braeden['w2_wins']}")
print(f"   Avg point diff (Brock's perspective): {hist_features_brock_braeden['avg_point_diff_w1']}")
print(f"   Pins by Brock: {hist_features_brock_braeden['pins_by_w1']}")
print(f"   Pins by Braeden: {hist_features_brock_braeden['pins_by_w2']}")
print(f"   Last match: {hist_features_brock_braeden['last_match_date']} (Winner: {hist_features_brock_braeden['last_winner']})")

# Prepare features for prediction
print(f"\n📊 Wrestler Data from Inference Pipeline:")
brock_data = inference_pipeline_db[inference_pipeline_db['wrestler_name'] == 'Brock Hardy'].iloc[0]
braeden_data = inference_pipeline_db[inference_pipeline_db['wrestler_name'] == 'Braeden Davis'].iloc[0]

print(f"   Brock Hardy - Rank: {brock_data['rank']}, Team: {brock_data['team_name']}, Win Rate: {brock_data['win_rate']}%")
print(f"   Braeden Davis - Rank: {braeden_data['rank']}, Team: {braeden_data['team_name']}, Win Rate: {braeden_data['win_rate']}%")

# Calculate win_rate_diff for LOGREG
win_rate_diff = brock_data['win_rate']/100 - braeden_data['win_rate']/100
print(f"\n📊 LOGREG Input (win_rate_diff): {win_rate_diff:.4f} (Brock {brock_data['win_rate']}% - Braeden {braeden_data['win_rate']}%)")

# Prepare features for prediction - Penn State forced home (Braeden is Penn State)
features_brock_braeden, home_name_brock_braeden, away_name_brock_braeden, home_data_brock_braeden, away_data_brock_braeden = prepare_matchup_features(
    "Brock Hardy", "Braeden Davis", hist_features_brock_braeden, inference_pipeline_db, team_name="Penn State", weight_class=141
)

# Make predictions
results_brock_braeden = predict_matchup("Brock Hardy", "Braeden Davis", features_brock_braeden, home_name_brock_braeden, away_name_brock_braeden)

# Print detailed information
print_matchup_details(
    "Brock Hardy", "Braeden Davis",
    hist_features_brock_braeden, features_brock_braeden, results_brock_braeden,
    home_name_brock_braeden, away_name_brock_braeden, home_data_brock_braeden, away_data_brock_braeden
)

# Verification of expected values
print("\n" + "="*60)
print("✅ EXPECTED VALUES VERIFICATION")
print("="*60)
print(f"Expected wrestled_before: 1 → Actual: {features_brock_braeden['wrestled_before']}")
print(f"Expected home_point_diff_rematches (pin means no points, so 0 from winner's perspective): 0 → Actual: {features_brock_braeden['home_point_diff_rematches']}")
print(f"Expected home_pinned_away: 1 (since Brock pinned Braeden and Braeden is home) → Actual: {features_brock_braeden['home_pinned_away']}")
print(f"Expected home wrestler (Braeden - Penn State): Braeden Davis → Actual: {home_name_brock_braeden}")

print("\n" + "="*100)
print("✅ BIG TEN TEST CASES COMPLETE")
print("="*100)

====================================================================================================
🏆 BIG TEN CONFERENCE TEST CASES
====================================================================================================

================================================================================
🔍 TEST CASE 1: BEN DAVINO vs DRAKE AYALA
================================================================================

📜 Raw Historical Features (from Ben Davino's perspective):
   wrestled_before: 1
   total_matches: 2
   Ben Davino wins: 2
   Drake Ayala wins: 0
   Avg point diff (Ben's perspective): 4.0
   Last match: 2/6/2026 (Winner: Ben Davino)

📊 Wrestler Data from Inference Pipeline:
   Ben Davino - Rank: 4, Team: Ohio State, Win Rate: 94.7%
   Drake Ayala - Rank: 10, Team: Iowa, Win Rate: 56.2%

📊 LOGREG Input (win_rate_diff): 0.3850 (Ben 94.7% - Drake 56.2%)

📌 Home wrestler: Ben Davino (Rank: 4, Team: Ohio State)
📌 Away wrestler: Drake Ayala (Rank: 10, Team: Iowa)

================================================================================
🔍 MATCHUP DETAILS: Ben Davino vs Drake Ayala
================================================================================

📜 HISTORICAL SUMMARY:
   Previous matches: 2
   Ben Davino wins: 2
   Drake Ayala wins: 0
   Avg point diff (Ben Davino's perspective): 4.0
   Last match: 2/6/2026 (Winner: Ben Davino)

🔍 HISTORICAL FEATURES FOR MODELS:
   wrestled_before: 1
   home_point_diff_rematches: 4.0
   home_pinned_away: 0

📊 KEY DIFFERENTIALS (home - away):
   win_rate_diff: 0.3850 (Ben Davino 94.7% - Drake Ayala 56.2%)
   matches_wrestled_diff: 3
   bonus_rate_diff: 0.1940
   avg_point_diff_diff: 6.1600
   team_rank_diff: -3

📊 FULL FEATURE ARRAYS:

📊 DT/XGB1 features (33 total):
    1. wrestled_before                     =   1.0000
    2. home_point_diff_rematches           =   4.0000
    3. home_pinned_away                    =   0.0000
    4. weight_class_133                    =   1.0000
    5. weight_class_141                    =   0.0000
    6. weight_class_149                    =   0.0000
    7. weight_class_157                    =   0.0000
    8. weight_class_165                    =   0.0000
    9. weight_class_174                    =   0.0000
   10. weight_class_184                    =   0.0000
   ...

📊 XGB2 features (34 total):
    1. wrestled_before                     =   1.0000
    2. home_point_diff_rematches           =   4.0000
    3. home_pinned_away                    =   0.0000
    4. matches_wrestled_diff               =   3.0000
    5. win_rate_diff                       =   0.3850
    6. bonus_rate_diff                     =   0.1940
    7. pin_count_diff                      =   0.0000
    8. avg_point_diff_diff                 =   6.1600
    9. avg_points_scored_diff              =   2.7700
   10. std_point_diff_diff                 =  -4.1700
   ...

🔮 PREDICTIONS:
   LOGREG: Ben Davino wins with 70.0% confidence
   DT    : Ben Davino wins with 74.6% confidence
   XGB1  : Ben Davino wins with 78.0% confidence
   XGB2  : Ben Davino wins with 72.7% confidence

✅ All models agree: Ben Davino wins!

============================================================
✅ EXPECTED VALUES VERIFICATION
============================================================
Expected wrestled_before: 1 → Actual: 1
Expected home_point_diff_rematches (Ben's avg): 4.0 → Actual: 4.0
Expected home_pinned_away: 0 → Actual: 0

================================================================================
🔍 TEST CASE 2: BEN DAVINO vs MARCUS BLAZE
================================================================================

📜 Raw Historical Features (from Ben Davino's perspective):
   wrestled_before: 1
   total_matches: 1
   Ben Davino wins: 0
   Marcus Blaze wins: 1
   Avg point diff (Ben's perspective): -1.0
   Last match: 2/13/2026 (Winner: Marcus Blaze)

📊 Wrestler Data from Inference Pipeline:
   Ben Davino - Rank: 4, Team: Ohio State, Win Rate: 94.7%
   Marcus Blaze - Rank: 3, Team: Penn State, Win Rate: 100.0%

📊 LOGREG Input (win_rate_diff): -0.0530 (Ben 94.7% - Marcus 100.0%)

📌 Home wrestler: Marcus Blaze (Rank: 3, Team: Penn State)
📌 Away wrestler: Ben Davino (Rank: 4, Team: Ohio State)

================================================================================
🔍 MATCHUP DETAILS: Ben Davino vs Marcus Blaze
================================================================================

📜 HISTORICAL SUMMARY:
   Previous matches: 1
   Ben Davino wins: 0
   Marcus Blaze wins: 1
   Avg point diff (Ben Davino's perspective): -1.0
   Last match: 2/13/2026 (Winner: Marcus Blaze)

🔍 HISTORICAL FEATURES FOR MODELS:
   wrestled_before: 1
   home_point_diff_rematches: 1.0
   home_pinned_away: 0

📊 KEY DIFFERENTIALS (home - away):
   win_rate_diff: 0.0530 (Marcus Blaze 100.0% - Ben Davino 94.7%)
   matches_wrestled_diff: -4
   bonus_rate_diff: 0.1680
   avg_point_diff_diff: -0.2200
   team_rank_diff: -1

📊 FULL FEATURE ARRAYS:

📊 DT/XGB1 features (33 total):
    1. wrestled_before                     =   1.0000
    2. home_point_diff_rematches           =   1.0000
    3. home_pinned_away                    =   0.0000
    4. weight_class_133                    =   1.0000
    5. weight_class_141                    =   0.0000
    6. weight_class_149                    =   0.0000
    7. weight_class_157                    =   0.0000
    8. weight_class_165                    =   0.0000
    9. weight_class_174                    =   0.0000
   10. weight_class_184                    =   0.0000
   ...

📊 XGB2 features (34 total):
    1. wrestled_before                     =   1.0000
    2. home_point_diff_rematches           =   1.0000
    3. home_pinned_away                    =   0.0000
    4. matches_wrestled_diff               =  -4.0000
    5. win_rate_diff                       =   0.0530
    6. bonus_rate_diff                     =   0.1680
    7. pin_count_diff                      =   2.0000
    8. avg_point_diff_diff                 =  -0.2200
    9. avg_points_scored_diff              =  -0.7500
   10. std_point_diff_diff                 =  -0.5700
   ...

🔮 PREDICTIONS:
   LOGREG: Marcus Blaze wins with 53.1% confidence
   DT    : Marcus Blaze wins with 61.1% confidence
   XGB1  : Marcus Blaze wins with 58.2% confidence
   XGB2  : Marcus Blaze wins with 82.4% confidence

✅ All models agree: Marcus Blaze wins!

============================================================
✅ EXPECTED VALUES VERIFICATION
============================================================
Expected wrestled_before: 1 → Actual: 1
Expected home_point_diff_rematches (Marcus's avg from his perspective): 1 → Actual: 1.0
Expected home_pinned_away: 0 → Actual: 0
Expected home wrestler (Marcus - Penn State): Marcus Blaze → Actual: Marcus Blaze

================================================================================
🔍 TEST CASE 3: AJ FERRARI vs NICK FELDMAN
================================================================================

📜 Raw Historical Features (from AJ Ferrari's perspective):
   wrestled_before: 1
   total_matches: 2
   AJ Ferrari wins: 0
   Nick Feldman wins: 2
   Avg point diff (AJ's perspective): -2.0
   Last match: 11/16/2025 (Winner: Nick Feldman)

📊 Wrestler Data from Inference Pipeline:
   AJ Ferrari - Rank: 3, Team: Nebraska, Win Rate: 86.7%
   Nick Feldman - Rank: 5, Team: Ohio State, Win Rate: 76.5%

📊 LOGREG Input (win_rate_diff): 0.1020 (AJ 86.7% - Nick 76.5%)

📌 Home wrestler: AJ Ferrari (Rank: 3, Team: Nebraska)
📌 Away wrestler: Nick Feldman (Rank: 5, Team: Ohio State)

================================================================================
🔍 MATCHUP DETAILS: AJ Ferrari vs Nick Feldman
================================================================================

📜 HISTORICAL SUMMARY:
   Previous matches: 2
   AJ Ferrari wins: 0
   Nick Feldman wins: 2
   Avg point diff (AJ Ferrari's perspective): -2.0
   Last match: 11/16/2025 (Winner: Nick Feldman)

🔍 HISTORICAL FEATURES FOR MODELS:
   wrestled_before: 1
   home_point_diff_rematches: -2.0
   home_pinned_away: 0

📊 KEY DIFFERENTIALS (home - away):
   win_rate_diff: 0.1020 (AJ Ferrari 86.7% - Nick Feldman 76.5%)
   matches_wrestled_diff: -2
   bonus_rate_diff: 0.0550
   avg_point_diff_diff: 0.5500
   team_rank_diff: 4

📊 FULL FEATURE ARRAYS:

📊 DT/XGB1 features (33 total):
    1. wrestled_before                     =   1.0000
    2. home_point_diff_rematches           =  -2.0000
    3. home_pinned_away                    =   0.0000
    4. weight_class_133                    =   0.0000
    5. weight_class_141                    =   0.0000
    6. weight_class_149                    =   0.0000
    7. weight_class_157                    =   0.0000
    8. weight_class_165                    =   0.0000
    9. weight_class_174                    =   0.0000
   10. weight_class_184                    =   0.0000
   ...

📊 XGB2 features (34 total):
    1. wrestled_before                     =   1.0000
    2. home_point_diff_rematches           =  -2.0000
    3. home_pinned_away                    =   0.0000
    4. matches_wrestled_diff               =  -2.0000
    5. win_rate_diff                       =   0.1020
    6. bonus_rate_diff                     =   0.0550
    7. pin_count_diff                      =   0.0000
    8. avg_point_diff_diff                 =   0.5500
    9. avg_points_scored_diff              =  -0.4600
   10. std_point_diff_diff                 =  -1.5000
   ...

🔮 PREDICTIONS:
   LOGREG: AJ Ferrari wins with 55.8% confidence
   DT    : AJ Ferrari wins with 61.1% confidence
   XGB1  : AJ Ferrari wins with 58.4% confidence
   XGB2  : AJ Ferrari wins with 50.8% confidence

✅ All models agree: AJ Ferrari wins!

============================================================
✅ EXPECTED VALUES VERIFICATION
============================================================
Expected wrestled_before: 2 → Actual: 1
Expected avg point diff from home's perspective: -2.0 → Actual: -2.0
Expected home_pinned_away: 0 → Actual: 0

================================================================================
🔍 TEST CASE 4: BROCK HARDY vs BRAEDEN DAVIS
================================================================================

📜 Raw Historical Features (from Brock Hardy's perspective):
   wrestled_before: 1
   total_matches: 1
   Brock Hardy wins: 1
   Braeden Davis wins: 0
   Avg point diff (Brock's perspective): 0
   Pins by Brock: 1
   Pins by Braeden: 0
   Last match: 1/30/2026 (Winner: Brock Hardy)

📊 Wrestler Data from Inference Pipeline:
   Brock Hardy - Rank: 3, Team: Nebraska, Win Rate: 77.8%
   Braeden Davis - Rank: 11, Team: Penn State, Win Rate: 62.5%

📊 LOGREG Input (win_rate_diff): 0.1530 (Brock 77.8% - Braeden 62.5%)

📌 Home wrestler: Braeden Davis (Rank: 11, Team: Penn State)
📌 Away wrestler: Brock Hardy (Rank: 3, Team: Nebraska)

================================================================================
🔍 MATCHUP DETAILS: Brock Hardy vs Braeden Davis
================================================================================

📜 HISTORICAL SUMMARY:
   Previous matches: 1
   Brock Hardy wins: 1
   Braeden Davis wins: 0
   Avg point diff (Brock Hardy's perspective): 0
   Last match: 1/30/2026 (Winner: Brock Hardy)

🔍 HISTORICAL FEATURES FOR MODELS:
   wrestled_before: 1
   home_point_diff_rematches: 0
   home_pinned_away: 0

📊 KEY DIFFERENTIALS (home - away):
   win_rate_diff: -0.1530 (Braeden Davis 62.5% - Brock Hardy 77.8%)
   matches_wrestled_diff: -10
   bonus_rate_diff: -0.0560
   avg_point_diff_diff: -1.1400
   team_rank_diff: -5

📊 FULL FEATURE ARRAYS:

📊 DT/XGB1 features (33 total):
    1. wrestled_before                     =   1.0000
    2. home_point_diff_rematches           =   0.0000
    3. home_pinned_away                    =   0.0000
    4. weight_class_133                    =   0.0000
    5. weight_class_141                    =   1.0000
    6. weight_class_149                    =   0.0000
    7. weight_class_157                    =   0.0000
    8. weight_class_165                    =   0.0000
    9. weight_class_174                    =   0.0000
   10. weight_class_184                    =   0.0000
   ...

📊 XGB2 features (34 total):
    1. wrestled_before                     =   1.0000
    2. home_point_diff_rematches           =   0.0000
    3. home_pinned_away                    =   0.0000
    4. matches_wrestled_diff               = -10.0000
    5. win_rate_diff                       =  -0.1530
    6. bonus_rate_diff                     =  -0.0560
    7. pin_count_diff                      =  -4.0000
    8. avg_point_diff_diff                 =  -1.1400
    9. avg_points_scored_diff              =   1.0300
   10. std_point_diff_diff                 =   0.3600
   ...

🔮 PREDICTIONS:
   LOGREG: Brock Hardy wins with 58.0% confidence
   DT    : Brock Hardy wins with 74.7% confidence
   XGB1  : Brock Hardy wins with 60.8% confidence
   XGB2  : Brock Hardy wins with 61.9% confidence

✅ All models agree: Brock Hardy wins!

============================================================
✅ EXPECTED VALUES VERIFICATION
============================================================
Expected wrestled_before: 1 → Actual: 1
Expected home_point_diff_rematches (pin means no points, so 0 from winner's perspective): 0 → Actual: 0
Expected home_pinned_away: 1 (since Brock pinned Braeden and Braeden is home) → Actual: 0
Expected home wrestler (Braeden - Penn State): Braeden Davis → Actual: Braeden Davis

====================================================================================================
✅ BIG TEN TEST CASES COMPLETE
====================================================================================================

# Make Predictions

In [86]:
# ============================================
# BIG TEN WRESTLER LISTS
# ============================================

print("\n" + "="*100)
print("🏆 BIG TEN CONFERENCE - FULL PREDICTION LOOP")
print("="*100)

# # 125 lbs
# wrestlers_125 = [
#     "Luke Lilledahl", "Spencer Moore", "Nic Bouzakis", "Jacob Moran", "Jore Volk",
#     "Ayden Smith", "Nicolar Rivera", "Dean Peterson", "Diego Sotelo", "Dedrick Navarro",
#     "Kael Lauridsen", "Nick Corday", "Ashton Jackson", "Abram Cline"
# ]

# # 133 lbs
# wrestlers_133 = [
#     "Marcus Blaze", "Lucas Byrd", "Ben Davino", "Zan Fugitt", "Drake Ayala",
#     "Jacob Van Dee", "Sean Spidle", "Braxton Brown", "Dylan Shawver", "Blake Boarman",
#     "Caleb Weiand", "Blaine Frazier", "Gauge Botero", "Jager Eisch"
# ]

# # 141 lbs
# wrestlers_141 = [
#     "Jesse Mendez", "Brock Hardy", "Vance VomBaur", "Nasir Bailey", "Dylan Ragusin",
#     "Greyson Clark", "Braeden Davis", "Billy Dekraker", "Henry Porter", "Joseph Olivieri",
#     "Dario Lemus", "Danny Pucino", "Carson Exferd", "Jaden Crumpler"
# ]

# # 149 lbs
# wrestlers_149 = [
#     "Shayne Van Ness", "Ethan Stiles", "Joseph Zargo", "Lachlan McNeil", "Carter Young",
#     "Chance Lamer", "Andrew Clark", "Ryder Block", "Michael Gioffre", "Drew Roberts",
#     "Joey Buttler", "Gavin Brown", "Clayton Jones", "August Hibler"
# ]

# # 157 lbs
# wrestlers_157 = [
#     "Antrell Taylor", "PJ Duke", "Kannon Webster", "Anthony White", "Cameron Catrabone",
#     "Charlie Millard", "Brandon Cannon", "Luke Mechler", "Stoney Buell", "Victor Voinovich III",
#     "Bryce Lowery", "Darius Marines", "Mekhi Neal", "Ty Wilson"
# ]

# # 165 lbs
# wrestlers_165 = [
#     "Mitchell Mesenbrink", "Michael Caliendo", "Joey Blaze", "Andrew Sparks", "LJ Araujo",
#     "Braeden Scoles", "Andrew Barbosa", "Paddy Gallagher", "Tyler Lillard", "Cody Goebel",
#     "Jacob Bostelman", "Justin Gates", "AJ Rodrigues", "Jack Conley"
# ]

# # 174 lbs
# wrestlers_174 = [
#     "Christopher Minto", "Levi Haines", "Patrick Kennedy", "Beau Mantanona", "Carson Kharchla",
#     "Derek Gilcher", "Ethan Riddle", "Brody Baumann", "Colin Kelly", "Lenny Pinto",
#     "Eddie Enright", "Luke Condon", "Connor O'Neil", "Seth Digby"
# ]

# # 184 lbs
# wrestlers_184 = [
#     "Rocco Welsh", "Max McEnelly", "Silas Allred", "Brock Mantanona", "Chris Moore",
#     "Dylan Fishback", "Shane Cartagena-Walsh", "Angelo Ferrari", "Sam Goin", "James Rowley",
#     "Jesse Perez", "Sepanta Ahanj-Elias", "Ryan Boucher", "Cale Anderson"
# ]

# # 197 lbs
# wrestlers_197 = [
#     "Josh Barr", "Camden McDanel", "Remy Cotton", "Branson John", "Luke Geog",
#     "Wyatt Ingham", "Kael Wisler", "Gabe Sollars", "Ben Vanadia", "Hayden Walters",
#     "Gavin Nelson", "Dylan Connell", "Gabe Arnold", "Alex Smith"
# ]

# # 285 lbs
# wrestlers_285 = [
#     "Taye Ghadiali", "AJ Ferrari", "Nick Feldman", "Cole Mirasola", "Braxton Amos",
#     "Luke Luffman", "Koy Hopke", "Hunter Catka", "Josh Terrill", "Ben Kueter",
#     "Hayden Filipovich", "Joey Schneck", "Gabe Christenson", "Caleb Marzolino"
# ]

# ============================================
# COMBINE INTO MASTER LIST
# ============================================

all_wrestler_list = [
    wrestlers_125, wrestlers_133, wrestlers_141, wrestlers_149,
    wrestlers_157, wrestlers_165, wrestlers_174, wrestlers_184,
    wrestlers_197, wrestlers_285
]

weights = [125, 133, 141, 149, 157, 165, 174, 184, 197, 285]

# Dictionary to store all results
all_weight_results = {}

# ============================================
# PREDICTION LOOP FOR BIG TEN
# ============================================

# Loop through each weight class
for weight_idx, (weight, wrestler_list) in enumerate(zip(weights, all_wrestler_list)):
    print("\n" + "="*100)
    print(f"🏋️  PROCESSING BIG TEN {weight}lbs WEIGHT CLASS ({weight_idx+1}/10)")
    print("="*100)

    # Display wrestlers in this weight class
    print(f"\n📋 {weight}lbs Wrestlers:")
    wrestlers_df = inference_pipeline_db[inference_pipeline_db['wrestler_name'].isin(wrestler_list)].copy()

    # Check if all wrestlers were found
    found_wrestlers = wrestlers_df['wrestler_name'].tolist()
    missing = [w for w in wrestler_list if w not in found_wrestlers]

    if missing:
        print(f"⚠️ Warning: {len(missing)} wrestlers not found in database:")
        for w in missing:
            print(f"   - {w}")
        # Remove missing wrestlers from the list
        wrestler_list = [w for w in wrestler_list if w in found_wrestlers]

    if len(wrestlers_df) == 0 or len(wrestler_list) < 2:
        print(f"❌ Not enough wrestlers found for {weight}lbs! Skipping...")
        continue

    print(wrestlers_df[['wrestler_name', 'team_name', 'rank', 'win_rate']].to_string(index=False))

    # Generate all matchup predictions for this weight class
    total_matchups = len(list(combinations(wrestler_list, 2)))
    print(f"\n🔄 Generating predictions for {total_matchups} matchups...")

    weight_predictions = []
    matchup_count = 0

    for w1, w2 in combinations(wrestler_list, 2):
        matchup_count += 1
        if matchup_count % 10 == 0 or matchup_count == total_matchups:
            print(f"   Progress: {matchup_count}/{total_matchups} matchups")

        # Get historical data
        hist_features = get_wrestler_match_history(w1, w2, matches_reference)

        # Prepare features - Penn State forced home for Big Ten
        features, home_name, away_name, home_data, away_data = prepare_matchup_features(
            w1, w2, hist_features, inference_pipeline_db, team_name="Penn State", weight_class=weight
        )

        # Make predictions
        results = predict_matchup(w1, w2, features, home_name, away_name)

        # Add weight class
        results['weight_class'] = weight
        weight_predictions.append(results)

    # Create dataframe for this weight class
    weight_df = pd.DataFrame(weight_predictions)

    # Add model agreement column
    weight_df['all_agree'] = (
        (weight_df['logreg_winner'] == weight_df['dt_winner']) &
        (weight_df['dt_winner'] == weight_df['xgb1_winner']) &
        (weight_df['xgb1_winner'] == weight_df['xgb2_winner'])
    )

    # Store results
    all_weight_results[weight] = weight_df

    # ============================================
    # DISPLAY ALL MATCHUPS WITH WINNER PROBABILITIES
    # ============================================
    print(f"\n📊 BIG TEN {weight}lbs - ALL MATCHUP PREDICTIONS")
    print("="*100)

    display_cols = [
        'home_wrestler', 'away_wrestler',
        'logreg_winner', 'logreg_prob',
        'dt_winner', 'dt_prob',
        'xgb1_winner', 'xgb1_prob',
        'xgb2_winner', 'xgb2_prob',
        'all_agree'
    ]

    display_df = weight_df[display_cols].copy()
    display_df.columns = [
        'Home', 'Away',
        'LR_Winner', 'LR_Conf',
        'DT_Winner', 'DT_Conf',
        'X1_Winner', 'X1_Conf',
        'X2_Winner', 'X2_Conf',
        'Agree'
    ]

    # Format confidence as percentage
    for col in ['LR_Conf', 'DT_Conf', 'X1_Conf', 'X2_Conf']:
        display_df[col] = (display_df[col] * 100).round(1).astype(str) + '%'

    # Show first 20 rows or all if less
    if len(display_df) > 20:
        print(display_df.head(20).to_string(index=False))
        print(f"... and {len(display_df) - 20} more matchups")
    else:
        print(display_df.to_string(index=False))

    # ============================================
    # QUICK SUMMARY STATS
    # ============================================
    print(f"\n📊 BIG TEN {weight}lbs - QUICK SUMMARY")
    print("-" * 60)

    # Agreement stats
    agreement_count = weight_df['all_agree'].sum()
    print(f"Total Matchups: {len(weight_df)}")
    print(f"All models agree: {agreement_count}/{len(weight_df)} ({agreement_count/len(weight_df)*100:.1f}%)")

    # Calculate average confidence
    weight_df['avg_confidence'] = (
        weight_df['logreg_prob'] +
        weight_df['dt_prob'] +
        weight_df['xgb1_prob'] +
        weight_df['xgb2_prob']
    ) / 4

    # Top 3 most confident predictions
    if len(weight_df) >= 3:
        top_confident = weight_df.nlargest(3, 'avg_confidence')[
            ['home_wrestler', 'away_wrestler', 'avg_confidence']
        ]
        print("\n🔝 Top 3 most confident predictions:")
        for _, row in top_confident.iterrows():
            print(f"   {row['home_wrestler']} vs {row['away_wrestler']}: {row['avg_confidence']*100:.1f}%")

    # Predicted champion by each model
    print("\n🏆 Predicted champions:")
    for model in ['logreg', 'dt', 'xgb1', 'xgb2']:
        if len(weight_df) > 0:
            champ_counts = weight_df[f'{model}_winner'].value_counts()
            if len(champ_counts) > 0:
                champ = champ_counts.index[0]
                champ_wins = champ_counts.values[0]
                champ_pct = (champ_wins / (len(wrestler_list) - 1)) * 100 if len(wrestler_list) > 1 else 0
                print(f"   {model.upper():6}: {champ} ({champ_wins}/{len(wrestler_list)-1} wins, {champ_pct:.1f}%)")

    # Check for unanimous champion
    champions = []
    for model in ['logreg', 'dt', 'xgb1', 'xgb2']:
        if len(weight_df) > 0:
            champ_counts = weight_df[f'{model}_winner'].value_counts()
            if len(champ_counts) > 0:
                champions.append(champ_counts.index[0])

    if len(champions) == 4 and all(c == champions[0] for c in champions):
        print(f"\n✅ UNANIMOUS CHAMPION: {champions[0]}")
    elif len(champions) > 0:
        print(f"\n⚠️ No unanimous champion")
        for model, champ in zip(['logreg', 'dt', 'xgb1', 'xgb2'], champions):
            print(f"   {model.upper():6}: {champ}")

    print("\n" + "="*60)

# ============================================
# OVERALL SUMMARY ACROSS ALL WEIGHT CLASSES
# ============================================
print("\n" + "="*100)
print("📊 BIG TEN OVERALL SUMMARY - ALL WEIGHT CLASSES")
print("="*100)

summary_rows = []
for weight in weights:
    if weight in all_weight_results:
        weight_df = all_weight_results[weight]

        # Agreement stats
        agreement_count = weight_df['all_agree'].sum()
        agreement_pct = agreement_count / len(weight_df) * 100 if len(weight_df) > 0 else 0

        # Champions by model
        logreg_champ = weight_df['logreg_winner'].value_counts().index[0] if len(weight_df) > 0 else "N/A"
        dt_champ = weight_df['dt_winner'].value_counts().index[0] if len(weight_df) > 0 else "N/A"
        xgb1_champ = weight_df['xgb1_winner'].value_counts().index[0] if len(weight_df) > 0 else "N/A"
        xgb2_champ = weight_df['xgb2_winner'].value_counts().index[0] if len(weight_df) > 0 else "N/A"

        # Check unanimous
        unanimous = (logreg_champ == dt_champ == xgb1_champ == xgb2_champ) and logreg_champ != "N/A"

        summary_rows.append({
            'Weight': f"{weight}lbs",
            'Matchups': len(weight_df),
            'Agreement': f"{agreement_pct:.1f}%",
            'LogReg Champ': logreg_champ[:15] + "..." if len(str(logreg_champ)) > 15 else str(logreg_champ),
            'DT Champ': dt_champ[:15] + "..." if len(str(dt_champ)) > 15 else str(dt_champ),
            'XGB1 Champ': xgb1_champ[:15] + "..." if len(str(xgb1_champ)) > 15 else str(xgb1_champ),
            'XGB2 Champ': xgb2_champ[:15] + "..." if len(str(xgb2_champ)) > 15 else str(xgb2_champ),
            'Unanimous': '✅' if unanimous else '❌'
        })

summary_df = pd.DataFrame(summary_rows)
print("\n", summary_df.to_string(index=False))

# ============================================
# SAVE MASTER SUMMARY
# ============================================
summary_df.to_csv('big_ten_all_weight_classes_summary.csv', index=False)
print("\n💾 Saved Big Ten master summary to big_ten_all_weight_classes_summary.csv")

# Combine all predictions into one master file
if len(all_weight_results) > 0:
    all_predictions_master = pd.concat(all_weight_results.values(), ignore_index=True)
    all_predictions_master.to_csv('big_ten_all_predictions_master.csv', index=False)
    print("💾 Saved all Big Ten predictions to big_ten_all_predictions_master.csv")

print("\n" + "="*100)
print("✅ BIG TEN ALL WEIGHT CLASS PREDICTIONS COMPLETE")
print("="*100)
print(f"Total weight classes processed: {len(all_weight_results)}")
print(f"Total matchups processed: {sum(len(df) for df in all_weight_results.values())}")

====================================================================================================
🏆 BIG TEN CONFERENCE - FULL PREDICTION LOOP
====================================================================================================

====================================================================================================
🏋️  PROCESSING BIG TEN 125lbs WEIGHT CLASS (1/10)
====================================================================================================

📋 125lbs Wrestlers:
  wrestler_name      team_name  rank  win_rate
    Ayden Smith        Rutgers    35      55.6
 Nicolar Rivera      Wisconsin    15      76.5
      Jore Volk      Minnesota    18      75.0
  Spencer Moore       Illinois    16      60.0
    Jacob Moran        Indiana    12      78.6
   Diego Sotelo       Michigan    39      50.0
  Dean Peterson           Iowa     8      71.4
 Luke Lilledahl     Penn State     1     100.0
    Nick Corday Michigan State    82      46.2
   Nic Bouzakis     Ohio State     2      90.9
    Abram Cline       Maryland   125      10.0
 Kael Lauridsen       Nebraska    47      30.0
Dedrick Navarro   Northwestern    38      60.0
 Ashton Jackson         Purdue    96      22.2

🔄 Generating predictions for 91 matchups...

📌 Home wrestler: Luke Lilledahl (Rank: 1, Team: Penn State)
📌 Away wrestler: Spencer Moore (Rank: 16, Team: Illinois)

📌 Home wrestler: Luke Lilledahl (Rank: 1, Team: Penn State)
📌 Away wrestler: Nic Bouzakis (Rank: 2, Team: Ohio State)

📌 Home wrestler: Luke Lilledahl (Rank: 1, Team: Penn State)
📌 Away wrestler: Jacob Moran (Rank: 12, Team: Indiana)

📌 Home wrestler: Luke Lilledahl (Rank: 1, Team: Penn State)
📌 Away wrestler: Jore Volk (Rank: 18, Team: Minnesota)

📌 Home wrestler: Luke Lilledahl (Rank: 1, Team: Penn State)
📌 Away wrestler: Ayden Smith (Rank: 35, Team: Rutgers)

📌 Home wrestler: Luke Lilledahl (Rank: 1, Team: Penn State)
📌 Away wrestler: Nicolar Rivera (Rank: 15, Team: Wisconsin)

📌 Home wrestler: Luke Lilledahl (Rank: 1, Team: Penn State)
📌 Away wrestler: Dean Peterson (Rank: 8, Team: Iowa)

📌 Home wrestler: Luke Lilledahl (Rank: 1, Team: Penn State)
📌 Away wrestler: Diego Sotelo (Rank: 39, Team: Michigan)

📌 Home wrestler: Luke Lilledahl (Rank: 1, Team: Penn State)
📌 Away wrestler: Dedrick Navarro (Rank: 38, Team: Northwestern)
   Progress: 10/91 matchups

📌 Home wrestler: Luke Lilledahl (Rank: 1, Team: Penn State)
📌 Away wrestler: Kael Lauridsen (Rank: 47, Team: Nebraska)

📌 Home wrestler: Luke Lilledahl (Rank: 1, Team: Penn State)
📌 Away wrestler: Nick Corday (Rank: 82, Team: Michigan State)

📌 Home wrestler: Luke Lilledahl (Rank: 1, Team: Penn State)
📌 Away wrestler: Ashton Jackson (Rank: 96, Team: Purdue)

📌 Home wrestler: Luke Lilledahl (Rank: 1, Team: Penn State)
📌 Away wrestler: Abram Cline (Rank: 125, Team: Maryland)

📌 Home wrestler: Nic Bouzakis (Rank: 2, Team: Ohio State)
📌 Away wrestler: Spencer Moore (Rank: 16, Team: Illinois)

📌 Home wrestler: Jacob Moran (Rank: 12, Team: Indiana)
📌 Away wrestler: Spencer Moore (Rank: 16, Team: Illinois)

📌 Home wrestler: Spencer Moore (Rank: 16, Team: Illinois)
📌 Away wrestler: Jore Volk (Rank: 18, Team: Minnesota)

📌 Home wrestler: Spencer Moore (Rank: 16, Team: Illinois)
📌 Away wrestler: Ayden Smith (Rank: 35, Team: Rutgers)

📌 Home wrestler: Nicolar Rivera (Rank: 15, Team: Wisconsin)
📌 Away wrestler: Spencer Moore (Rank: 16, Team: Illinois)

📌 Home wrestler: Dean Peterson (Rank: 8, Team: Iowa)
📌 Away wrestler: Spencer Moore (Rank: 16, Team: Illinois)
   Progress: 20/91 matchups

📌 Home wrestler: Spencer Moore (Rank: 16, Team: Illinois)
📌 Away wrestler: Diego Sotelo (Rank: 39, Team: Michigan)

📌 Home wrestler: Spencer Moore (Rank: 16, Team: Illinois)
📌 Away wrestler: Dedrick Navarro (Rank: 38, Team: Northwestern)

📌 Home wrestler: Spencer Moore (Rank: 16, Team: Illinois)
📌 Away wrestler: Kael Lauridsen (Rank: 47, Team: Nebraska)

📌 Home wrestler: Spencer Moore (Rank: 16, Team: Illinois)
📌 Away wrestler: Nick Corday (Rank: 82, Team: Michigan State)

📌 Home wrestler: Spencer Moore (Rank: 16, Team: Illinois)
📌 Away wrestler: Ashton Jackson (Rank: 96, Team: Purdue)

📌 Home wrestler: Spencer Moore (Rank: 16, Team: Illinois)
📌 Away wrestler: Abram Cline (Rank: 125, Team: Maryland)

📌 Home wrestler: Nic Bouzakis (Rank: 2, Team: Ohio State)
📌 Away wrestler: Jacob Moran (Rank: 12, Team: Indiana)

📌 Home wrestler: Nic Bouzakis (Rank: 2, Team: Ohio State)
📌 Away wrestler: Jore Volk (Rank: 18, Team: Minnesota)

📌 Home wrestler: Nic Bouzakis (Rank: 2, Team: Ohio State)
📌 Away wrestler: Ayden Smith (Rank: 35, Team: Rutgers)

📌 Home wrestler: Nic Bouzakis (Rank: 2, Team: Ohio State)
📌 Away wrestler: Nicolar Rivera (Rank: 15, Team: Wisconsin)
   Progress: 30/91 matchups

📌 Home wrestler: Nic Bouzakis (Rank: 2, Team: Ohio State)
📌 Away wrestler: Dean Peterson (Rank: 8, Team: Iowa)

📌 Home wrestler: Nic Bouzakis (Rank: 2, Team: Ohio State)
📌 Away wrestler: Diego Sotelo (Rank: 39, Team: Michigan)

📌 Home wrestler: Nic Bouzakis (Rank: 2, Team: Ohio State)
📌 Away wrestler: Dedrick Navarro (Rank: 38, Team: Northwestern)

📌 Home wrestler: Nic Bouzakis (Rank: 2, Team: Ohio State)
📌 Away wrestler: Kael Lauridsen (Rank: 47, Team: Nebraska)

📌 Home wrestler: Nic Bouzakis (Rank: 2, Team: Ohio State)
📌 Away wrestler: Nick Corday (Rank: 82, Team: Michigan State)

📌 Home wrestler: Nic Bouzakis (Rank: 2, Team: Ohio State)
📌 Away wrestler: Ashton Jackson (Rank: 96, Team: Purdue)

📌 Home wrestler: Nic Bouzakis (Rank: 2, Team: Ohio State)
📌 Away wrestler: Abram Cline (Rank: 125, Team: Maryland)

📌 Home wrestler: Jacob Moran (Rank: 12, Team: Indiana)
📌 Away wrestler: Jore Volk (Rank: 18, Team: Minnesota)

📌 Home wrestler: Jacob Moran (Rank: 12, Team: Indiana)
📌 Away wrestler: Ayden Smith (Rank: 35, Team: Rutgers)

📌 Home wrestler: Jacob Moran (Rank: 12, Team: Indiana)
📌 Away wrestler: Nicolar Rivera (Rank: 15, Team: Wisconsin)
   Progress: 40/91 matchups

📌 Home wrestler: Dean Peterson (Rank: 8, Team: Iowa)
📌 Away wrestler: Jacob Moran (Rank: 12, Team: Indiana)

📌 Home wrestler: Jacob Moran (Rank: 12, Team: Indiana)
📌 Away wrestler: Diego Sotelo (Rank: 39, Team: Michigan)

📌 Home wrestler: Jacob Moran (Rank: 12, Team: Indiana)
📌 Away wrestler: Dedrick Navarro (Rank: 38, Team: Northwestern)

📌 Home wrestler: Jacob Moran (Rank: 12, Team: Indiana)
📌 Away wrestler: Kael Lauridsen (Rank: 47, Team: Nebraska)

📌 Home wrestler: Jacob Moran (Rank: 12, Team: Indiana)
📌 Away wrestler: Nick Corday (Rank: 82, Team: Michigan State)

📌 Home wrestler: Jacob Moran (Rank: 12, Team: Indiana)
📌 Away wrestler: Ashton Jackson (Rank: 96, Team: Purdue)

📌 Home wrestler: Jacob Moran (Rank: 12, Team: Indiana)
📌 Away wrestler: Abram Cline (Rank: 125, Team: Maryland)

📌 Home wrestler: Jore Volk (Rank: 18, Team: Minnesota)
📌 Away wrestler: Ayden Smith (Rank: 35, Team: Rutgers)

📌 Home wrestler: Nicolar Rivera (Rank: 15, Team: Wisconsin)
📌 Away wrestler: Jore Volk (Rank: 18, Team: Minnesota)

📌 Home wrestler: Dean Peterson (Rank: 8, Team: Iowa)
📌 Away wrestler: Jore Volk (Rank: 18, Team: Minnesota)
   Progress: 50/91 matchups

📌 Home wrestler: Jore Volk (Rank: 18, Team: Minnesota)
📌 Away wrestler: Diego Sotelo (Rank: 39, Team: Michigan)

📌 Home wrestler: Jore Volk (Rank: 18, Team: Minnesota)
📌 Away wrestler: Dedrick Navarro (Rank: 38, Team: Northwestern)

📌 Home wrestler: Jore Volk (Rank: 18, Team: Minnesota)
📌 Away wrestler: Kael Lauridsen (Rank: 47, Team: Nebraska)

📌 Home wrestler: Jore Volk (Rank: 18, Team: Minnesota)
📌 Away wrestler: Nick Corday (Rank: 82, Team: Michigan State)

📌 Home wrestler: Jore Volk (Rank: 18, Team: Minnesota)
📌 Away wrestler: Ashton Jackson (Rank: 96, Team: Purdue)

📌 Home wrestler: Jore Volk (Rank: 18, Team: Minnesota)
📌 Away wrestler: Abram Cline (Rank: 125, Team: Maryland)

📌 Home wrestler: Nicolar Rivera (Rank: 15, Team: Wisconsin)
📌 Away wrestler: Ayden Smith (Rank: 35, Team: Rutgers)

📌 Home wrestler: Dean Peterson (Rank: 8, Team: Iowa)
📌 Away wrestler: Ayden Smith (Rank: 35, Team: Rutgers)

📌 Home wrestler: Ayden Smith (Rank: 35, Team: Rutgers)
📌 Away wrestler: Diego Sotelo (Rank: 39, Team: Michigan)

📌 Home wrestler: Ayden Smith (Rank: 35, Team: Rutgers)
📌 Away wrestler: Dedrick Navarro (Rank: 38, Team: Northwestern)
   Progress: 60/91 matchups

📌 Home wrestler: Ayden Smith (Rank: 35, Team: Rutgers)
📌 Away wrestler: Kael Lauridsen (Rank: 47, Team: Nebraska)

📌 Home wrestler: Ayden Smith (Rank: 35, Team: Rutgers)
📌 Away wrestler: Nick Corday (Rank: 82, Team: Michigan State)

📌 Home wrestler: Ayden Smith (Rank: 35, Team: Rutgers)
📌 Away wrestler: Ashton Jackson (Rank: 96, Team: Purdue)

📌 Home wrestler: Ayden Smith (Rank: 35, Team: Rutgers)
📌 Away wrestler: Abram Cline (Rank: 125, Team: Maryland)

📌 Home wrestler: Dean Peterson (Rank: 8, Team: Iowa)
📌 Away wrestler: Nicolar Rivera (Rank: 15, Team: Wisconsin)

📌 Home wrestler: Nicolar Rivera (Rank: 15, Team: Wisconsin)
📌 Away wrestler: Diego Sotelo (Rank: 39, Team: Michigan)

📌 Home wrestler: Nicolar Rivera (Rank: 15, Team: Wisconsin)
📌 Away wrestler: Dedrick Navarro (Rank: 38, Team: Northwestern)

📌 Home wrestler: Nicolar Rivera (Rank: 15, Team: Wisconsin)
📌 Away wrestler: Kael Lauridsen (Rank: 47, Team: Nebraska)

📌 Home wrestler: Nicolar Rivera (Rank: 15, Team: Wisconsin)
📌 Away wrestler: Nick Corday (Rank: 82, Team: Michigan State)

📌 Home wrestler: Nicolar Rivera (Rank: 15, Team: Wisconsin)
📌 Away wrestler: Ashton Jackson (Rank: 96, Team: Purdue)
   Progress: 70/91 matchups

📌 Home wrestler: Nicolar Rivera (Rank: 15, Team: Wisconsin)
📌 Away wrestler: Abram Cline (Rank: 125, Team: Maryland)

📌 Home wrestler: Dean Peterson (Rank: 8, Team: Iowa)
📌 Away wrestler: Diego Sotelo (Rank: 39, Team: Michigan)

📌 Home wrestler: Dean Peterson (Rank: 8, Team: Iowa)
📌 Away wrestler: Dedrick Navarro (Rank: 38, Team: Northwestern)

📌 Home wrestler: Dean Peterson (Rank: 8, Team: Iowa)
📌 Away wrestler: Kael Lauridsen (Rank: 47, Team: Nebraska)

📌 Home wrestler: Dean Peterson (Rank: 8, Team: Iowa)
📌 Away wrestler: Nick Corday (Rank: 82, Team: Michigan State)

📌 Home wrestler: Dean Peterson (Rank: 8, Team: Iowa)
📌 Away wrestler: Ashton Jackson (Rank: 96, Team: Purdue)

📌 Home wrestler: Dean Peterson (Rank: 8, Team: Iowa)
📌 Away wrestler: Abram Cline (Rank: 125, Team: Maryland)

📌 Home wrestler: Dedrick Navarro (Rank: 38, Team: Northwestern)
📌 Away wrestler: Diego Sotelo (Rank: 39, Team: Michigan)

📌 Home wrestler: Diego Sotelo (Rank: 39, Team: Michigan)
📌 Away wrestler: Kael Lauridsen (Rank: 47, Team: Nebraska)

📌 Home wrestler: Diego Sotelo (Rank: 39, Team: Michigan)
📌 Away wrestler: Nick Corday (Rank: 82, Team: Michigan State)
   Progress: 80/91 matchups

📌 Home wrestler: Diego Sotelo (Rank: 39, Team: Michigan)
📌 Away wrestler: Ashton Jackson (Rank: 96, Team: Purdue)

📌 Home wrestler: Diego Sotelo (Rank: 39, Team: Michigan)
📌 Away wrestler: Abram Cline (Rank: 125, Team: Maryland)

📌 Home wrestler: Dedrick Navarro (Rank: 38, Team: Northwestern)
📌 Away wrestler: Kael Lauridsen (Rank: 47, Team: Nebraska)

📌 Home wrestler: Dedrick Navarro (Rank: 38, Team: Northwestern)
📌 Away wrestler: Nick Corday (Rank: 82, Team: Michigan State)

📌 Home wrestler: Dedrick Navarro (Rank: 38, Team: Northwestern)
📌 Away wrestler: Ashton Jackson (Rank: 96, Team: Purdue)

📌 Home wrestler: Dedrick Navarro (Rank: 38, Team: Northwestern)
📌 Away wrestler: Abram Cline (Rank: 125, Team: Maryland)

📌 Home wrestler: Kael Lauridsen (Rank: 47, Team: Nebraska)
📌 Away wrestler: Nick Corday (Rank: 82, Team: Michigan State)

📌 Home wrestler: Kael Lauridsen (Rank: 47, Team: Nebraska)
📌 Away wrestler: Ashton Jackson (Rank: 96, Team: Purdue)

📌 Home wrestler: Kael Lauridsen (Rank: 47, Team: Nebraska)
📌 Away wrestler: Abram Cline (Rank: 125, Team: Maryland)

📌 Home wrestler: Nick Corday (Rank: 82, Team: Michigan State)
📌 Away wrestler: Ashton Jackson (Rank: 96, Team: Purdue)
   Progress: 90/91 matchups

📌 Home wrestler: Nick Corday (Rank: 82, Team: Michigan State)
📌 Away wrestler: Abram Cline (Rank: 125, Team: Maryland)
   Progress: 91/91 matchups

📌 Home wrestler: Ashton Jackson (Rank: 96, Team: Purdue)
📌 Away wrestler: Abram Cline (Rank: 125, Team: Maryland)

📊 BIG TEN 125lbs - ALL MATCHUP PREDICTIONS
====================================================================================================
          Home            Away      LR_Winner LR_Conf      DT_Winner DT_Conf      X1_Winner X1_Conf      X2_Winner X2_Conf  Agree
Luke Lilledahl   Spencer Moore Luke Lilledahl   70.7% Luke Lilledahl   74.6% Luke Lilledahl   80.1% Luke Lilledahl   81.0%   True
Luke Lilledahl    Nic Bouzakis Luke Lilledahl   55.2% Luke Lilledahl   61.1% Luke Lilledahl   61.7% Luke Lilledahl   53.2%   True
Luke Lilledahl     Jacob Moran Luke Lilledahl   61.7% Luke Lilledahl   74.6% Luke Lilledahl   65.8% Luke Lilledahl   88.6%   True
Luke Lilledahl       Jore Volk Luke Lilledahl   63.5% Luke Lilledahl   74.6% Luke Lilledahl   71.0% Luke Lilledahl   83.7%   True
Luke Lilledahl     Ayden Smith Luke Lilledahl   72.6% Luke Lilledahl   89.0% Luke Lilledahl   83.7% Luke Lilledahl   90.2%   True
Luke Lilledahl  Nicolar Rivera Luke Lilledahl   62.8% Luke Lilledahl   74.6% Luke Lilledahl   69.6% Luke Lilledahl   79.1%   True
Luke Lilledahl   Dean Peterson Luke Lilledahl   65.3% Luke Lilledahl   74.6% Luke Lilledahl   78.1% Luke Lilledahl   67.1%   True
Luke Lilledahl    Diego Sotelo Luke Lilledahl   75.0% Luke Lilledahl   74.6% Luke Lilledahl   81.9% Luke Lilledahl   75.3%   True
Luke Lilledahl Dedrick Navarro Luke Lilledahl   70.7% Luke Lilledahl   89.0% Luke Lilledahl   88.2% Luke Lilledahl   96.7%   True
Luke Lilledahl  Kael Lauridsen Luke Lilledahl   82.3% Luke Lilledahl   89.0% Luke Lilledahl   91.0% Luke Lilledahl   95.4%   True
Luke Lilledahl     Nick Corday Luke Lilledahl   76.5% Luke Lilledahl   89.0% Luke Lilledahl   88.3% Luke Lilledahl   96.2%   True
Luke Lilledahl  Ashton Jackson Luke Lilledahl   84.6% Luke Lilledahl   89.0% Luke Lilledahl   91.3% Luke Lilledahl   97.5%   True
Luke Lilledahl     Abram Cline Luke Lilledahl   87.8% Luke Lilledahl   89.0% Luke Lilledahl   87.9% Luke Lilledahl   96.6%   True
  Nic Bouzakis   Spencer Moore   Nic Bouzakis   66.4%   Nic Bouzakis   74.6%   Nic Bouzakis   77.8%   Nic Bouzakis   87.4%   True
   Jacob Moran   Spencer Moore    Jacob Moran   60.2%    Jacob Moran   74.6%    Jacob Moran   68.7%  Spencer Moore   59.9%  False
 Spencer Moore       Jore Volk      Jore Volk   57.8%      Jore Volk   53.1%      Jore Volk   55.6%  Spencer Moore   56.1%  False
 Spencer Moore     Ayden Smith  Spencer Moore   52.6%  Spencer Moore   61.1%  Spencer Moore   64.7%  Spencer Moore   73.8%   True
Nicolar Rivera   Spencer Moore Nicolar Rivera   59.1% Nicolar Rivera   61.1% Nicolar Rivera   61.3%  Spencer Moore   52.6%  False
 Dean Peterson   Spencer Moore  Dean Peterson   56.4%  Dean Peterson   61.1%  Dean Peterson   53.6%  Dean Peterson   70.7%   True
 Spencer Moore    Diego Sotelo  Spencer Moore   55.7%  Spencer Moore   61.1%  Spencer Moore   53.6%  Spencer Moore   54.8%   True
... and 71 more matchups

📊 BIG TEN 125lbs - QUICK SUMMARY
------------------------------------------------------------
Total Matchups: 91
All models agree: 77/91 (84.6%)

🔝 Top 3 most confident predictions:
   Nic Bouzakis vs Abram Cline: 90.8%
   Luke Lilledahl vs Ashton Jackson: 90.6%
   Luke Lilledahl vs Abram Cline: 90.3%

🏆 Predicted champions:
   LOGREG: Luke Lilledahl (13/13 wins, 100.0%)
   DT    : Luke Lilledahl (13/13 wins, 100.0%)
   XGB1  : Luke Lilledahl (13/13 wins, 100.0%)
   XGB2  : Luke Lilledahl (13/13 wins, 100.0%)

✅ UNANIMOUS CHAMPION: Luke Lilledahl

============================================================

====================================================================================================
🏋️  PROCESSING BIG TEN 133lbs WEIGHT CLASS (2/10)
====================================================================================================

📋 133lbs Wrestlers:
 wrestler_name      team_name  rank  win_rate
    Ben Davino     Ohio State     4      94.7
    Zan Fugitt      Wisconsin    12      76.5
 Dylan Shawver        Rutgers    35      64.7
    Lucas Byrd       Illinois     1     100.0
 Blake Boarman         Purdue    43      50.0
   Drake Ayala           Iowa    10      56.2
  Marcus Blaze     Penn State     3     100.0
 Jacob Van Dee       Nebraska    13      80.0
  Gauge Botero       Michigan    98      13.3
 Braxton Brown       Maryland    23      66.7
  Caleb Weiand Michigan State    51      36.4
   Sean Spidle   Northwestern    30      71.4
   Jager Eisch      Minnesota   125       0.0
Blaine Frazier        Indiana    93      25.0

🔄 Generating predictions for 91 matchups...

📌 Home wrestler: Marcus Blaze (Rank: 3, Team: Penn State)
📌 Away wrestler: Lucas Byrd (Rank: 1, Team: Illinois)

📌 Home wrestler: Marcus Blaze (Rank: 3, Team: Penn State)
📌 Away wrestler: Ben Davino (Rank: 4, Team: Ohio State)

📌 Home wrestler: Marcus Blaze (Rank: 3, Team: Penn State)
📌 Away wrestler: Zan Fugitt (Rank: 12, Team: Wisconsin)

📌 Home wrestler: Marcus Blaze (Rank: 3, Team: Penn State)
📌 Away wrestler: Drake Ayala (Rank: 10, Team: Iowa)

📌 Home wrestler: Marcus Blaze (Rank: 3, Team: Penn State)
📌 Away wrestler: Jacob Van Dee (Rank: 13, Team: Nebraska)

📌 Home wrestler: Marcus Blaze (Rank: 3, Team: Penn State)
📌 Away wrestler: Sean Spidle (Rank: 30, Team: Northwestern)

📌 Home wrestler: Marcus Blaze (Rank: 3, Team: Penn State)
📌 Away wrestler: Braxton Brown (Rank: 23, Team: Maryland)

📌 Home wrestler: Marcus Blaze (Rank: 3, Team: Penn State)
📌 Away wrestler: Dylan Shawver (Rank: 35, Team: Rutgers)

📌 Home wrestler: Marcus Blaze (Rank: 3, Team: Penn State)
📌 Away wrestler: Blake Boarman (Rank: 43, Team: Purdue)
   Progress: 10/91 matchups

📌 Home wrestler: Marcus Blaze (Rank: 3, Team: Penn State)
📌 Away wrestler: Caleb Weiand (Rank: 51, Team: Michigan State)

📌 Home wrestler: Marcus Blaze (Rank: 3, Team: Penn State)
📌 Away wrestler: Blaine Frazier (Rank: 93, Team: Indiana)

📌 Home wrestler: Marcus Blaze (Rank: 3, Team: Penn State)
📌 Away wrestler: Gauge Botero (Rank: 98, Team: Michigan)

📌 Home wrestler: Marcus Blaze (Rank: 3, Team: Penn State)
📌 Away wrestler: Jager Eisch (Rank: 125, Team: Minnesota)

📌 Home wrestler: Lucas Byrd (Rank: 1, Team: Illinois)
📌 Away wrestler: Ben Davino (Rank: 4, Team: Ohio State)

📌 Home wrestler: Lucas Byrd (Rank: 1, Team: Illinois)
📌 Away wrestler: Zan Fugitt (Rank: 12, Team: Wisconsin)

📌 Home wrestler: Lucas Byrd (Rank: 1, Team: Illinois)
📌 Away wrestler: Drake Ayala (Rank: 10, Team: Iowa)

📌 Home wrestler: Lucas Byrd (Rank: 1, Team: Illinois)
📌 Away wrestler: Jacob Van Dee (Rank: 13, Team: Nebraska)

📌 Home wrestler: Lucas Byrd (Rank: 1, Team: Illinois)
📌 Away wrestler: Sean Spidle (Rank: 30, Team: Northwestern)

📌 Home wrestler: Lucas Byrd (Rank: 1, Team: Illinois)
📌 Away wrestler: Braxton Brown (Rank: 23, Team: Maryland)
   Progress: 20/91 matchups

📌 Home wrestler: Lucas Byrd (Rank: 1, Team: Illinois)
📌 Away wrestler: Dylan Shawver (Rank: 35, Team: Rutgers)

📌 Home wrestler: Lucas Byrd (Rank: 1, Team: Illinois)
📌 Away wrestler: Blake Boarman (Rank: 43, Team: Purdue)

📌 Home wrestler: Lucas Byrd (Rank: 1, Team: Illinois)
📌 Away wrestler: Caleb Weiand (Rank: 51, Team: Michigan State)

📌 Home wrestler: Lucas Byrd (Rank: 1, Team: Illinois)
📌 Away wrestler: Blaine Frazier (Rank: 93, Team: Indiana)

📌 Home wrestler: Lucas Byrd (Rank: 1, Team: Illinois)
📌 Away wrestler: Gauge Botero (Rank: 98, Team: Michigan)

📌 Home wrestler: Lucas Byrd (Rank: 1, Team: Illinois)
📌 Away wrestler: Jager Eisch (Rank: 125, Team: Minnesota)

📌 Home wrestler: Ben Davino (Rank: 4, Team: Ohio State)
📌 Away wrestler: Zan Fugitt (Rank: 12, Team: Wisconsin)

📌 Home wrestler: Ben Davino (Rank: 4, Team: Ohio State)
📌 Away wrestler: Drake Ayala (Rank: 10, Team: Iowa)

📌 Home wrestler: Ben Davino (Rank: 4, Team: Ohio State)
📌 Away wrestler: Jacob Van Dee (Rank: 13, Team: Nebraska)


In [87]:
# ============================================
# FUNCTION TO FIND MISSING WRESTLERS
# ============================================

def find_missing_wrestlers(wrestler_lists, weight_classes, inference_db):
    """
    Identify which wrestlers from each weight class are missing from the inference database.

    Parameters:
    - wrestler_lists: list of lists containing wrestler names by weight class
    - weight_classes: list of weight class numbers
    - inference_db: the inference pipeline dataframe

    Returns:
    - missing_dict: dictionary with weight class as key and list of missing wrestlers as value
    - found_dict: dictionary with weight class as key and list of found wrestlers as value
    """

    print("\n" + "="*100)
    print("🔍 IDENTIFYING MISSING BIG TEN WRESTLERS")
    print("="*100)

    missing_dict = {}
    found_dict = {}
    all_missing = []

    for weight_idx, (weight, wrestler_list) in enumerate(zip(weight_classes, wrestler_lists)):
        print(f"\n📊 {weight}lbs - Checking {len(wrestler_list)} wrestlers...")

        # Find which wrestlers are in the database
        found = inference_db[inference_db['wrestler_name'].isin(wrestler_list)]['wrestler_name'].tolist()
        missing = [w for w in wrestler_list if w not in found]

        found_dict[weight] = found
        missing_dict[weight] = missing
        all_missing.extend(missing)

        # Print results for this weight class
        print(f"   ✅ Found: {len(found)}/{len(wrestler_list)} wrestlers")
        if missing:
            print(f"   ❌ Missing ({len(missing)}):")
            for w in missing:
                # Try to find similar names for suggestions
                similar = inference_db[inference_db['wrestler_name'].str.contains(w.split()[-1] if ' ' in w else w, na=False)]['wrestler_name'].tolist()
                print(f"      - {w}")
                if similar:
                    print(f"        → Similar names in DB: {similar[:3]}")

    print("\n" + "="*100)
    print(f"📋 SUMMARY: {len(all_missing)} total missing wrestlers across all weight classes")
    print("="*100)

    return missing_dict, found_dict


# ============================================
# FUNCTION TO SUGGEST CORRECTIONS
# ============================================

def suggest_name_corrections(missing_dict, inference_db):
    """
    Suggest possible corrections for missing wrestler names.
    """
    print("\n💡 NAME CORRECTION SUGGESTIONS:")
    print("-" * 60)

    all_suggestions = {}

    for weight, missing_list in missing_dict.items():
        if not missing_list:
            continue

        print(f"\n{weight}lbs:")
        weight_suggestions = {}

        for missing_name in missing_list:
            # Split name to get last name
            parts = missing_name.split()
            if len(parts) > 1:
                last_name = parts[-1]
                # Find similar last names in database
                similar = inference_db[inference_db['wrestler_name'].str.contains(last_name, case=False, na=False)]
                if len(similar) > 0:
                    suggestions = similar['wrestler_name'].tolist()
                    weight_suggestions[missing_name] = suggestions
                    print(f"   '{missing_name}' → maybe: {suggestions}")
                else:
                    print(f"   '{missing_name}' → no close matches found")
            else:
                print(f"   '{missing_name}' → single name, can't parse last name")

        all_suggestions[weight] = weight_suggestions

    return all_suggestions


# ============================================
# RUN THE ANALYSIS
# ============================================

# Your Big Ten wrestler lists
big_ten_lists = [
    wrestlers_125, wrestlers_133, wrestlers_141, wrestlers_149,
    wrestlers_157, wrestlers_165, wrestlers_174, wrestlers_184,
    wrestlers_197, wrestlers_285
]
weight_classes = [125, 133, 141, 149, 157, 165, 174, 184, 197, 285]

# Find missing wrestlers
missing_dict, found_dict = find_missing_wrestlers(big_ten_lists, weight_classes, inference_pipeline_db)

# Get correction suggestions
suggestions = suggest_name_corrections(missing_dict, inference_pipeline_db)

# ============================================
# CREATE UPDATED LISTS (optional)
# ============================================

print("\n" + "="*100)
print("📝 UPDATED WRESTLER LISTS (with only found wrestlers)")
print("="*100)

updated_lists = []
for weight in weight_classes:
    updated_list = found_dict[weight]
    updated_lists.append(updated_list)
    print(f"\n{weight}lbs ({len(updated_list)} wrestlers):")
    for w in updated_list:
        print(f"   - {w}")

# ============================================
# CHECK SPECIFIC NAMES THAT MIGHT BE PROBLEMATIC
# ============================================

print("\n" + "="*100)
print("🔎 CHECKING SPECIFIC NAME PATTERNS")
print("="*100)

# Common naming issues to check
problematic_patterns = [
    "Luke Lilledahl",  # Might be "Lilledahl, Luke" format
    "PJ Duke",         # Might have period after PJ
    "AJ Ferrari",      # Might have period after AJ
    "Joey Buttler",    # Might be misspelled
    "Jager Eisch",     # Uncommon name
]

for name in problematic_patterns:
    print(f"\nChecking '{name}':")

    # Exact match
    exact = inference_pipeline_db[inference_pipeline_db['wrestler_name'] == name]
    if len(exact) > 0:
        print(f"   ✅ Found exact match!")
        continue

    # Try contains
    parts = name.split()
    if len(parts) > 1:
        last_name = parts[-1]
        contains = inference_pipeline_db[inference_pipeline_db['wrestler_name'].str.contains(last_name, case=False, na=False)]
        if len(contains) > 0:
            print(f"   🔍 Found by last name '{last_name}':")
            for n in contains['wrestler_name'].head(5).tolist():
                print(f"      - {n}")
        else:
            print(f"   ❌ No matches found for last name '{last_name}'")

====================================================================================================
🔍 IDENTIFYING MISSING BIG TEN WRESTLERS
====================================================================================================

📊 125lbs - Checking 14 wrestlers...
   ✅ Found: 14/14 wrestlers

📊 133lbs - Checking 14 wrestlers...
   ✅ Found: 14/14 wrestlers

📊 141lbs - Checking 14 wrestlers...
   ✅ Found: 14/14 wrestlers

📊 149lbs - Checking 14 wrestlers...
   ✅ Found: 14/14 wrestlers

📊 157lbs - Checking 14 wrestlers...
   ✅ Found: 14/14 wrestlers

📊 165lbs - Checking 14 wrestlers...
   ✅ Found: 14/14 wrestlers

📊 174lbs - Checking 14 wrestlers...
   ✅ Found: 14/14 wrestlers

📊 184lbs - Checking 14 wrestlers...
   ✅ Found: 14/14 wrestlers

📊 197lbs - Checking 14 wrestlers...
   ✅ Found: 14/14 wrestlers

📊 285lbs - Checking 14 wrestlers...
   ✅ Found: 14/14 wrestlers

====================================================================================================
📋 SUMMARY: 0 total missing wrestlers across all weight classes
====================================================================================================

💡 NAME CORRECTION SUGGESTIONS:
------------------------------------------------------------

====================================================================================================
📝 UPDATED WRESTLER LISTS (with only found wrestlers)
====================================================================================================

125lbs (14 wrestlers):
   - Ayden Smith
   - Nicolar Rivera
   - Jore Volk
   - Spencer Moore
   - Jacob Moran
   - Diego Sotelo
   - Dean Peterson
   - Luke Lilledahl
   - Nick Corday
   - Nic Bouzakis
   - Abram Cline
   - Kael Lauridsen
   - Dedrick Navarro
   - Ashton Jackson

133lbs (14 wrestlers):
   - Ben Davino
   - Zan Fugitt
   - Dylan Shawver
   - Lucas Byrd
   - Blake Boarman
   - Drake Ayala
   - Marcus Blaze
   - Jacob Van Dee
   - Gauge Botero
   - Braxton Brown
   - Caleb Weiand
   - Sean Spidle
   - Jager Eisch
   - Blaine Frazier

141lbs (14 wrestlers):
   - Jesse Mendez
   - Brock Hardy
   - Vance Vombaur
   - Carson Exferd
   - Henry Porter
   - Nasir Bailey
   - Dario Lemus
   - Greyson Clark
   - Billy Dekraker
   - Dylan Ragusin
   - Braeden Davis
   - Joey Olivieri
   - Danny Pucino
   - Jaden Crumpler

149lbs (14 wrestlers):
   - Joseph Zargo
   - Gavin Brown
   - Andrew Clark
   - Ryder Block
   - Shayne Van Ness
   - Joey Buttler
   - Lachlan McNeil
   - Ethan Stiles
   - Drew Roberts
   - Chance Lamer
   - August Hibler
   - Clayton Jones
   - Carter Young
   - Michael Gioffre

157lbs (14 wrestlers):
   - Antrell Taylor
   - Luke Mechler
   - Anthony White
   - Cam Catrabone
   - Charlie Millard
   - Darius Marines
   - Bryce Lowery
   - Kannon Webster
   - PJ Duke
   - Brandon Cannon
   - Stoney Buell
   - Mekhi Neal
   - Victor Voinovich
   - Ty Wilson

165lbs (14 wrestlers):
   - Michael Caliendo
   - Braeden Scoles
   - Cody Goebel
   - LJ Araujo
   - Andrew Sparks
   - Tyler Lillard
   - Mitchell Mesenbrink
   - Paddy Gallagher
   - Joey Blaze
   - AJ Rodriguez
   - Andrew Barbosa
   - Justin Gates
   - Jacob Bostelman
   - Jack Conley

174lbs (14 wrestlers):
   - Christopher Minto
   - Lucas Condon
   - Carson Kharchla
   - Patrick Kennedy
   - Colin Kelly
   - Beau Mantanona
   - Ethan Riddle
   - Levi Haines
   - Connor O'Neill
   - Lenny Pinto
   - Seth Digby
   - Brody Baumann
   - Derek Gilcher
   - Eddie Enright

184lbs (14 wrestlers):
   - Shane Cartagena-Walsh
   - Silas Allred
   - Dylan Fishback
   - James Rowley
   - Chris Moore
   - Max McEnelly
   - Rocco Welsh
   - Brock Mantanona
   - Sam Goin
   - Jesse Perez
   - Cale Anderson
   - Angelo Ferrari
   - Sepanta Ahanj-Elias
   - Ryan Boucher

197lbs (14 wrestlers):
   - Camden McDanel
   - Wyatt Ingham
   - Hayden Walters
   - Gabe Sollars
   - Gavin Nelson
   - Remy Cotton
   - Luke Geog
   - Branson John
   - Kael Wisler
   - Ben Vanadia
   - Alex Smith
   - Gabe Arnold
   - Josh Barr
   - Dylan Connell

285lbs (14 wrestlers):
   - Braxton Amos
   - Nick Feldman
   - Hunter Catka
   - Hayden Filipovich
   - Cole Mirasola
   - AJ Ferrari
   - Taye Ghadiali
   - Koy Hopke
   - Gabe Christenson
   - Luke Luffman
   - Caleb Marzolino
   - Ben Kueter
   - Josh Terrill
   - Joey Schneck

====================================================================================================
🔎 CHECKING SPECIFIC NAME PATTERNS
====================================================================================================

Checking 'Luke Lilledahl':
   ✅ Found exact match!

Checking 'PJ Duke':
   ✅ Found exact match!

Checking 'AJ Ferrari':
   ✅ Found exact match!

Checking 'Joey Buttler':
   ✅ Found exact match!

Checking 'Jager Eisch':
   ✅ Found exact match!

In [88]:
# ============================================
# FUNCTION TO FIND MISSING IVY LEAGUE WRESTLERS
# ============================================

def find_missing_ivy_wrestlers(wrestler_lists, weight_classes, inference_db):
    """
    Identify which Ivy League wrestlers from each weight class are missing from the inference database.

    Parameters:
    - wrestler_lists: list of lists containing wrestler names by weight class
    - weight_classes: list of weight class numbers
    - inference_db: the inference pipeline dataframe

    Returns:
    - missing_dict: dictionary with weight class as key and list of missing wrestlers as value
    - found_dict: dictionary with weight class as key and list of found wrestlers as value
    """

    print("\n" + "="*100)
    print("🔍 IDENTIFYING MISSING IVY LEAGUE WRESTLERS")
    print("="*100)

    missing_dict = {}
    found_dict = {}
    all_missing = []

    for weight_idx, (weight, wrestler_list) in enumerate(zip(weight_classes, wrestler_lists)):
        print(f"\n📊 {weight}lbs - Checking {len(wrestler_list)} wrestlers...")

        # Find which wrestlers are in the database
        found = inference_db[inference_db['wrestler_name'].isin(wrestler_list)]['wrestler_name'].tolist()
        missing = [w for w in wrestler_list if w not in found]

        found_dict[weight] = found
        missing_dict[weight] = missing
        all_missing.extend(missing)

        # Print results for this weight class
        print(f"   ✅ Found: {len(found)}/{len(wrestler_list)} wrestlers")
        if found:
            print(f"   📋 Found wrestlers:")
            for w in found:
                # Get their data
                wrestler_data = inference_db[inference_db['wrestler_name'] == w].iloc[0]
                print(f"      - {w} (Rank: {wrestler_data['rank']}, Team: {wrestler_data['team_name']})")

        if missing:
            print(f"   ❌ Missing ({len(missing)}):")
            for w in missing:
                # Try to find similar names for suggestions
                similar = inference_db[inference_db['wrestler_name'].str.contains(w.split()[-1] if ' ' in w else w, case=False, na=False)]['wrestler_name'].tolist()
                print(f"      - {w}")
                if similar:
                    print(f"        → Similar names in DB: {similar[:3]}")

    print("\n" + "="*100)
    print(f"📋 SUMMARY: {len(all_missing)} total missing wrestlers across all weight classes")
    print("="*100)

    return missing_dict, found_dict


# ============================================
# FUNCTION TO SUGGEST CORRECTIONS FOR IVY LEAGUE
# ============================================

def suggest_ivy_name_corrections(missing_dict, inference_db):
    """
    Suggest possible corrections for missing Ivy League wrestler names.
    """
    print("\n💡 IVY LEAGUE NAME CORRECTION SUGGESTIONS:")
    print("-" * 60)

    all_suggestions = {}

    for weight, missing_list in missing_dict.items():
        if not missing_list:
            continue

        print(f"\n{weight}lbs:")
        weight_suggestions = {}

        for missing_name in missing_list:
            # Split name to get last name
            parts = missing_name.split()
            if len(parts) > 1:
                last_name = parts[-1]
                # Find similar last names in database
                similar = inference_db[inference_db['wrestler_name'].str.contains(last_name, case=False, na=False)]
                if len(similar) > 0:
                    suggestions = similar['wrestler_name'].tolist()
                    weight_suggestions[missing_name] = suggestions
                    print(f"   '{missing_name}' → maybe: {suggestions}")
                else:
                    print(f"   '{missing_name}' → no close matches found")
            else:
                print(f"   '{missing_name}' → single name, can't parse last name")

        all_suggestions[weight] = weight_suggestions

    return all_suggestions


# ============================================
# IVY LEAGUE WRESTLER LISTS
# ============================================

ivy_wrestlers_125 = ["Davis Motyka", "Greg Diakomihalis", "Logan Brzozowski", "Sulayman Bah", "Chase Yasutake", "Marc-Anthony McGowan"]

ivy_wrestlers_133 = ["Evan Mougalian", "Ethan Rivera", "Coleman Nogle", "Evin Gursoy", "Douglas Shipers", "Tyler Ferrera"]

ivy_wrestlers_141 = ["Vince Cornella", "Matthew Martino", "Lorenzo Frezza", "Khimari Manns", "Dante Frinzi", "CJ Composto"]

ivy_wrestlers_149 = ["Jaxon Joy", "Richard Fedalen", "Jack Crook", "Eligh Rivera", "Austin McBurney", "Cross Wasilewski"]

ivy_wrestlers_157 = ["Meyer Shapiro", "Ethan Mojena", "Kai Owen", "Jimmy Harrington", "Rocco Camillaci", "Jude Swisher"]

ivy_wrestlers_165 = ["Cesar Alvan", "Joseph Cangro", "Maximus Norman", "Sean Seefeldt", "Benny Rogers", "Ty Whalen"]

ivy_wrestlers_174 = ["Simon Ruiz", "Haden Bottiglieri", "Caden Bellis", "Holden Garcia", "Drew Clearie", "Nick Fine"]

ivy_wrestlers_184 = ["Joe Curtis", "Xavier Giles", "Matthew Walsh", "Liam Carlin", "Connor O'Donnell", "Louis Cerchio"]

ivy_wrestlers_197 = ["Andrew Reall", "Aiden Hanning", "Hudson Skove", "Martin Cosgrove", "Conor McCloskey", "Jack Wehmeyer"]

ivy_wrestlers_285 = ["Vincent Mueller", "Sebastian Garibaldi", "Ashton Davis", "John Pardo", "Daniel Bittner", "Alex Semenenko"]

# ============================================
# COMBINE INTO MASTER LIST
# ============================================

ivy_all_wrestler_list = [
    ivy_wrestlers_125, ivy_wrestlers_133, ivy_wrestlers_141, ivy_wrestlers_149,
    ivy_wrestlers_157, ivy_wrestlers_165, ivy_wrestlers_174, ivy_wrestlers_184,
    ivy_wrestlers_197, ivy_wrestlers_285
]

ivy_weights = [125, 133, 141, 149, 157, 165, 174, 184, 197, 285]

# ============================================
# RUN THE ANALYSIS FOR IVY LEAGUE
# ============================================

print("\n" + "="*100)
print("🏆 IVY LEAGUE WRESTLER VERIFICATION")
print("="*100)

# Find missing wrestlers
ivy_missing_dict, ivy_found_dict = find_missing_ivy_wrestlers(
    ivy_all_wrestler_list, ivy_weights, inference_pipeline_db
)

# Get correction suggestions
ivy_suggestions = suggest_ivy_name_corrections(ivy_missing_dict, inference_pipeline_db)

# ============================================
# CREATE UPDATED IVY LEAGUE LISTS
# ============================================

print("\n" + "="*100)
print("📝 UPDATED IVY LEAGUE WRESTLER LISTS (with only found wrestlers)")
print("="*100)

ivy_updated_lists = []
for weight in ivy_weights:
    updated_list = ivy_found_dict[weight]
    ivy_updated_lists.append(updated_list)
    print(f"\n{weight}lbs ({len(updated_list)} wrestlers):")
    for w in updated_list:
        wrestler_data = inference_pipeline_db[inference_pipeline_db['wrestler_name'] == w].iloc[0]
        print(f"   - {w} (Rank: {wrestler_data['rank']}, Team: {wrestler_data['team_name']})")

# ============================================
# SUMMARY TABLE
# ============================================

print("\n" + "="*100)
print("📊 IVY LEAGUE WRESTLER SUMMARY TABLE")
print("="*100)

summary_data = []
for weight in ivy_weights:
    original_count = len(ivy_all_wrestler_list[ivy_weights.index(weight)])
    found_count = len(ivy_found_dict[weight])
    missing_count = original_count - found_count

    summary_data.append({
        'Weight': f"{weight}lbs",
        'Original': original_count,
        'Found': found_count,
        'Missing': missing_count,
        'Status': '✅ COMPLETE' if missing_count == 0 else f'⚠️ MISSING {missing_count}'
    })

summary_df = pd.DataFrame(summary_data)
print("\n", summary_df.to_string(index=False))

# ============================================
# CHECK SPECIFIC IVY LEAGUE NAMES
# ============================================

print("\n" + "="*100)
print("🔎 CHECKING SPECIFIC IVY LEAGUE NAME PATTERNS")
print("="*100)

# Common Ivy League naming issues to check
ivy_problematic = [
    "Marc-Anthony McGowan",  # Has hyphen
    "CJ Composto",           # Initials
    "AShton Davis",          # Capitalization issue
    "Haden Bottiglieri",     # Uncommon name
    "Louis Cerchio",         # Uncommon name
    "Khimari Manns",         # Uncommon name
]

for name in ivy_problematic:
    print(f"\nChecking '{name}':")

    # Exact match
    exact = inference_pipeline_db[inference_pipeline_db['wrestler_name'] == name]
    if len(exact) > 0:
        data = exact.iloc[0]
        print(f"   ✅ Found: {data['wrestler_name']} (Rank: {data['rank']}, Team: {data['team_name']})")
        continue

    # Try contains (case insensitive)
    parts = name.split()
    if len(parts) > 1:
        last_name = parts[-1].replace('-', ' ')  # Handle hyphenated names
        contains = inference_pipeline_db[inference_pipeline_db['wrestler_name'].str.contains(last_name, case=False, na=False)]
        if len(contains) > 0:
            print(f"   🔍 Found by last name '{last_name}':")
            for _, row in contains.head(3).iterrows():
                print(f"      - {row['wrestler_name']} (Rank: {row['rank']}, Team: {row['team_name']})")
        else:
            # Try first name
            first_name = parts[0]
            contains_first = inference_pipeline_db[inference_pipeline_db['wrestler_name'].str.contains(first_name, case=False, na=False)]
            if len(contains_first) > 0:
                print(f"   🔍 Found by first name '{first_name}':")
                for _, row in contains_first.head(3).iterrows():
                    print(f"      - {row['wrestler_name']} (Rank: {row['rank']}, Team: {row['team_name']})")
            else:
                print(f"   ❌ No matches found")
    else:
        print(f"   ❌ Single name, can't parse")

print("\n" + "="*100)
print("✅ IVY LEAGUE WRESTLER VERIFICATION COMPLETE")
print("="*100)

====================================================================================================
🏆 IVY LEAGUE WRESTLER VERIFICATION
====================================================================================================

====================================================================================================
🔍 IDENTIFYING MISSING IVY LEAGUE WRESTLERS
====================================================================================================

📊 125lbs - Checking 6 wrestlers...
   ✅ Found: 6/6 wrestlers
   📋 Found wrestlers:
      - Sulayman Bah (Rank: 23, Team: Columbia)
      - Logan Brzozowski (Rank: 45, Team: Harvard)
      - Chase Yasutake (Rank: 230, Team: Brown)
      - Marc-Anthony McGowan (Rank: 13, Team: Princeton)
      - Greg Diakomihalis (Rank: 50, Team: Cornell)
      - Davis Motyka (Rank: 37, Team: Pennsylvania)

📊 133lbs - Checking 6 wrestlers...
   ✅ Found: 6/6 wrestlers
   📋 Found wrestlers:
      - Douglas Shipers (Rank: 254, Team: Brown)
      - Evin Gursoy (Rank: 68, Team: Columbia)
      - Coleman Nogle (Rank: 72, Team: Harvard)
      - Tyler Ferrera (Rank: 18, Team: Cornell)
      - Evan Mougalian (Rank: 16, Team: Pennsylvania)
      - Ethan Rivera (Rank: 45, Team: Princeton)

📊 141lbs - Checking 6 wrestlers...
   ✅ Found: 6/6 wrestlers
   📋 Found wrestlers:
      - Vince Cornella (Rank: 6, Team: Cornell)
      - Matthew Martino (Rank: 28, Team: Princeton)
      - Lorenzo Frezza (Rank: 46, Team: Columbia)
      - Khimari Manns (Rank: 67, Team: Brown)
      - Dante Frinzi (Rank: 133, Team: Harvard)
      - CJ Composto (Rank: 10, Team: Pennsylvania)

📊 149lbs - Checking 6 wrestlers...
   ✅ Found: 6/6 wrestlers
   📋 Found wrestlers:
      - Jaxon Joy (Rank: 3, Team: Cornell)
      - Austin McBurney (Rank: 81, Team: Brown)
      - Eligh Rivera (Rank: 22, Team: Princeton)
      - Richard Fedalen (Rank: 69, Team: Columbia)
      - Jack Crook (Rank: 60, Team: Harvard)
      - Cross Wasilewski (Rank: 8, Team: Pennsylvania)

📊 157lbs - Checking 6 wrestlers...
   ✅ Found: 6/6 wrestlers
   📋 Found wrestlers:
      - Meyer Shapiro (Rank: 1, Team: Cornell)
      - Ethan Mojena (Rank: 88, Team: Brown)
      - Jimmy Harrington (Rank: 16, Team: Harvard)
      - Kai Owen (Rank: 34, Team: Columbia)
      - Jude Swisher (Rank: 12, Team: Pennsylvania)
      - Rocco Camillaci (Rank: 87, Team: Princeton)

📊 165lbs - Checking 6 wrestlers...
   ✅ Found: 6/6 wrestlers
   📋 Found wrestlers:
      - Ty Whalen (Rank: 18, Team: Princeton)
      - Cesar Alvan (Rank: 20, Team: Columbia)
      - Maximus Norman (Rank: 48, Team: Brown)
      - Joseph Cangro (Rank: 77, Team: Harvard)
      - Sean Seefeldt (Rank: 30, Team: Pennsylvania)
      - Benny Rogers (Rank: 66, Team: Cornell)

📊 174lbs - Checking 6 wrestlers...
   ✅ Found: 6/6 wrestlers
   📋 Found wrestlers:
      - Simon Ruiz (Rank: 2, Team: Cornell)
      - Nick Fine (Rank: 22, Team: Columbia)
      - Drew Clearie (Rank: 102, Team: Brown)
      - Holden Garcia (Rank: 29, Team: Princeton)
      - Caden Bellis (Rank: 66, Team: Pennsylvania)
      - Haden Bottiglieri (Rank: 82, Team: Harvard)

📊 184lbs - Checking 6 wrestlers...
   ✅ Found: 6/6 wrestlers
   📋 Found wrestlers:
      - Louis Cerchio (Rank: 50, Team: Cornell)
      - Xavier Giles (Rank: 73, Team: Princeton)
      - Matthew Walsh (Rank: 81, Team: Harvard)
      - Connor O'Donnell (Rank: 155, Team: Brown)
      - Liam Carlin (Rank: 58, Team: Pennsylvania)
      - Joe Curtis (Rank: 19, Team: Columbia)

📊 197lbs - Checking 6 wrestlers...
   ✅ Found: 6/6 wrestlers
   📋 Found wrestlers:
      - Conor McCloskey (Rank: 148, Team: Princeton)
      - Andrew Reall (Rank: 18, Team: Brown)
      - Jack Wehmeyer (Rank: 42, Team: Columbia)
      - Martin Cosgrove (Rank: 80, Team: Pennsylvania)
      - Hudson Skove (Rank: 117, Team: Harvard)
      - Aiden Hanning (Rank: 87, Team: Cornell)

📊 285lbs - Checking 6 wrestlers...
   ✅ Found: 6/6 wrestlers
   📋 Found wrestlers:
      - Alex Semenenko (Rank: 22, Team: Brown)
      - Vincent Mueller (Rank: 26, Team: Columbia)
      - John Pardo (Rank: 85, Team: Pennsylvania)
      - Sebastian Garibaldi (Rank: 121, Team: Princeton)
      - Ashton Davis (Rank: 48, Team: Cornell)
      - Daniel Bittner (Rank: 174, Team: Harvard)

====================================================================================================
📋 SUMMARY: 0 total missing wrestlers across all weight classes
====================================================================================================

💡 IVY LEAGUE NAME CORRECTION SUGGESTIONS:
------------------------------------------------------------

====================================================================================================
📝 UPDATED IVY LEAGUE WRESTLER LISTS (with only found wrestlers)
====================================================================================================

125lbs (6 wrestlers):
   - Sulayman Bah (Rank: 23, Team: Columbia)
   - Logan Brzozowski (Rank: 45, Team: Harvard)
   - Chase Yasutake (Rank: 230, Team: Brown)
   - Marc-Anthony McGowan (Rank: 13, Team: Princeton)
   - Greg Diakomihalis (Rank: 50, Team: Cornell)
   - Davis Motyka (Rank: 37, Team: Pennsylvania)

133lbs (6 wrestlers):
   - Douglas Shipers (Rank: 254, Team: Brown)
   - Evin Gursoy (Rank: 68, Team: Columbia)
   - Coleman Nogle (Rank: 72, Team: Harvard)
   - Tyler Ferrera (Rank: 18, Team: Cornell)
   - Evan Mougalian (Rank: 16, Team: Pennsylvania)
   - Ethan Rivera (Rank: 45, Team: Princeton)

141lbs (6 wrestlers):
   - Vince Cornella (Rank: 6, Team: Cornell)
   - Matthew Martino (Rank: 28, Team: Princeton)
   - Lorenzo Frezza (Rank: 46, Team: Columbia)
   - Khimari Manns (Rank: 67, Team: Brown)
   - Dante Frinzi (Rank: 133, Team: Harvard)
   - CJ Composto (Rank: 10, Team: Pennsylvania)

149lbs (6 wrestlers):
   - Jaxon Joy (Rank: 3, Team: Cornell)
   - Austin McBurney (Rank: 81, Team: Brown)
   - Eligh Rivera (Rank: 22, Team: Princeton)
   - Richard Fedalen (Rank: 69, Team: Columbia)
   - Jack Crook (Rank: 60, Team: Harvard)
   - Cross Wasilewski (Rank: 8, Team: Pennsylvania)

157lbs (6 wrestlers):
   - Meyer Shapiro (Rank: 1, Team: Cornell)
   - Ethan Mojena (Rank: 88, Team: Brown)
   - Jimmy Harrington (Rank: 16, Team: Harvard)
   - Kai Owen (Rank: 34, Team: Columbia)
   - Jude Swisher (Rank: 12, Team: Pennsylvania)
   - Rocco Camillaci (Rank: 87, Team: Princeton)

165lbs (6 wrestlers):
   - Ty Whalen (Rank: 18, Team: Princeton)
   - Cesar Alvan (Rank: 20, Team: Columbia)
   - Maximus Norman (Rank: 48, Team: Brown)
   - Joseph Cangro (Rank: 77, Team: Harvard)
   - Sean Seefeldt (Rank: 30, Team: Pennsylvania)
   - Benny Rogers (Rank: 66, Team: Cornell)

174lbs (6 wrestlers):
   - Simon Ruiz (Rank: 2, Team: Cornell)
   - Nick Fine (Rank: 22, Team: Columbia)
   - Drew Clearie (Rank: 102, Team: Brown)
   - Holden Garcia (Rank: 29, Team: Princeton)
   - Caden Bellis (Rank: 66, Team: Pennsylvania)
   - Haden Bottiglieri (Rank: 82, Team: Harvard)

184lbs (6 wrestlers):
   - Louis Cerchio (Rank: 50, Team: Cornell)
   - Xavier Giles (Rank: 73, Team: Princeton)
   - Matthew Walsh (Rank: 81, Team: Harvard)
   - Connor O'Donnell (Rank: 155, Team: Brown)
   - Liam Carlin (Rank: 58, Team: Pennsylvania)
   - Joe Curtis (Rank: 19, Team: Columbia)

197lbs (6 wrestlers):
   - Conor McCloskey (Rank: 148, Team: Princeton)
   - Andrew Reall (Rank: 18, Team: Brown)
   - Jack Wehmeyer (Rank: 42, Team: Columbia)
   - Martin Cosgrove (Rank: 80, Team: Pennsylvania)
   - Hudson Skove (Rank: 117, Team: Harvard)
   - Aiden Hanning (Rank: 87, Team: Cornell)

285lbs (6 wrestlers):
   - Alex Semenenko (Rank: 22, Team: Brown)
   - Vincent Mueller (Rank: 26, Team: Columbia)
   - John Pardo (Rank: 85, Team: Pennsylvania)
   - Sebastian Garibaldi (Rank: 121, Team: Princeton)
   - Ashton Davis (Rank: 48, Team: Cornell)
   - Daniel Bittner (Rank: 174, Team: Harvard)

====================================================================================================
📊 IVY LEAGUE WRESTLER SUMMARY TABLE
====================================================================================================

 Weight  Original  Found  Missing     Status
125lbs         6      6        0 ✅ COMPLETE
133lbs         6      6        0 ✅ COMPLETE
141lbs         6      6        0 ✅ COMPLETE
149lbs         6      6        0 ✅ COMPLETE
157lbs         6      6        0 ✅ COMPLETE
165lbs         6      6        0 ✅ COMPLETE
174lbs         6      6        0 ✅ COMPLETE
184lbs         6      6        0 ✅ COMPLETE
197lbs         6      6        0 ✅ COMPLETE
285lbs         6      6        0 ✅ COMPLETE

====================================================================================================
🔎 CHECKING SPECIFIC IVY LEAGUE NAME PATTERNS
====================================================================================================

Checking 'Marc-Anthony McGowan':
   ✅ Found: Marc-Anthony McGowan (Rank: 13, Team: Princeton)

Checking 'CJ Composto':
   ✅ Found: CJ Composto (Rank: 10, Team: Pennsylvania)

Checking 'AShton Davis':
   🔍 Found by last name 'Davis':
      - TK Davis (Rank: 14, Team: Gardner-Webb)
      - Riley Davis (Rank: 50, Team: Wyoming)
      - JT Davis (Rank: 30, Team: Lehigh)

Checking 'Haden Bottiglieri':
   ✅ Found: Haden Bottiglieri (Rank: 82, Team: Harvard)

Checking 'Louis Cerchio':
   ✅ Found: Louis Cerchio (Rank: 50, Team: Cornell)

Checking 'Khimari Manns':
   ✅ Found: Khimari Manns (Rank: 67, Team: Brown)

====================================================================================================
✅ IVY LEAGUE WRESTLER VERIFICATION COMPLETE
====================================================================================================